#!/usr/bin/env bash
# Provision the wine-free Linux cross-toolchain: MSVC/Windows SDK headers+libs via xwin,
# plus vkd3d-compiler as the fxc stand-in for the SM3 shaders (see tools/hlsl_compile.py).
#
# Everything lands under $TOOLCHAIN_ROOT (default ./.xwin-toolchain, gitignored). Re-running
# is cheap: each step is skipped when its output already exists.
#
# Needs on PATH beforehand: clang-cl, lld-link, llvm-rc, llvm-lib, llvm-mt, cmake >= 3.29,
# ninja, python3, curl, tar. On Debian/Ubuntu: clang lld llvm ninja-build python3.
set -euo pipefail

TOOLCHAIN_ROOT=${TOOLCHAIN_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/.xwin-toolchain}
XWIN_VERSION=${XWIN_VERSION:-0.10.0}
# 1.6 (what most distros package) miscompiles these shaders; keep this in step with
# VKD3D_MINIMUM_VERSION in GWToolboxdll/CMakeLists.txt.
VKD3D_VERSION=${VKD3D_VERSION:-1.19}

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
mkdir -p "$TOOLCHAIN_ROOT"
cd "$TOOLCHAIN_ROOT"

if [ ! -d xwin-sdk ]; then
    echo "==> downloading xwin ${XWIN_VERSION}"
    curl -fsSL "https://github.com/Jake-Shadle/xwin/releases/download/${XWIN_VERSION}/xwin-${XWIN_VERSION}-x86_64-unknown-linux-musl.tar.gz" \
        | tar -xz
    # --include-debug-libs: without msvcrtd/libcmtd even CMake's own compiler check fails,
    # since its default Debug config links /MDd.
    echo "==> splatting the MSVC + Windows SDK (x86, ~800MB)"
    "./xwin-${XWIN_VERSION}-x86_64-unknown-linux-musl/xwin" \
        --accept-license --arch x86 splat --include-debug-libs --output ./xwin-sdk
fi

# The SDK ships each header under its canonical casing plus an all-lowercase alias, but the
# codebase (and vendored GWCA) spell some of them a third way -- <Shlobj.h>, <ShellApi.h>,
# <DelayImp.h>. Wine's case-insensitive VFS hides this; a native Linux clang does not.
# Link every spelling the sources actually use, skipping any name that already resolves.
echo "==> linking SDK headers for the casings the sources use"
INCLUDE_DIRS=(crt/include sdk/include/ucrt sdk/include/um sdk/include/shared sdk/include/winrt)
grep -rhoP '(?<=#include <)[A-Za-z0-9_./\\-]+(?=>)' \
        --include=*.cpp --include=*.h --include=*.hpp --include=*.inl \
        "$REPO_ROOT"/{Core,GWToolboxdll,GWToolbox,RestClient,plugins,Dependencies} 2>/dev/null \
    | sort -u \
    | while read -r included; do
        relative=${included//\\//}
        for directory in "${INCLUDE_DIRS[@]}"; do
            [ -e "xwin-sdk/$directory/$relative" ] && continue 2
        done
        basename=$(basename "$relative")
        actual=$(find xwin-sdk/crt/include xwin-sdk/sdk/include -maxdepth 2 -iname "$basename" 2>/dev/null | head -1)
        [ -n "$actual" ] || continue
        # Never link a name onto itself: that replaces the real header with a symlink loop.
        [ "$(basename "$actual")" = "$basename" ] && continue
        ln -sfn "$(basename "$actual")" "$(dirname "$actual")/$basename"
    done

if [ ! -x "vkd3d-${VKD3D_VERSION}/vkd3d-compiler" ]; then
    echo "==> building vkd3d-compiler ${VKD3D_VERSION}"
    # The release tarball, not git: the git tree generates headers with widl, which comes
    # from wine -- the one thing this toolchain exists to avoid.
    [ -d "vkd3d-${VKD3D_VERSION}" ] || curl -fsSL "https://dl.winehq.org/vkd3d/source/vkd3d-${VKD3D_VERSION}.tar.xz" | tar -xJ
    [ -d SPIRV-Headers ] || git clone --depth 1 https://github.com/KhronosGroup/SPIRV-Headers.git SPIRV-Headers
    (
        cd "vkd3d-${VKD3D_VERSION}"
        # Generated by the release script, absent from the tarball; only vkd3d's --version uses it.
        [ -f include/private/vkd3d_version.h ] || echo "#define VKD3D_VCS_ID \" (${VKD3D_VERSION})\"" > include/private/vkd3d_version.h
        [ -f Makefile ] || ./configure --prefix="$PWD/inst" CPPFLAGS="-I$PWD/../SPIRV-Headers/include" >/dev/null
        # Only the shader compiler; libvkd3d proper is the D3D12 runtime and irrelevant here.
        make -j"$(nproc)" vkd3d-compiler
    )
fi

cat <<EOF

Toolchain ready. Configure and build with:

    export XWIN_SDK="${TOOLCHAIN_ROOT}/xwin-sdk"
    export VKD3D_COMPILER="${TOOLCHAIN_ROOT}/vkd3d-${VKD3D_VERSION}/vkd3d-compiler"
    cmake --preset xwin
    cmake --build build-xwin -j\$(nproc)
EOF
