#pragma once

namespace GW {
    namespace Constants {
        enum class MapID : uint32_t {
            None = 0,
            Gladiators_Arena,
            DEV_Test_Arena_1v1,
            Test_map,
            Warriors_Isle_outpost,
            Hunters_Isle_outpost,
            Wizards_Isle_outpost,
            Warriors_Isle,
            Hunters_Isle,
            Wizards_Isle,
            Bloodstone_Fen,
            The_Wilds,
            Aurora_Glade,
            Diessa_Lowlands,
            Gates_of_Kryta,
            DAlessio_Seaboard,
            Divinity_Coast,
            Talmark_Wilderness,
            The_Black_Curtain,
            Sanctum_Cay,
            Droknars_Forge_outpost,
            The_Frost_Gate,
            Ice_Caves_of_Sorrow,
            Thunderhead_Keep,
            Iron_Mines_of_Moladune,
            Borlis_Pass,
            Talus_Chute,
            Griffons_Mouth,
            The_Great_Northern_Wall,
            Fort_Ranik,
            Ruins_of_Surmia,
            Xaquang_Skyway,
            Nolani_Academy,
            Old_Ascalon,
            The_Fissure_of_Woe,
            Ember_Light_Camp_outpost,
            Grendich_Courthouse_outpost,
            Glints_Challenge_mission,
            Augury_Rock_outpost,
            Sardelac_Sanitarium_outpost,
            Piken_Square_outpost,
            Sage_Lands,
            Mamnoon_Lagoon,
            Silverwood,
            Ettins_Back,
            Reed_Bog,
            The_Falls,
            Dry_Top,
            Tangle_Root,
            Henge_of_Denravi_outpost,

            Senjis_Corner_outpost = 51,
            Burning_Isle_outpost,
            Tears_of_the_Fallen,
            Scoundrels_Rise,
            Lions_Arch_outpost,
            Cursed_Lands,
            Bergen_Hot_Springs_outpost,
            North_Kryta_Province,
            Nebo_Terrace,
            Majestys_Rest,
            Twin_Serpent_Lakes,
            Watchtower_Coast,
            Stingray_Strand,
            Kessex_Peak,
            DAlessio_Arena_mission,

            Burning_Isle = 67,
            Frozen_Isle,
            Nomads_Isle,
            Druids_Isle,
            Isle_of_the_Dead_guild_hall,
            The_Underworld,
            Riverside_Province,

            The_Hall_of_Heroes_arena_mission = 75,
            Broken_Tower_mission,
            House_zu_Heltzer_outpost,
            The_Courtyard_arena_mission,
            Unholy_Temples_mission,
            Burial_Mounds_mission,
            Ascalon_City_outpost,
            Tomb_of_the_Primeval_Kings,
            The_Vault_mission,
            The_Underworld_arena_mission,
            Ascalon_Arena,
            Sacred_Temples_mission,
            Icedome,
            Iron_Horse_Mine,
            Anvil_Rock,
            Lornars_Pass,
            Snake_Dance,
            Tascas_Demise,
            Spearhead_Peak,
            Ice_Floe,
            Witmans_Folly,
            Mineral_Springs,
            Dreadnoughts_Drift,
            Frozen_Forest,
            Travelers_Vale,
            Deldrimor_Bowl,
            Regent_Valley,
            The_Breach,
            Ascalon_Foothills,
            Pockmark_Flats,
            Dragons_Gullet,
            Flame_Temple_Corridor,
            Eastern_Frontier,
            The_Scar,
            The_Amnoon_Oasis_outpost,
            Diviners_Ascent,
            Vulture_Drifts,
            The_Arid_Sea,
            Prophets_Path,
            Salt_Flats,
            Skyward_Reach,
            Dunes_of_Despair,
            Thirsty_River,
            Elona_Reach,
            Augury_Rock_mission,
            The_Dragons_Lair,
            Perdition_Rock,
            Ring_of_Fire,
            Abaddons_Mouth,
            Hells_Precipice,
            Titans_Tears,

            Golden_Gates_mission,
            Scarred_Earth2,
            The_Eternal_Grove,
            Lutgardis_Conservatory_outpost,
            Vasburg_Armory_outpost,
            Serenity_Temple_outpost,
            Ice_Tooth_Cave_outpost,
            Beacons_Perch_outpost,
            Yaks_Bend_outpost,
            Frontier_Gate_outpost,
            Beetletun_outpost,
            Fishermens_Haven_outpost,
            Temple_of_the_Ages,
            Ventaris_Refuge_outpost,
            Druids_Overlook_outpost,
            Maguuma_Stade_outpost,
            Quarrel_Falls_outpost,

            Gyala_Hatchery = 144,
            The_Catacombs,
            Lakeside_County,
            The_Northlands,
            Ascalon_City_pre_searing,       // ?
            Ascalon_Academy,
            Ascalon_Academy_PvP_battle_mission,
            Ascalon_Academy_unk,
            Heroes_Audience_outpost,
            Seekers_Passage_outpost,
            Destinys_Gorge_outpost,
            Camp_Rankor_outpost,
            The_Granite_Citadel_outpost,
            Marhans_Grotto_outpost,
            Port_Sledge_outpost,
            Copperhammer_Mines_outpost,
            Green_Hills_County,
            Wizards_Folly,
            Regent_Valley_pre_Searing,
            The_Barradin_Estate_outpost,
            Ashford_Abbey_outpost,
            Foibles_Fair_outpost,
            Fort_Ranik_pre_Searing_outpost,
            Burning_Isle_mission,
            Druids_Isle_mission,

            Frozen_Isle_mission = 170,
            Warriors_Isle_mission,
            Hunters_Isle_mission,
            Wizards_Isle_mission,
            Nomads_Isle_mission,
            Isle_of_the_Dead_guild_hall_mission,
            Frozen_Isle_outpost,
            Nomads_Isle_outpost,
            Druids_Isle_outpost,
            Isle_of_the_Dead_guild_hall_outpost,
            Fort_Koga_mission,
            Shiverpeak_Arena,
            Amnoon_Arena_mission,
            Deldrimor_Arena_mission,
            The_Crag_mission,

            Random_Arenas_outpost = 188,
            Team_Arenas_outpost,
            Sorrows_Furnace,
            Grenths_Footprint,

            Cavalon_outpost = 193,
            Kaineng_Center_outpost,
            Drazach_Thicket,
            Jaya_Bluffs,
            Shenzun_Tunnels,
            Archipelagos,
            Maishang_Hills,
            Mount_Qinkai,
            Melandrus_Hope,
            Rheas_Crater,
            Silent_Surf,
            Unwaking_Waters_mission,
            Morostav_Trail,
            Deldrimor_War_Camp_outpost,

            Heroes_Crypt_mission = 208,
            Mourning_Veil_Falls,
            Ferndale,
            Pongmei_Valley,
            Monastery_Overlook1,
            Zen_Daijun_outpost_mission,
            Minister_Chos_Estate_outpost_mission,
            Vizunah_Square_mission,
            Nahpui_Quarter_outpost_mission,
            Tahnnakai_Temple_outpost_mission,
            Arborstone_outpost_mission,
            Boreas_Seabed_outpost_mission,
            Sunjiang_District_outpost_mission,
            Fort_Aspenwood_mission,
            The_Eternal_Grove_outpost_mission,
            The_Jade_Quarry_mission,
            Gyala_Hatchery_outpost_mission,
            Raisu_Palace_outpost_mission,
            Imperial_Sanctum_outpost_mission,
            Unwaking_Waters,
            Grenz_Frontier_mission,

            Amatz_Basin = 230,

            Shadows_Passage = 232,
            Raisu_Palace,
            The_Aurios_Mines,
            Panjiang_Peninsula,
            Kinya_Province,
            Haiju_Lagoon,
            Sunqua_Vale,
            Wajjun_Bazaar,
            Bukdek_Byway,
            The_Undercity,
            Shing_Jea_Monastery_outpost,
            Shing_Jea_Arena,
            Arborstone_explorable,
            Minister_Chos_Estate_explorable,
            Zen_Daijun_explorable,
            Boreas_Seabed_explorable,
            Great_Temple_of_Balthazar_outpost,
            Tsumei_Village_outpost,
            Seitung_Harbor_outpost,
            Ran_Musu_Gardens_outpost,
            Linnok_Courtyard,
            Dwayna_Vs_Grenth,

            Sunjiang_District_explorable = 256,

            Nahpui_Quarter_explorable = 265,
            Urgozs_Warren,

            Tahnnakai_Temple_explorable = 269,

            Altrumm_Ruins = 272,
            Zos_Shivros_Channel,
            Dragons_Throat,
            Isle_of_Weeping_Stone_outpost,
            Isle_of_Jade_outpost,
            Harvest_Temple_outpost,
            Breaker_Hollow_outpost,
            Leviathan_Pits_outpost,
            Isle_of_the_Nameless,
            Zaishen_Challenge_outpost,
            Zaishen_Elite_outpost,
            Maatu_Keep_outpost,
            Zin_Ku_Corridor_outpost,
            Monastery_Overlook2,
            Brauer_Academy_outpost,
            Durheim_Archives_outpost,
            Bai_Paasu_Reach_outpost,
            Seafarers_Rest_outpost,
            Bejunkan_Pier,
            Vizunah_Square_Local_Quarter_outpost,
            Vizunah_Square_Foreign_Quarter_outpost,
            Fort_Aspenwood_Luxon_outpost,
            Fort_Aspenwood_Kurzick_outpost,
            The_Jade_Quarry_Luxon_outpost,
            The_Jade_Quarry_Kurzick_outpost,
            Unwaking_Waters_Luxon_outpost,
            Unwaking_Waters_Kurzick_outpost,

            Etnaran_Keys_mission = 300,
            Raisu_Pavilion,
            Kaineng_Docks,
            The_Marketplace_outpost,

            The_Deep = 307,
            Ascalon_Arena_mission,
            Annihilation_mission,
            Kill_Count_Training_mission,
            Priest_Annihilation_Training,
            Obelisk_Annihilation_Training_mission,
            Saoshang_Trail,
            Shiverpeak_Arena_mission,

            DAlessio_Arena_mission3 = 318,
            Amnoon_Arena_mission3,
            Fort_Koga_mission3,
            Heroes_Crypt_mission3,
            Shiverpeak_Arena_mission3,

            Saltspray_Beach_Luxon_outpost = 328,
            Saltspray_Beach_Kurzick_outpost,
            Heroes_Ascent_outpost,
            Grenz_Frontier_Luxon_outpost,
            Grenz_Frontier_Kurzick_outpost,
            The_Ancestral_Lands_Luxon_outpost,
            The_Ancestral_Lands_Kurzick_outpost,
            Etnaran_Keys_Luxon_outpost,
            Etnaran_Keys_Kurzick_outpost,
            Kaanai_Canyon_Luxon_outpost,
            Kaanai_Canyon_Kurzick_outpost,
            DAlessio_Arena_mission2,
            Amnoon_Arena_mission2,
            Fort_Koga_mission2,
            Heroes_Crypt_mission2,
            Shiverpeak_Arena_mission2,
            The_Hall_of_Heroes,
            The_Courtyard,
            Scarred_Earth,
            The_Underworld_PvP,
            Tanglewood_Copse_outpost,
            Saint_Anjekas_Shrine_outpost,
            Eredon_Terrace_outpost,
            Divine_Path,
            Brawlers_Pit_mission,
            Petrified_Arena_mission,
            Seabed_Arena_mission,
            Isle_of_Weeping_Stone_mission,
            Isle_of_Jade_mission,
            Imperial_Isle_mission,
            Isle_of_Meditation_mission,
            Imperial_Isle_outpost,
            Isle_of_Meditation_outpost,
            Isle_of_Weeping_Stone,
            Isle_of_Jade,
            Imperial_Isle,
            Isle_of_Meditation,

            Shing_Jea_Arena_mission = 366,

            Dragon_Arena = 368,
            Jahai_Bluffs,
            Kamadan_mission,
            Marga_Coast,
            Fahranur_mission,
            Sunward_Marches,

            Barbarous_Shore = 375,
            Camp_Hojanu_outpost,
            Bahdok_Caverns,
            Wehhan_Terraces_outpost,
            Dejarin_Estate,
            Arkjok_Ward,
            Yohlon_Haven_outpost,
            Gandara_the_Moon_Fortress,

            The_Floodplain_of_Mahnkelon = 384,
            Lions_Arch_Sunspears_in_Kryta,
            Turais_Procession,
            Sunspear_Sanctuary_outpost,
            Aspenwood_Gate_Kurzick_outpost,
            Aspenwood_Gate_Luxon_outpost,
            Jade_Flats_Kurzick_outpost,
            Jade_Flats_Luxon_outpost,
            Yatendi_Canyons,
            Chantry_of_Secrets_outpost,
            Garden_of_Seborhin,
            Holdings_of_Chokhin,
            Mihanu_Township_outpost,
            Vehjin_Mines,
            Basalt_Grotto_outpost,
            Forum_Highlands,
            Kaineng_Center_Sunspears_in_Cantha,

            Resplendent_Makuun = 402,
            Honur_Hill_outpost,
            Wilderness_of_Bahdza,

            Vehtendi_Valley = 406,
            Yahnur_Market_outpost,

            The_Hidden_City_of_Ahdashim = 413,
            The_Kodash_Bazaar_outpost,
            Lions_Gate,

            The_Mirror_of_Lyss = 419,
            Secure_the_Refuge,
            Venta_Cemetery,
            Kamadan_Jewel_of_Istan_explorable,
            The_Tribunal,
            Kodonur_Crossroads,
            Rilohn_Refuge,
            Pogahn_Passage,
            Moddok_Crevice,
            Tihark_Orchard,
            Consulate,
            Plains_of_Jarin,
            Sunspear_Great_Hall_outpost,
            Cliffs_of_Dohjok,
            Dzagonur_Bastion,
            Dasha_Vestibule,
            Grand_Court_of_Sebelkeh,
            Command_Post,
            Jokos_Domain,
            Bone_Palace_outpost,
            The_Ruptured_Heart,
            The_Mouth_of_Torment_outpost,
            The_Shattered_Ravines,
            Lair_of_the_Forgotten_outpost,
            Poisoned_Outcrops,
            The_Sulfurous_Wastes,
            The_Ebony_Citadel_of_Mallyx_mission,
            The_Alkali_Pan,
            A_Land_of_Heroes,
            Crystal_Overlook,
            Kamadan_Jewel_of_Istan_outpost,
            Gate_of_Torment_outpost,

            Nightfallen_Garden = 455,
            Churrhir_Fields,
            Beknur_Harbor_outpost,

            The_Underworld2 = 461,
            Heart_of_Abaddon,
            The_Underworld3,
            Nightfallen_Coast,
            Nightfallen_Jahai,
            Depths_of_Madness,
            Rollerbeetle_Racing,
            Domain_of_Fear,
            Gate_of_Fear_outpost,
            Domain_of_Pain,
            Bloodstone_Fen_quest,
            Domain_of_Secrets,
            Gate_of_Secrets_outpost,
            Domain_of_Anguish,

            Ooze_Pit_mission = 475,
            Jennurs_Horde,
            Nundu_Bay,
            Gate_of_Desolation,
            Champions_Dawn_outpost,
            Ruins_of_Morah,
            Fahranur_The_First_City,
            Bjora_Marches,
            Zehlon_Reach,
            Lahtenda_Bog,
            Arbor_Bay,
            Issnur_Isles,
            Beknur_Harbor,
            Mehtani_Keys,
            Kodlonu_Hamlet_outpost,
            Island_of_Shehkah,
            Jokanur_Diggings,
            Blacktide_Den,
            Consulate_Docks,
            Gate_of_Pain,
            Gate_of_Madness,
            Abaddons_Gate,
            Sunspear_Arena,

            Ice_Cliff_Chasms = 499,
            Bokka_Amphitheatre,
            Riven_Earth,
            The_Astralarium_outpost,
            Throne_of_Secrets,
            Churranu_Island_Arena_mission,
            Shing_Jea_Monastery_mission,
            Haiju_Lagoon_mission,
            Jaya_Bluffs_mission,
            Seitung_Harbor_mission,
            Tsumei_Village_mission,
            Seitung_Harbor_mission_2,
            Tsumei_Village_mission_2,

            Drakkar_Lake = 513,

            Minister_Chos_Estate_mission_2 = 512,

            Uncharted_Isle_outpost = 529,
            Isle_of_Wurms_outpost,
            Uncharted_Isle,
            Isle_of_Wurms,
            Uncharted_Isle_mission,
            Isle_of_Wurms_mission,

            Sunspear_Arena_mission = 536,
            Corrupted_Isle_outpost,
            Isle_of_Solitude_outpost,
            Corrupted_Isle,
            Isle_of_Solitude,
            Corrupted_Isle_mission,
            Isle_of_Solitude_mission,
            Sun_Docks,
            Chahbek_Village,
            Remains_of_Sahlahja,
            Jaga_Moraine,
            Bombardment_mission,
            Norrhart_Domains,
            Hero_Battles_outpost,
            The_Beachhead_mission,
            The_Crossing_mission,
            Desert_Sands_mission,
            Varajar_Fells,
            Dajkah_Inlet,
            The_Shadow_Nexus,

            Sparkfly_Swamp = 558,
            Gate_of_the_Nightfallen_Lands_outpost,
            Cathedral_of_Flames_Level_1,
            The_Troubled_Keeper,

            Verdant_Cascades = 566,
            Cathedral_of_Flames_Level_2,
            Cathedral_of_Flames_Level_3,
            Magus_Stones,
            Catacombs_of_Kathandrax_Level_1,
            Catacombs_of_Kathandrax_Level_2,
            Alcazia_Tangle,
            Rragars_Menagerie_Level_1,
            Rragars_Menagerie_Level_2,
            Rragars_Menagerie_Level_3,
            Ooze_Pit,
            Slavers_Exile_Level_1,
            Oolas_Lab_Level_1,
            Oolas_Lab_Level_2,
            Oolas_Lab_Level_3,
            Shards_of_Orr_Level_1,
            Shards_of_Orr_Level_2,
            Shards_of_Orr_Level_3,
            Arachnis_Haunt_Level_1,
            Arachnis_Haunt_Level_2,

            Fetid_River_mission = 593,

            Forgotten_Shrines_mission = 596,

            Antechamber_mission = 598,

            Vloxen_Excavations_Level_1 = 604,
            Vloxen_Excavations_Level_2,
            Vloxen_Excavations_Level_3,
            Heart_of_the_Shiverpeaks_Level_1,
            Heart_of_the_Shiverpeaks_Level_2,
            Heart_of_the_Shiverpeaks_Level_3,

            Bloodstone_Caves_Level_1 = 612,
            Bloodstone_Caves_Level_2,
            Bloodstone_Caves_Level_3,
            Bogroot_Growths_Level_1,
            Bogroot_Growths_Level_2,
            Ravens_Point_Level_1,
            Ravens_Point_Level_2,
            Ravens_Point_Level_3,
            Slavers_Exile_Level_2,
            Slavers_Exile_Level_3,
            Slavers_Exile_Level_4,
            Slavers_Exile_Level_5,
            Vloxs_Falls,
            Battledepths_Level_1,
            Battledepths_Level_2,
            Battledepths_Level_3,
            Sepulchre_of_Dragrimmar_Level_1,
            Sepulchre_of_Dragrimmar_Level_2,
            Frostmaws_Burrows_Level_1,
            Frostmaws_Burrows_Level_2,
            Frostmaws_Burrows_Level_3,
            Frostmaws_Burrows_Level_4,
            Frostmaws_Burrows_Level_5,
            Darkrime_Delves_Level_1,
            Darkrime_Delves_Level_2,
            Darkrime_Delves_Level_3,
            Gadds_Encampment_outpost,
            Umbral_Grotto_outpost,
            Rata_Sum_outpost,
            Tarnished_Haven_outpost,
            Eye_of_the_North_outpost,
            Sifhalla_outpost,
            Gunnars_Hold_outpost,
            Olafstead_outpost,
            Hall_of_Monuments,
            Dalada_Uplands,
            Doomlore_Shrine_outpost,
            Grothmar_Wardowns,
            Longeyes_Ledge_outpost,
            Sacnoth_Valley,
            Central_Transfer_Chamber_outpost,
            Curse_of_the_Nornbear,
            Blood_Washes_Blood,
            A_Gate_Too_Far_Level_1,
            A_Gate_Too_Far_Level_2,
            A_Gate_Too_Far_Level_3,
            The_Elusive_Golemancer_Level_1,
            The_Elusive_Golemancer_Level_2,
            The_Elusive_Golemancer_Level_3,
            Finding_the_Bloodstone_Level_1,
            Finding_the_Bloodstone_Level_2,
            Finding_the_Bloodstone_Level_3,
            Genius_Operated_Living_Enchanted_Manifestation,
            Against_the_Charr,
            Warband_of_Brothers_Level_1,
            Warband_of_Brothers_Level_2,
            Warband_of_Brothers_Level_3,
            Assault_on_the_Stronghold,
            Destructions_Depths_Level_1,
            Destructions_Depths_Level_2,
            Destructions_Depths_Level_3,
            A_Time_for_Heroes,
            Warband_Training,
            Boreal_Station_outpost,
            Catacombs_of_Kathandrax_Level_3,

            Attack_of_the_Nornbear = 678,
            Cinematic_Cave_Norn_Cursed,
            Cinematic_Steppe_Interrogation,
            Cinematic_Interior_Research,
            Cinematic_Eye_Vision_A,
            Cinematic_Eye_Vision_B,
            Cinematic_Eye_Vision_C,
            Cinematic_Eye_Vision_D,
            Polymock_Coliseum,
            Polymock_Glacier,
            Polymock_Crossing,
            Cinematic_Mountain_Resolution,
            Cold_as_Ice,
            Beneath_Lions_Arch,
            Tunnels_Below_Cantha,
            Caverns_Below_Kamadan,
            Cinematic_Mountain_Dwarfs,
            Service_In_Defense_of_the_Eye,
            Mano_a_Norn_o,
            Service_Practice_Dummy,
            Hero_Tutorial,

            The_Norn_Fighting_Tournament = 700,
            Secret_Lair_of_the_Snowmen,
            Norn_Brawling_Championship,
            Kilroys_Punchout_Training,
            Fronis_Irontoes_Lair_mission,
            The_Justiciars_End,

            The_Great_Norn_Alemoot = 707,
            Varajar_Fells_unknown,          // quest map? cinematic?

            Epilogue = 710,
            Insidious_Remnants,

            Attack_on_Jaliss_Camp = 717,

            Costume_Brawl_outpost = 721,
            Whitefury_Rapids_mission,
            Kysten_Shore_mission,
            Deepway_Ruins_mission,
            Plikkup_Works_mission,
            Kilroys_Punchout_Tournament,
            Special_Ops_Flame_Temple_Corridor,
            Special_Ops_Dragons_Gullet,
            Special_Ops_Grendich_Courthouse,
            The_Tengu_Accords,
            The_Battle_of_Jahai,
            The_Flight_North,
            The_Rise_of_the_White_Mantle,

            // "Mission" maps, used for icon status on world map
            Finding_the_Bloodstone_mission = 759,
            Genius_Operated_Living_Enchanted_Manifestation_mission,
            Against_the_Charr_mission,
            Warband_of_brothers_mission,
            Assault_on_the_Stronghold_mission,
            Destructions_Depths_mission,
            A_Time_for_Heroes_mission,
            Curse_of_the_Nornbear_mission,
            Blood_Washes_Blood_mission,
            A_Gate_Too_Far_mission,
            The_Elusive_Golemancer_mission,

            Secret_Lair_of_the_Snowmen2 = 781,  // ?
            Secret_Lair_of_the_Snowmen3,        // ?
            Droknars_Forge_cinematic,           // ?
            Isle_of_the_Nameless_PvP,

            Temple_of_the_Ages_ROX = 788,
            Wajjun_Bazaar_POX,
            Bokka_Amphitheatre_NOX,
            Secret_Underground_Lair,
            Golem_Tutorial_Simulation,
            Snowball_Dominance,
            Zaishen_Menagerie_Grounds,
            Zaishen_Menagerie_outpost,
            Codex_Arena_outpost,
            The_Underworld_Something_Wicked_This_Way_Comes = 806,
            The_Underworld_Dont_Fear_the_Reapers,
            Lions_Arch_Halloween_outpost,
            Lions_Arch_Wintersday_outpost,
            Lions_Arch_Canthan_New_Year_outpost,
            Ascalon_City_Wintersday_outpost,
            Droknars_Forge_Halloween_outpost,
            Droknars_Forge_Wintersday_outpost,
            Tomb_of_the_Primeval_Kings_Halloween_outpost,
            Shing_Jea_Monastery_Dragon_Festival_outpost,
            Shing_Jea_Monastery_Canthan_New_Year_outpost,
            Kaineng_Center_Canthan_New_Year_outpost,
            Kamadan_Jewel_of_Istan_Halloween_outpost,
            Kamadan_Jewel_of_Istan_Wintersday_outpost,
            Kamadan_Jewel_of_Istan_Canthan_New_Year_outpost,
            Eye_of_the_North_outpost_Wintersday_outpost,

            War_in_Kryta_Talmark_Wilderness = 837,
            War_in_Kryta_Trial_of_Zinn,
            War_in_Kryta_Divinity_Coast,
            War_in_Kryta_Lions_Arch_Keep,
            War_in_Kryta_DAlessio_Seaboard,
            War_in_Kryta_The_Battle_for_Lions_Arch,
            War_in_Kryta_Riverside_Province, // cinematic ?
            War_in_Kryta_Lions_Arch,
            War_in_Kryta_The_Mausoleum,
            War_in_Kryta_Rise,
            War_in_Kryta_Shadows_in_the_Jungle,
            War_in_Kryta_A_Vengeance_of_Blades,
            War_in_Kryta_Auspicious_Beginnings,

            Olafstead_cinematic = 854,
            The_Great_Snowball_Fight_of_the_Gods__Operation_Crush_Spirits,
            The_Great_Snowball_Fight_of_the_Gods__Fighting_in_a_Winter_Wonderland,
            Embark_Beach,

            Dragons_Throat_area__What_Waits_in_Shadow = 860,
            Kaineng_Center_Winds_of_Change__A_Chance_Encounter,
            The_Marketplace_area__Tracking_the_Corruption,
            Bukdek_Byway_Winds_of_Change__Cantha_Courier_Crisis,
            Tsumei_Village_Winds_of_Change__A_Treatys_a_Treaty,
            Seitung_Harbor_area__Deadly_Cargo,
            Tahnnakai_Temple_Winds_of_Change__The_Rescue_Attempt,
            Wajjun_Bazaar_Winds_of_Change__Violence_in_the_Streets,
            Scarred_Psyche_mission,
            Shadows_Passage_Winds_of_Change__Calling_All_Thugs,
            Altrumm_Ruins__Finding_Jinnai,
            Shing_Jea_Monastery__Raid_on_Shing_Jea_Monastery,
            Kaineng_Center_Winds_of_Change__Raid_on_Kaineng_Center,
            Wajjun_Bazaar_Winds_of_Change__Ministry_of_Oppression,
            The_Final_Confrontation,
            Lakeside_County_1070_AE,
            Ashford_Catacombs_1070_AE,

            Count,
        };

        // This array needs testing lol.
        constexpr std::array NAME_FROM_ID = {
            "",
            "Gladiators Arena",
            "DEV Test Arena (1v1)",
            "Test Map",
            "Warriors Isle",
            "Hunters Isle",
            "Wizards Isle",
            "Warriors Isle",
            "Hunters Isle",
            "Wizards Isle",
            "Bloodstone Fen",
            "The Wilds",
            "Aurora Glade",
            "Diessa Lowlands",
            "Gates of Kryta",
            "DAlessio Seaboard",
            "Divinity Coast",
            "Talmark Wilderness",
            "The Black Curtain",
            "Sanctum Cay",
            "Droknars Forge",
            "The Frost Gate",
            "Ice Caves of Sorrow",
            "Thunderhead Keep",
            "Iron Mines of Moladune",
            "Borlis Pass",
            "Talus Chute",
            "Griffons Mouth",
            "The Great Northern Wall",
            "Fort Ranik",
            "Ruins of Surmia",
            "Xaquang Skyway",
            "Nolani Academy",
            "Old Ascalon",
            "The Fissure of Woe",
            "Ember Light Camp",
            "Grendich Courthouse",
            "Glints Challenge",
            "Augury Rock",
            "Sardelac Sanitarium",
            "Piken Square",
            "Sage Lands",
            "Mamnoon Lagoon",
            "Silverwood",
            "Ettins Back",
            "Reed Bog",
            "The Falls",
            "Dry Top",
            "Tangle Root",
            "Henge of Denravi",
            "Test Map",
            "Senjis Corner",
            "Burning Isle",
            "Tears of the Fallen",
            "Scoundrels Rise",
            "Lions Arch",
            "Cursed Lands",
            "Bergen Hot Springs",
            "North Kryta Province",
            "Nebo Terrace",
            "Majestys Rest",
            "Twin Serpent Lakes",
            "Watchtower Coast",
            "Stingray Strand",
            "Kessex Peak",
            "DAlessio Arena",
            "All Call Click Point 1",
            "Burning Isle",
            "Frozen Isle",
            "Nomads Isle",
            "Druids Isle",
            "Isle of the Dead",
            "The Underworld",
            "Riverside Province",
            "Tournament 6",
            "The Hall of Heroes",
            "Broken Tower",
            "House zu Heltzer",
            "The Courtyard",
            "Unholy Temples",
            "Burial Mounds",
            "Ascalon City",
            "Tomb of the Primeval Kings",
            "The Vault",
            "The Underworld",
            "Ascalon Arena",
            "Sacred Temples",
            "Icedome",
            "Iron Horse Mine",
            "Anvil Rock",
            "Lornars Pass",
            "Snake Dance",
            "Tascas Demise",
            "Spearhead Peak",
            "Ice Floe",
            "Witmans Folly",
            "Mineral Springs",
            "Dreadnoughts Drift",
            "Frozen Forest",
            "Travelers Vale",
            "Deldrimor Bowl",
            "Regent Valley",
            "The Breach",
            "Ascalon Foothills",
            "Pockmark Flats",
            "Dragons Gullet",
            "Flame Temple Corridor",
            "Eastern Frontier",
            "The Scar",
            "The Amnoon Oasis",
            "Diviners Ascent",
            "Vulture Drifts",
            "The Arid Sea",
            "Prophets Path",
            "Salt Flats",
            "Skyward Reach",
            "Dunes of Despair",
            "Thirsty River",
            "Elona Reach",
            "Augury Rock",
            "The Dragons Lair",
            "Perdition Rock",
            "Ring of Fire",
            "Abaddons Mouth",
            "Hells Precipice",
            "Titans Tears",
            "Golden Gates",
            "Scarred Earth",
            "The Eternal Grove",
            "Lutgardis Conservatory",
            "Vasburg Armory",
            "Serenity Temple",
            "Ice Tooth Cave",
            "Beacons Perch",
            "Yaks Bend",
            "Frontier Gate",
            "Beetletun",
            "Fishermens Haven",
            "Temple of the Ages",
            "Ventaris Refuge",
            "Druids Overlook",
            "Maguuma Stade",
            "Quarrel Falls",
            "Ascalon Academy",
            "Gyala Hatchery",
            "The Catacombs",
            "Lakeside County",
            "The Northlands",
            "Ascalon City",
            "Ascalon Academy",
            "Ascalon Academy",
            "Ascalon Academy",
            "Heroes Audience",
            "Seekers Passage",
            "Destinys Gorge",
            "Camp Rankor",
            "The Granite Citadel",
            "Marhans Grotto",
            "Port Sledge",
            "Copperhammer Mines",
            "Green Hills County",
            "Wizards Folly",
            "Regent Valley",
            "The Barradin Estate",
            "Ashford Abbey",
            "Foibles Fair",
            "Fort Ranik",
            "Burning Isle",
            "Druids Isle",
            "[null]",
            "Frozen Isle",
            "Warriors Isle",
            "Hunters Isle",
            "Wizards Isle",
            "Nomads Isle",
            "Isle of the Dead",
            "Frozen Isle",
            "Nomads Isle",
            "Druids Isle",
            "Isle of the Dead",
            "Fort Koga",
            "Shiverpeak Arena",
            "Amnoon Arena",
            "Deldrimor Arena",
            "The Crag",
            "The Underworld",
            "The Underworld",
            "The Underworld",
            "Random Arenas",
            "Team Arenas",
            "Sorrows Furnace",
            "Grenths Footprint",
            "All Call Click Point 2",
            "Cavalon",
            "Kaineng Center",
            "Drazach Thicket",
            "Jaya Bluffs",
            "Shenzun Tunnels",
            "Archipelagos",
            "Maishang Hills",
            "Mount Qinkai",
            "Melandrus Hope",
            "Rheas Crater",
            "Silent Surf",
            "Unwaking Waters",
            "Morostav Trail",
            "Deldrimor War Camp",
            "Dragons Thieves",
            "Heroes Crypt",
            "Mourning Veil Falls",
            "Ferndale",
            "Pongmei Valley",
            "Monastery Overlook",
            "Zen Daijun",
            "Minister Chos Estate",
            "Vizunah Square",
            "Nahpui Quarter",
            "Tahnnakai Temple",
            "Arborstone",
            "Boreas Seabed",
            "Sunjiang District",
            "Fort Aspenwood",
            "The Eternal Grove",
            "The Jade Quarry",
            "Gyala Hatchery",
            "Raisu Palace",
            "Imperial Sanctum",
            "Unwaking Waters",
            "Grenz Frontier",
            "The Ancestral Lands",
            "Amatz Basin",
            "Kaanai Canyon",
            "Shadows Passage",
            "Raisu Palace",
            "The Aurios Mines",
            "Panjiang Peninsula",
            "Kinya Province",
            "Haiju Lagoon",
            "Sunqua Vale",
            "Wajjun Bazaar",
            "Bukdek Byway",
            "The Undercity",
            "Shing Jea Monastery",
            "Shing Jea Arena",
            "Arborstone",
            "Minister Chos Estate",
            "Zen Daijun",
            "Boreas Seabed",
            "Great Temple of Balthazar",
            "Tsumei Village",
            "Seitung Harbor",
            "Ran Musu Gardens",
            "Linnok Courtyard",
            "Dwayna Vs Grenth",
            "Dwaynas Camp",
            "Grenths Camp",
            "Sunjiang District",
            "Minister Chos Estate",
            "Zen Daijun",
            "The Jade Quarry (Kurzick)",
            "Nahpui Quarter",
            "Tahnnakai Temple",
            "Arborstone",
            "Boreas Seabed",
            "Sunjiang District",
            "Nahpui Quarter",
            "Urgozs Warren",
            "The Eternal Grove",
            "Gyala Hatchery",
            "Tahnnakai Temple",
            "Raisu Palace",
            "Imperial Sanctum",
            "Altrumm Ruins",
            "Zos Shivros Channel",
            "Dragons Throat",
            "Isle of Weeping Stone",
            "Isle of Jade",
            "Harvest Temple",
            "Breaker Hollow",
            "Leviathan Pits",
            "Isle of the Nameless",
            "Zaishen Challenge",
            "Zaishen Elite",
            "Maatu Keep",
            "Zin Ku Corridor",
            "Monastery Overlook",
            "Brauer Academy",
            "Durheim Archives",
            "Bai Paasu Reach",
            "Seafarers Rest",
            "Bejunkan Pier",
            "Vizunah Square (Local Quarter)",
            "Vizunah Square (Foreign Quarter)",
            "Fort Aspenwood (Luxon)",
            "Fort Aspenwood (Kurzick)",
            "The Jade Quarry (Luxon)",
            "The Jade Quarry (Kurzick)",
            "Unwaking Waters (Luxon)",
            "Unwaking Waters (Kurzick)",
            "Saltspray Beach",
            "Etnaran Keys",
            "Raisu Pavilion",
            "Kaineng Docks",
            "The Marketplace",
            "Vizunah Square (Local Quarter)",
            "Vizunah Square (Foreign Quarter)",
            "The Jade Quarry (Luxon)",
            "The Deep",
            "Ascalon Arena",
            "Annihilation Training",
            "Kill Count Training",
            "Priest Annihilation Training",
            "Obelisk Annihilation Training",
            "Saoshang Trail",
            "Shiverpeak Arena",
            "Travel",
            "Travel",
            "Travel",
            "DAlessio Arena",
            "Amnoon Arena",
            "Fort Koga",
            "Heroes Crypt",
            "Shiverpeak Arena",
            "Fort Aspenwood (Kurzick)",
            "Fort Aspenwood (Luxon)",
            "The Harvest Ceremony",
            "The Harvest Ceremony",
            "Imperial Sanctum",
            "Saltspray Beach (Luxon)",
            "Saltspray Beach (Kurzick)",
            "Heroes Ascent",
            "Grenz Frontier (Luxon)",
            "Grenz Frontier (Kurzick)",
            "The Ancestral Lands (Luxon)",
            "The Ancestral Lands (Kurzick)",
            "Etnaran Keys (Luxon)",
            "Etnaran Keys (Kurzick)",
            "Kaanai Canyon (Luxon)",
            "Kaanai Canyon (Kurzick)",
            "DAlessio Arena",
            "Amnoon Arena",
            "Fort Koga",
            "Heroes Crypt",
            "Shiverpeak Arena",
            "The Hall of Heroes",
            "The Courtyard",
            "Scarred Earth",
            "The Underworld",
            "Tanglewood Copse",
            "Saint Anjekas Shrine",
            "Eredon Terrace",
            "Divine Path",
            "Brawlers Pit",
            "Petrified Arena",
            "Seabed Arena",
            "Isle of Weeping Stone",
            "Isle of Jade",
            "Imperial Isle",
            "Isle of Meditation",
            "Imperial Isle",
            "Isle of Meditation",
            "Isle of Weeping Stone",
            "Isle of Jade",
            "Imperial Isle",
            "Isle of Meditation",
            "Random Arenas Test",
            "Shing Jea Arena",
            "All Skills",
            "Dragon Arena",
            "Jahai Bluffs",
            "Kamadan",
            "Marga Coast",
            "Fahranur",
            "Sunward Marches",
            "oleplaying Character //Buuug? ",
            "Vortex",
            "Camp Hojanu",
            "Bahdok Caverns",
            "Wehhan Terraces",
            "Dejarin Estate",
            "Arkjok Ward",
            "Yohlon Haven",
            "Gandara",
            "Vortex",
            "The Floodplain of Mahnkelon",
            "Lions Arch",
            "Turais Procession",
            "Sunspear Sanctuary",
            "Aspenwood Gate (Kurzick)",
            "Aspenwood Gate (Luxon)",
            "Jade Flats (Kurzick)",
            "Jade Flats (Luxon)",
            "Yatendi Canyons",
            "Chantry of Secrets",
            "Garden of Seborhin",
            "Holdings of Chokhin",
            "Mihanu Township",
            "Vehjin Mines",
            "Basalt Grotto",
            "Forum Highlands",
            "Kaineng Center",
            "Sebelkeh Basilica",
            "Resplendent Makuun",
            "Honur Hill",
            "Wilderness of Bahdza",
            "Sun Docks",
            "Vehtendi Valley",
            "Yahnur Market",
            "Here Be Dragons",
            "Here Be Dragons",
            "Here Be Dragons",
            "Here Be Dragons",
            "Here Be Dragons",
            "The Hidden City of Ahdashim",
            "The Kodash Bazaar",
            "Lions Gate",
            "Monastery Overlook",
            "Bejunkan Pier",
            "Lions Gate",
            "The Mirror of Lyss",
            "Secure the Refuge",
            "Venta Cemetery",
            "Kamadan",
            "The Tribunal",
            "Kodonur Crossroads",
            "Rilohn Refuge",
            "Pogahn Passage",
            "Moddok Crevice",
            "Tihark Orchard",
            "Consulate",
            "Plains of Jarin",
            "Sunspear Great Hall",
            "Cliffs of Dohjok",
            "Dzagonur Bastion",
            "Dasha Vestibule",
            "Grand Court of Sebelkeh",
            "Command Post",
            "Jokos Domain",
            "Bone Palace",
            "The Ruptured Heart",
            "The Mouth of Torment",
            "The Shattered Ravines",
            "Lair of the Forgotten",
            "Poisoned Outcrops",
            "The Sulfurous Wastes",
            "The Ebony Citadel of Mallyx",
            "The Alkali Pan",
            "Cliffs of Dohjok",
            "Crystal Overlook",
            "Kamadan",
            "Gate of Torment",
            "Gate of Anguish",
            "Secure the Refuge",
            "Evacuation",
            "Test Map",
            "Nightfallen Garden",
            "Churrhir Fields",
            "Beknur Harbor",
            "Kodonur Crossroads",
            "Rilohn Refuge",
            "Pogahn Passage",
            "The Underworld",
            "Heart of Abaddon",
            "The Underworld",
            "Nightfallen Coast",
            "Nightfallen Jahai",
            "Depths of Madness",
            "Rollerbeetle Racing",
            "Domain of Fear",
            "Gate of Fear",
            "Domain of Pain",
            "Bloodstone Fen",
            "Domain of Secrets",
            "Gate of Secrets",
            "Gate of Anguish",
            "Jelly Den",
            "Jennurs Horde",
            "Nundu Bay",
            "Gate of Desolation",
            "Champions Dawn",
            "Ruins of Morah",
            "Fahranur",
            "Bjora Marches",
            "Zehlon Reach",
            "Lahtenda Bog",
            "Arbor Bay",
            "Issnur Isles",
            "Beknur Harbor",
            "Mehtani Keys",
            "Kodlonu Hamlet",
            "Island of Shehkah",
            "Jokanur Diggings",
            "Blacktide Den",
            "Consulate Docks",
            "Gate of Pain",
            "Gate of Madness",
            "Abaddons Gate",
            "Sunspear Arena",
            "Travel",
            "Ice Cliff Chasms",
            "Bokka Amphitheatre",
            "Riven Earth",
            "The Astralarium",
            "Throne Of Secrets",
            "Churranu Island Arena",
            "Shing Jea Monastery",
            "Haiju Lagoon",
            "Jaya Bluffs",
            "Seitung Harbor",
            "Tsumei Village",
            "Seitung Harbor",
            "Tsumei Village",
            "Minister Chos Estate",
            "Drakkar Lake",
            "Island of Shehkah",
            "Jokanur Diggings",
            "Blacktide Den",
            "Consulate Docks",
            "Tihark Orchard",
            "Dzagonur Bastion",
            "Hidden City of Ahdashim",
            "Grand Court of Sebelkeh",
            "Jennurs Horde",
            "Nundu Bay",
            "Gates of Desolation",
            "Ruins of Morah",
            "Domain of Pain",
            "Gate of Madness",
            "Abaddons Gate",
            "Uncharted Isle",
            "Isle of Wurms",
            "Uncharted Isle",
            "Isle of Wurms",
            "Uncharted Isle",
            "Isle of Wurms",
            "Ahmtur Arena",
            "Sunspear Arena",
            "Corrupted Isle",
            "Isle of Solitude",
            "Corrupted Isle",
            "Isle of Solitude",
            "Corrupted Isle",
            "Isle of Solitude",
            "Sun Docks",
            "Chahbek Village",
            "Remains of Sahlahja",
            "Jaga Moraine",
            "Bombardment",
            "Norrhart Domains",
            "Hero Battles",
            "Hero Battles",
            "The Crossing",
            "Desert Sands",
            "Varajar Fells",
            "Dajkah Inlet",
            "The Shadow Nexus",
            "Chahbek Village",
            "Throne Of Secrets",
            "Sparkfly Swamp",
            "Gate of the Nightfallen Lands",
            "Cathedral of Flames",
            "Gate of Torment",
            "Fortress of Jahai",
            "Halls of Chokhin",
            "Citadel of Dzagon",
            "Dynastic Tombs",
            "Verdant Cascades",
            "Cathedral of Flames: Level 2",
            "Cathedral of Flames: Level 3",
            "Magus Stones",
            "Catacombs of Kathandrax",
            "Catacombs of Kathandrax: Level 2",
            "Alcazia Tangle",
            "Rragars Menagerie",
            "Rragars Menagerie: Level 2",
            "Rragars Menagerie: Level 3",
            "Jelly Den: Level 2",
            "Slavers Exile",
            "Oolas Lab",
            "Oolas Lab: Level 2",
            "Oolas Lab: Level 3",
            "Shards of Orr",
            "Shards of Orr: Level 2",
            "Shards of Orr: Level 3",
            "Arachnis Haunt",
            "Arachnis Haunt: Level 2",
            "Burning Embers",
            "Burning Furnace",
            "Burning Temple",
            "Catacombs Lush",
            "Catacombs Stone",
            "Catacombs Tomb",
            "5 team test",
            "Fetid River",
            "Overlook",
            "Cemetery",
            "Forgotten Shrines",
            "Track",
            "The Antechamber",
            "Collision",
            "The Hall of Heroes",
            "Frozen Crevasse",
            "Frozen Depleted",
            "Frozen Fort",
            "Vloxen Excavations",
            "Vloxen Excavations: Level 2",
            "Vloxen Excavations: Level 3",
            "Heart of the Shiverpeaks",
            "Heart of the Shiverpeaks: Level 2",
            "Heart of the Shiverpeaks: Level 3",
            "The Journey to Nornheim",
            "The Journey to Nornheim",
            "Bloodstone Caves",
            "Bloodstone Caves: Level 2",
            "Bloodstone Caves: Level 3",
            "Bogroot Growths",
            "Bogroot Growths: Level 2",
            "Ravens Point",
            "Ravens Point: Level 2",
            "Ravens Point: Level 3",
            "Slavers Exile",
            "Slavers Exile",
            "Slavers Exile",
            "Slavers Exile",
            "Vloxs Falls",
            "Battledepths",
            "Battledepths: Level 2",
            "Battledepths: Level 3",
            "Sepulchre of Dragrimmar",
            "Sepulchre of Dragrimmar: Level 2",
            "Frostmaws Burrows",
            "Frostmaws Burrows: Level 2",
            "Frostmaws Burrows: Level 3",
            "Frostmaws Burrows: Level 4",
            "Frostmaws Burrows: Level 5",
            "Darkrime Delves",
            "Darkrime Delves: Level 2",
            "Darkrime Delves: Level 3",
            "Gadds Encampment",
            "Umbral Grotto",
            "Rata Sum",
            "Tarnished Haven",
            "Eye of the North",
            "Sifhalla",
            "Gunnars Hold",
            "Olafstead",
            "Hall of Monuments",
            "Dalada Uplands",
            "Doomlore Shrine",
            "Grothmar Wardowns",
            "Longeyes Ledge",
            "Sacnoth Valley",
            "Central Transfer Chamber",
            "Revealing the Curse",
            "My Side of the Mountain",
            "Mountain Owl",
            "Mountain Owl",
            "Mountain Owl",
            "Oolas Laboratory",
            "Oolas Laboratory",
            "Oolas Laboratory",
            "Completing Gadds Research",
            "Completing Gadds Research",
            "Completing Gadds Research",
            "Genius Operated Living Enchanted Manifestation",
            "Assaulting the Charr Camp",
            "Freeing Pyres Warband",
            "Freeing Pyres Warband",
            "Freeing Pyres Warband",
            "Freeing the Vanguard",
            "Source of Destruction",
            "Source of Destruction",
            "Source of Destruction",
            "A Time for Heroes",
            "Steppe Practice",
            "Boreal Station",
            "Catacombs of Kathandrax: Level 3",
            "Hall of Primordus",
            "Mountain Holdout",
            "Cinematic Cave Norn Cursed",
            "Cinematic Steppe Interrogation",
            "Cinematic Interior Research",
            "Cinematic Eye Vision A",
            "Cinematic Eye Vision B",
            "Cinematic Eye Vision C",
            "Cinematic Eye Vision D",
            "Polymock Coliseum",
            "Polymock Glacier",
            "Polymock Crossing",
            "Cinematic Mountain Resolution",
            "<Mountain Polar OP>",
            "Beneath Lions Arch",
            "Tunnels Below Cantha",
            "Caverns Below Kamadan",
            "Cinematic Mountain Dwarfs",
            "The Eye of the North",
            "The Eye of the North",
            "The Eye of the North",
            "Hero Tutorial",
            "Prototype Map",
            "The Norn Fighting Tournament",
            "Hundars Resplendent Treasure Vault",
            "Norn Brawling Championship",
            "Kilroys Punchout Training",
            "Fronis Irontoe's Lair",
            "INTERIOR_WATCH_OP1_FINAL_BATTLE",
            "Designer Test Map",
            "The Great Norn Alemoot",
            "(Mountain Traverse)",
            "Battle for Nornheim",
            "Destroyer Ending",
            "Alcazia Tangle",
            "Mission Pack Test",
            "North Kryta Province",
            "Bukdek Byway",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "Plains of Jarin",
            "(crash)"
        };
    }
}
