//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Armor_of_Salvation {
            get {
                object obj = ResourceManager.GetObject("Armor_of_Salvation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balthspirit {
            get {
                object obj = ResourceManager.GetObject("balthspirit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Birthday_Cupcake {
            get {
                object obj = ResourceManager.GetObject("Birthday_Cupcake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Rock_Candy {
            get {
                object obj = ResourceManager.GetObject("Blue_Rock_Candy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bottle_of_Grog {
            get {
                object obj = ResourceManager.GetObject("Bottle_of_Grog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bowl_of_Skalefin_Soup {
            get {
                object obj = ResourceManager.GetObject("Bowl_of_Skalefin_Soup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Candy_Apple {
            get {
                object obj = ResourceManager.GetObject("Candy_Apple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Candy_Corn {
            get {
                object obj = ResourceManager.GetObject("Candy_Corn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment {
            get {
                object obj = ResourceManager.GetObject("comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cupcake {
            get {
                object obj = ResourceManager.GetObject("cupcake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[hotkey-1:SendChat]
        ///msg = age
        ///
        ///
        ///[hotkey-2:SendChat]
        ///msg = stuck
        ///
        ///
        ///[hotkey-3:SendChat]
        ///msg = resign
        ///
        ///
        ///[hotkey-4:DropUseBuff]
        ///SkillID = 925
        ///
        ///
        ///[hotkey-5:Target]
        ///TargetID = 7445
        ///TargetName = Boo
        ///
        ///[hotkey-6:UseItem]
        ///ItemID = 26501
        ///ItemName = Res Scroll
        ///.
        /// </summary>
        internal static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[hotkey-1:SendChat]
        ///msg = age
        ///
        ///
        ///[hotkey-2:SendChat]
        ///msg = stuck
        ///
        ///
        ///[hotkey-3:SendChat]
        ///msg = resign
        ///
        ///
        ///[hotkey-4:DropUseBuff]
        ///SkillID = 925
        ///
        ///
        ///[hotkey-5:Target]
        ///TargetID = 7445
        ///TargetName = Boo
        ///
        ///[hotkey-6:UseItem]
        ///ItemID = 26501
        ///ItemName = Res Scroll
        ///.
        /// </summary>
        internal static string DefaultSettings1 {
            get {
                return ResourceManager.GetString("DefaultSettings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;name&quot; : &quot;Toolbox++&quot;,
        ///	&quot;author&quot; : &quot;Has&quot;,
        ///	&quot;default&quot; : {
        ///		&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///		&quot;backcolor&quot; : [ 90, 0, 0, 0 ]
        ///	},
        ///	&quot;themes&quot; : {
        ///		&quot;button&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 100, 90, 90, 90 ]
        ///		},
        ///		&quot;combobox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 100, 34, 34, 34 ]
        ///		},
        ///		&quot;checkbox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 255, 0, 0, 0 ]
        ///		},
        ///		&quot;textbox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTheme {
            get {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;name&quot; : &quot;Toolbox++&quot;,
        ///	&quot;author&quot; : &quot;Has&quot;,
        ///	&quot;default&quot; : {
        ///		&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///		&quot;backcolor&quot; : [ 90, 0, 0, 0 ]
        ///	},
        ///	&quot;themes&quot; : {
        ///		&quot;button&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 100, 90, 90, 90 ]
        ///		},
        ///		&quot;combobox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 100, 34, 34, 34 ]
        ///		},
        ///		&quot;checkbox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 255, 255 ],
        ///			&quot;backcolor&quot; : [ 255, 0, 0, 0 ]
        ///		},
        ///		&quot;textbox&quot; : {
        ///			&quot;forecolor&quot; : [ 255, 255, 25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTheme1 {
            get {
                return ResourceManager.GetString("DefaultTheme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Drake_Kabob {
            get {
                object obj = ResourceManager.GetObject("Drake_Kabob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dwarven_Ale {
            get {
                object obj = ResourceManager.GetObject("Dwarven_Ale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Essence_of_Celerity {
            get {
                object obj = ResourceManager.GetObject("Essence_of_Celerity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feather {
            get {
                object obj = ResourceManager.GetObject("feather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Friz_Quadrata_Regular {
            get {
                object obj = ResourceManager.GetObject("Friz_Quadrata_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Friz_Quadrata_Regular1 {
            get {
                object obj = ResourceManager.GetObject("Friz_Quadrata_Regular1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fruitcake {
            get {
                object obj = ResourceManager.GetObject("Fruitcake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Golden_Egg {
            get {
                object obj = ResourceManager.GetObject("Golden_Egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grail_of_Might {
            get {
                object obj = ResourceManager.GetObject("Grail_of_Might", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green_Rock_Candy {
            get {
                object obj = ResourceManager.GetObject("Green_Rock_Candy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon gwtoolbox {
            get {
                object obj = ResourceManager.GetObject("gwtoolbox", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lifebond {
            get {
                object obj = ResourceManager.GetObject("lifebond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lunar_Fortune {
            get {
                object obj = ResourceManager.GetObject("Lunar_Fortune", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pahnai_Salad {
            get {
                object obj = ResourceManager.GetObject("Pahnai_Salad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plane {
            get {
                object obj = ResourceManager.GetObject("plane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap protbond {
            get {
                object obj = ResourceManager.GetObject("protbond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_Rock_Candy {
            get {
                object obj = ResourceManager.GetObject("Red_Rock_Candy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scroll_of_Resurrection {
            get {
                object obj = ResourceManager.GetObject("Scroll_of_Resurrection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Slice_of_Pumpkin_Pie {
            get {
                object obj = ResourceManager.GetObject("Slice_of_Pumpkin_Pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sugary_Blue_Drink {
            get {
                object obj = ResourceManager.GetObject("Sugary_Blue_Drink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tick_v0 {
            get {
                object obj = ResourceManager.GetObject("Tick_v0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tick_v1 {
            get {
                object obj = ResourceManager.GetObject("Tick_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tick_v2 {
            get {
                object obj = ResourceManager.GetObject("Tick_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap War_Supplies {
            get {
                object obj = ResourceManager.GetObject("War_Supplies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
