#include "stdafx.h"

#include <GWCA/Constants/Constants.h>
#include <GWCA/GameContainers/GamePos.h>
#include <GWCA/GameEntities/Agent.h>
#include <GWCA/GameEntities/Camera.h>
#include <GWCA/GameEntities/Item.h>
#include <GWCA/Managers/AgentMgr.h>
#include <GWCA/Managers/CameraMgr.h>
#include <GWCA/Managers/ItemMgr.h>
#include <GWCA/Managers/MapMgr.h>

#include <Color.h>
#include <ImGuiAddons.h>
#include <Modules/GwDatModule.h>
#include <Modules/LootBeaconsModule.h>
#include <Modules/PriceCheckerModule.h>
#include <Utils/GameWorldCompositor.h>
#include <Utils/SettingsRegistry.h>
#include <Utils/TerrainDrape.h>
#include <Utils/ToolboxUtils.h>
#include <Widgets/Minimap/GameWorldRenderer.h>

// Generated by CMake (fxc) from the .hlsl in the shared shaders dir.
#include "Widgets/Minimap/Shaders/loot_beacon_ring_ps.h"
#include "Widgets/Minimap/Shaders/loot_beacon_ring_vs.h"

namespace {
    constexpr int kMaxBuildsPerFrame = 8;   // caps QueryAltitude calls (1 per beacon build) spent per frame
    constexpr uint32_t kScanIntervalMs = 250; // item agents don't move; classification only needs a coarse tick
    constexpr uint32_t kRingTextureFileId = 0x03F2F1BB; // GW dat texture for the pulsing ring sprite

    // Not user-configurable - how far apart the two rings pulse (their "animation distance").
    constexpr float kRingSpacing = 4.f; // gwinches, how far the two rings start from the true diameter

    // Occlusion behind terrain is shared with the "In-game rendering" module
    // via GameWorldRenderer::GetOccludeBehindTerrain() so it's set in one place.
    float render_max_distance = 20000.f;
    float fog_factor = 0.5f;
    float beam_height = 225.f;
    float beam_width = 35.f;
    float beam_opacity = 0.5f;
    float ring_diameter = 90.f; // the true diameter the two rings pulse toward/away from
    float z_lift = 5.f;         // raise above the floor to avoid z-fighting (GW up is -z)
    float pulse_interval = 1.f; // seconds for the two rings to go from spread apart to meeting in the middle
    bool show_reserved_for_others = false;

    bool enable_value_beacons = true;
    int value_threshold = 1000; // gold, against the Kamadan trader price
    Color value_color = Colors::ARGB(255, 255, 140, 0);

    struct RarityBeacon {
        const char* label;
        bool enabled;
        Color color;
    };
    RarityBeacon rarity_white = {"White items", false, Colors::ARGB(255, 255, 255, 255)};
    RarityBeacon rarity_blue = {"Blue items", false, Colors::ARGB(255, 80, 160, 255)};
    RarityBeacon rarity_purple = {"Purple items", true, Colors::ARGB(255, 180, 80, 250)};
    RarityBeacon rarity_gold = {"Gold items", true, Colors::ARGB(255, 255, 210, 60)};
    RarityBeacon rarity_green = {"Green items", true, Colors::ARGB(255, 40, 220, 40)};

    struct BeaconVertex {
        float x, y, z;
        DWORD color;
    };

    // POSITION (world) + D3DCOLOR tint + UV, for the textured ring quads (0x03F2F1BB).
    struct RingVertex {
        float x, y, z;
        DWORD color;
        float u, v;
    };

    struct Beacon {
        GW::Vec2f pos;
        uint32_t zplane = 0;
        Color color = 0;
        bool draw = false;
        bool dimmed = false;
        bool built = false;   // true once ground_z has been resolved via a terrain query
        uint32_t seen = 0;
        float ground_z = 0.f; // draped terrain height (post z_lift); resolved once and cached, everything
                               // drawn from it (beam quad, ring quads) is rebuilt fresh every frame instead
    };

    std::unordered_map<uint32_t, Beacon> beacons;
    std::vector<BeaconVertex> scratch;
    std::vector<RingVertex> ring_scratch;
    uint32_t scan_counter = 0;
    uint64_t last_scan_tick = 0;
    bool beacons_dirty = false;
    int compositor_token = 0;

    IDirect3DVertexShader9* ring_vs = nullptr;
    IDirect3DPixelShader9* ring_ps = nullptr;
    IDirect3DVertexDeclaration9* ring_decl = nullptr;
    IDirect3DTexture9** ring_tex_pp = nullptr;
    bool ring_texture_requested = false;

    DWORD WithAlpha(const Color color, const float alpha_factor)
    {
        const auto base_a = static_cast<float>((color >> IM_COL32_A_SHIFT) & 0xFF);
        const auto a = static_cast<DWORD>(std::clamp(base_a * alpha_factor, 0.f, 255.f));
        return (color & ~(0xFFu << IM_COL32_A_SHIFT)) | (a << IM_COL32_A_SHIFT);
    }

    bool EnsureRingShaders(IDirect3DDevice9* device)
    {
        if (ring_vs && ring_ps && ring_decl) return true;
        constexpr D3DVERTEXELEMENT9 decl[] = {
            {0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
            {0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
            {0, 16, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
            D3DDECL_END()
        };
        if (!ring_decl && device->CreateVertexDeclaration(decl, &ring_decl) != D3D_OK) return false;
        if (!ring_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&loot_beacon_ring_vs), &ring_vs) != D3D_OK) return false;
        if (!ring_ps && device->CreatePixelShader(reinterpret_cast<const DWORD*>(&loot_beacon_ring_ps), &ring_ps) != D3D_OK) return false;
        return true;
    }

    // Appends a flat, ground-aligned textured quad (2 triangles) centred on `pos`, sized to the ring's
    // current diameter (2*radius) so the ring texture fills it exactly.
    void EmitRingQuad(std::vector<RingVertex>& out, const GW::Vec2f& pos, const float z, const float radius, const DWORD col)
    {
        const float r = std::max(1.f, radius);
        const RingVertex v00{pos.x - r, pos.y - r, z, col, 0.f, 1.f};
        const RingVertex v10{pos.x + r, pos.y - r, z, col, 1.f, 1.f};
        const RingVertex v11{pos.x + r, pos.y + r, z, col, 1.f, 0.f};
        const RingVertex v01{pos.x - r, pos.y + r, z, col, 0.f, 0.f};
        out.push_back(v00);
        out.push_back(v10);
        out.push_back(v11);
        out.push_back(v00);
        out.push_back(v11);
        out.push_back(v01);
    }

    void Classify(const GW::AgentItem& agent_item, const GW::Item& item, const uint32_t my_agent_id, Beacon& beacon)
    {
        const bool mine = !agent_item.owner || agent_item.owner == my_agent_id;
        beacon.dimmed = !mine;
        Color color = 0;
        bool draw = false;
        if (mine || show_reserved_for_others) {
            if (enable_value_beacons && value_threshold > 0 && PriceCheckerModule::GetPriceByItem(&item) >= static_cast<uint32_t>(value_threshold)) {
                color = value_color;
                draw = true;
            }
            else {
                const RarityBeacon* by_rarity = nullptr;
                switch (GW::Items::GetRarity(&item)) {
                    case GW::Constants::Rarity::White: by_rarity = &rarity_white; break;
                    case GW::Constants::Rarity::Blue: by_rarity = &rarity_blue; break;
                    case GW::Constants::Rarity::Purple: by_rarity = &rarity_purple; break;
                    case GW::Constants::Rarity::Gold: by_rarity = &rarity_gold; break;
                    case GW::Constants::Rarity::Green: by_rarity = &rarity_green; break;
                    default: break;
                }
                if (by_rarity && by_rarity->enabled) {
                    color = by_rarity->color;
                    draw = true;
                }
            }
        }
        if (draw && color != beacon.color) beacon.built = false;
        beacon.color = color;
        beacon.draw = draw;
    }

    void ScanItems()
    {
        ++scan_counter;
        const auto* agents = GW::Agents::GetAgentArray();
        if (!agents) {
            beacons.clear();
            return;
        }
        const auto my_agent_id = GW::Agents::GetControlledCharacterId();
        for (const auto* agent : *agents) {
            const auto* agent_item = agent ? agent->GetAsAgentItem() : nullptr;
            if (!agent_item) continue;
            const auto* item = GW::Items::GetItemById(agent_item->item_id);
            if (!item) continue;
            auto& beacon = beacons[agent_item->agent_id];
            beacon.seen = scan_counter;
            beacon.pos = {agent_item->pos.x, agent_item->pos.y};
            beacon.zplane = agent_item->pos.zplane;
            Classify(*agent_item, *item, my_agent_id, beacon);
        }
        std::erase_if(beacons, [](const auto& entry) { return entry.second.seen != scan_counter; });
    }

    bool BuildBeacon(Beacon& beacon, const uint32_t n_planes)
    {
        const float base_z = TerrainDrape::SurfaceZ(beacon.pos.x, beacon.pos.y, beacon.zplane, n_planes);
        if (base_z == 0.f) return false; // no altitude data yet; retry next frame
        beacon.ground_z = base_z - z_lift; // everything (beam quad, ring quads) is built fresh from this every frame
        beacon.built = true;
        return true;
    }

    constexpr float kBeamSolidFraction = 0.25f; // bottom fraction of beam_height that stays fully solid before fading

    // Appends a single quad standing on the ground and facing the camera - `right_x`/`right_y` is the
    // horizontal axis (from GetCameraRight below) so the quad rotates to face the viewer without ever
    // being edge-on, unlike two fixed crossed quads. Subdivided into a 3x3 vertex grid (4 quads) so the
    // beam holds solid near the item before fading upward, and tapers to transparent at its left/right
    // edges too, instead of a single hard-edged rectangle with a flat top-to-bottom gradient.
    void EmitBeamQuad(std::vector<BeaconVertex>& out, const GW::Vec2f& pos, const float ground_z, const float right_x, const float right_y, const Color base_color, const float base_alpha)
    {
        const float half = std::max(1.f, beam_width) * 0.5f;
        const float height = std::max(1.f, beam_height);
        const float z_solid = ground_z - height * kBeamSolidFraction;
        const float z_top = ground_z - height;

        const DWORD col_full = WithAlpha(base_color, base_alpha);
        const DWORD col_zero = WithAlpha(base_color, 0.f);

        struct GridVert {
            float x, y, z;
            DWORD color;
        };
        const auto at = [&](const float t, const float z, const DWORD color) {
            return GridVert{pos.x + right_x * half * t, pos.y + right_y * half * t, z, color};
        };
        // Columns: left edge (t=-1), centre (t=0), right edge (t=1) - only the centre carries alpha, so
        // every row tapers to transparent at both edges.
        const GridVert row_base[3] = {at(-1.f, ground_z, col_zero), at(0.f, ground_z, col_full), at(1.f, ground_z, col_zero)};
        const GridVert row_solid[3] = {at(-1.f, z_solid, col_zero), at(0.f, z_solid, col_full), at(1.f, z_solid, col_zero)};
        const GridVert row_top[3] = {at(-1.f, z_top, col_zero), at(0.f, z_top, col_zero), at(1.f, z_top, col_zero)};

        const auto quad = [&](const GridVert& a0, const GridVert& a1, const GridVert& b0, const GridVert& b1) {
            const BeaconVertex v00{a0.x, a0.y, a0.z, a0.color}, v10{a1.x, a1.y, a1.z, a1.color};
            const BeaconVertex v01{b0.x, b0.y, b0.z, b0.color}, v11{b1.x, b1.y, b1.z, b1.color};
            out.push_back(v00);
            out.push_back(v10);
            out.push_back(v11);
            out.push_back(v00);
            out.push_back(v11);
            out.push_back(v01);
        };
        // row_base -> row_solid is identical alpha at both ends (holds solid); row_solid -> row_top fades to zero.
        quad(row_base[0], row_base[1], row_solid[0], row_solid[1]);
        quad(row_base[1], row_base[2], row_solid[1], row_solid[2]);
        quad(row_solid[0], row_solid[1], row_top[0], row_top[1]);
        quad(row_solid[1], row_solid[2], row_top[1], row_top[2]);
    }

    // Horizontal axis perpendicular to the camera's view direction, for a vertical (upright) billboard -
    // world_up is (0,0,-1) since GW's up is -z, so right = cross(world_up, fwd) reduces to (fwd.y, -fwd.x).
    void GetCameraRight(float& right_x, float& right_y)
    {
        right_x = 1.f;
        right_y = 0.f;
        const auto* cam = GW::CameraMgr::GetCamera();
        if (!cam) return;
        const float fx = cam->look_at_target.x - cam->position.x;
        const float fy = cam->look_at_target.y - cam->position.y;
        const float len = std::sqrt(fx * fx + fy * fy);
        if (len < 0.0001f) return;
        right_x = fy / len;
        right_y = -fx / len;
    }
} // namespace

void LootBeaconsModule::DrawInWorld(IDirect3DDevice9* device)
{
    if (GW::Map::GetInstanceType() != GW::Constants::InstanceType::Explorable) {
        beacons.clear();
        return;
    }
    if (beacons_dirty) {
        for (auto& [id, beacon] : beacons) beacon.built = false;
        beacons_dirty = false;
    }

    const auto now = GetTickCount64();
    if (now - last_scan_tick >= kScanIntervalMs) {
        last_scan_tick = now;
        ScanItems();
    }
    if (beacons.empty()) return;

    if (!ring_texture_requested) {
        ring_tex_pp = GwDatModule::LoadTextureFromFileId(kRingTextureFileId);
        ring_texture_requested = true;
    }

    const auto n_planes = TerrainDrape::PathingPlaneCount();
    const float t_seconds = static_cast<float>(now % 3600000) / 1000.f;

    // One shared timer for every beacon - "the set pulse interval" is a single global setting, not
    // per-beacon - so the beam's brightness and the rings' radii are each a single value per frame,
    // not per-vertex data. cycle hits pi/2 exactly when t_seconds == pulse_interval, i.e. exactly when
    // the two rings first meet at the midpoint (cos=0) - which is also when the beam is brightest (sin=1).
    float env = 1.f;
    float osc01 = 0.5f;
    if (pulse_interval > 0.f) {
        const float cycle = t_seconds * (DirectX::XM_PIDIV2 / pulse_interval);
        env = 0.75f + 0.25f * std::sin(cycle);
        osc01 = 0.5f - 0.5f * std::cos(cycle);
    }
    const float true_radius = std::max(1.f, ring_diameter * 0.5f);
    const float r_min = std::max(1.f, true_radius - kRingSpacing);
    const float r_max = true_radius + kRingSpacing;
    const float r_outer = std::lerp(r_max, r_min, osc01);
    const float r_inner = std::lerp(r_min, r_max, osc01);

    float right_x, right_y;
    GetCameraRight(right_x, right_y);

    scratch.clear();
    ring_scratch.clear();
    int builds = 0;
    for (auto& [id, beacon] : beacons) {
        if (!beacon.draw) continue;
        if (!beacon.built) {
            if (!n_planes || builds >= kMaxBuildsPerFrame) continue;
            ++builds;
            if (!BuildBeacon(beacon, n_planes)) continue;
        }
        const float beam_env = beacon.dimmed ? env * 0.4f : env;
        EmitBeamQuad(scratch, beacon.pos, beacon.ground_z, right_x, right_y, beacon.color, beam_opacity * beam_env);

        // Ring opacity comes straight from the beacon colour's own alpha channel; dimmed (reserved for
        // other party members) is the one exception, same as the beam.
        const DWORD ring_col = beacon.dimmed ? WithAlpha(beacon.color, 0.4f) : beacon.color;
        EmitRingQuad(ring_scratch, beacon.pos, beacon.ground_z, r_outer, ring_col);
        EmitRingQuad(ring_scratch, beacon.pos, beacon.ground_z, r_inner, ring_col);
    }

    if (!scratch.empty()) {
        IDirect3DStateBlock9* state_block = nullptr;
        if (device->CreateStateBlock(D3DSBT_ALL, &state_block) == D3D_OK) {
            if (GameWorldCompositor::SetupPipeline(device, GameWorldRenderer::GetOccludeBehindTerrain(), render_max_distance, fog_factor)) {
                constexpr BOOL dotted_off[1] = {FALSE};
                device->SetPixelShaderConstantB(0, dotted_off, 1);
                device->DrawPrimitiveUP(D3DPT_TRIANGLELIST, static_cast<UINT>(scratch.size() / 3), scratch.data(), sizeof(BeaconVertex));
            }
            state_block->Apply();
            state_block->Release();
        }
    }

    IDirect3DTexture9* ring_tex = ring_tex_pp ? *ring_tex_pp : nullptr;
    if (!ring_scratch.empty() && ring_tex && EnsureRingShaders(device)) {
        IDirect3DStateBlock9* state_block = nullptr;
        if (device->CreateStateBlock(D3DSBT_ALL, &state_block) == D3D_OK) {
            if (device->SetVertexShader(ring_vs) == D3D_OK && device->SetPixelShader(ring_ps) == D3D_OK && device->SetVertexDeclaration(ring_decl) == D3D_OK &&
                GameWorldCompositor::SetWorldViewProj(device)) {
                GameWorldCompositor::SetWorldRenderStates(device, GameWorldRenderer::GetOccludeBehindTerrain());
                GameWorldCompositor::SetDistanceFog(device, render_max_distance, fog_factor);
                device->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_LINEAR);
                device->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_LINEAR);
                device->SetSamplerState(0, D3DSAMP_ADDRESSU, D3DTADDRESS_CLAMP);
                device->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP);
                device->SetTexture(0, ring_tex);
                device->DrawPrimitiveUP(D3DPT_TRIANGLELIST, static_cast<UINT>(ring_scratch.size() / 3), ring_scratch.data(), sizeof(RingVertex));
            }
            state_block->Apply();
            state_block->Release();
        }
    }
}

void LootBeaconsModule::RegisterSettings(ToolboxModule* module)
{
    SettingsRegistry::RegisterField(module, "render_max_distance", &render_max_distance);
    SettingsRegistry::RegisterField(module, "fog_factor", &fog_factor);
    SettingsRegistry::RegisterField(module, "beam_height", &beam_height);
    SettingsRegistry::RegisterField(module, "beam_width", &beam_width);
    SettingsRegistry::RegisterField(module, "beam_opacity", &beam_opacity);
    SettingsRegistry::RegisterField(module, "ring_diameter", &ring_diameter);
    SettingsRegistry::RegisterField(module, "z_lift", &z_lift);
    SettingsRegistry::RegisterField(module, "pulse_interval", &pulse_interval);
    SettingsRegistry::RegisterField(module, "show_reserved_for_others", &show_reserved_for_others);
    SettingsRegistry::RegisterField(module, "enable_value_beacons", &enable_value_beacons);
    SettingsRegistry::RegisterField(module, "value_threshold", &value_threshold);
    SettingsRegistry::RegisterField(module, "value_color", &value_color);
    SettingsRegistry::RegisterField(module, "white_enabled", &rarity_white.enabled);
    SettingsRegistry::RegisterField(module, "white_color", &rarity_white.color);
    SettingsRegistry::RegisterField(module, "blue_enabled", &rarity_blue.enabled);
    SettingsRegistry::RegisterField(module, "blue_color", &rarity_blue.color);
    SettingsRegistry::RegisterField(module, "purple_enabled", &rarity_purple.enabled);
    SettingsRegistry::RegisterField(module, "purple_color", &rarity_purple.color);
    SettingsRegistry::RegisterField(module, "gold_enabled", &rarity_gold.enabled);
    SettingsRegistry::RegisterField(module, "gold_color", &rarity_gold.color);
    SettingsRegistry::RegisterField(module, "green_enabled", &rarity_green.enabled);
    SettingsRegistry::RegisterField(module, "green_color", &rarity_green.color);
}

void LootBeaconsModule::Initialize()
{
    ToolboxModule::Initialize();
    RegisterSettings(this);
    if (!compositor_token) compositor_token = GameWorldCompositor::RegisterDraw(&LootBeaconsModule::DrawInWorld);
}

void LootBeaconsModule::SignalTerminate()
{
    if (compositor_token) {
        GameWorldCompositor::UnregisterDraw(compositor_token);
        compositor_token = 0;
    }
    beacons.clear();
}

void LootBeaconsModule::LoadSettings(SettingsDoc& doc, ToolboxIni* legacy)
{
    ToolboxModule::LoadSettings(doc, legacy);
    beacons_dirty = true;
}

void LootBeaconsModule::DrawSettingsInternal()
{
    const auto red = ImGui::ColorConvertU32ToFloat4(Colors::Red());
    if (!GameWorldCompositor::IsActive())
        ImGui::TextColored(red, GameWorldCompositor::HasFailed() ? "In-world compositor FAILED to install." : "In-world compositor: not installed yet.");

    ImGui::Checkbox("Beacon on valuable items", &enable_value_beacons);
    ImGui::ShowHelp("Any drop whose Kamadan trader price meets the threshold gets a beacon,\nregardless of rarity - catches ectos, gemstones, dyes and other white-rarity valuables.");
    if (enable_value_beacons) {
        Colors::DrawSettingHueWheel("##value_color", &value_color);
        ImGui::DragInt("Value threshold (gold)", &value_threshold, 50.f, 0, 1000000);
    }
    ImGui::Separator();
    ImGui::TextUnformatted("Beacon by rarity");
    for (auto* rarity : {&rarity_gold, &rarity_green, &rarity_purple, &rarity_blue, &rarity_white}) {
        ImGui::PushID(rarity->label);
        if (ImGui::Checkbox(rarity->label, &rarity->enabled)) beacons_dirty = true;
        ImGui::SameLine(180.f);
        Colors::DrawSettingHueWheel("##color", &rarity->color);
        ImGui::PopID();
    }
    if (ImGui::Checkbox("Show beacons on items reserved for other party members", &show_reserved_for_others)) beacons_dirty = true;
    ImGui::ShowHelp("Drawn dimmed. Off: only unreserved drops and drops assigned to you.");

    ImGui::Separator();
    ImGui::TextDisabled("Occlusion behind terrain follows the \"In-game rendering\" module's setting.");
    ImGui::DragFloat("Maximum render distance", &render_max_distance, 25.f, 10.f, 100000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Beam height", &beam_height, 5.f, 50.f, 5000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Beam width", &beam_width, 1.f, 5.f, 500.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Beam opacity", &beam_opacity, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Ring diameter", &ring_diameter, 1.f, 5.f, 1000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("The two rings pulse 4 gwinches in and out of this diameter, crossing over it. Opacity comes "
                     "from the beacon colour's own alpha - no separate ring opacity setting.");
    if (ImGui::DragFloat("Height lift", &z_lift, 0.5f, 0.f, 200.f, "%.1f", ImGuiSliderFlags_AlwaysClamp)) beacons_dirty = true;
    ImGui::DragFloat("Pulse interval", &pulse_interval, 0.05f, 0.f, 10.f, "%.2f s", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("Seconds for the two rings to go from spread apart to meeting in the middle. 0 = no pulsing; "
                     "rings hold at their midpoint and the beam pulse pauses too.");
}
