#include "stdafx.h"

#include <GWCA/GameContainers/GamePos.h>
#include <GWCA/GameEntities/Agent.h>
#include <GWCA/GameEntities/Pathing.h>
#include <GWCA/Managers/AgentMgr.h>
#include <GWCA/Managers/MapMgr.h>

#include <Color.h>
#include <ImGuiAddons.h>
#include <Logger.h>
#include <Modules/GwDatModule.h>
#include <Modules/RiverModule.h>
#include <Utils/GameWorldCompositor.h>
#include <Utils/SettingsDoc.h>
#include <Utils/SettingsRegistry.h>

// Generated by CMake (fxc) from the .hlsl in the shared shaders dir.
#include "Widgets/Minimap/Shaders/river_ps.h"
#include "Widgets/Minimap/Shaders/river_vs.h"

// External linkage (not the anonymous namespace) so glaze can reflect these as elements when
// (de)serialising the per-map river list. Plain aggregates so reflection works without a glz::meta.
namespace lava_river_module {
    struct RiverPoint {
        float x = 0.f;
        float y = 0.f;
    };
    struct LavaRiver {
        std::vector<RiverPoint> points;
        float width = 200.f;
    };
} // namespace lava_river_module

namespace {
    using namespace lava_river_module;

    constexpr float kZNear = 47.0f, kZFar = 100000.f; // must match GW's projection for occlusion to line up
    constexpr float kSampleSpacing = 50.f;            // resample a river centerline every ~50 gu (follow slopes)
    constexpr float kAltUnknown = 1e30f;              // sentinel: no terrain data at this (x,y)
    constexpr size_t kMaxVertices = 1500000;          // safety cap on total surface geometry per map (raise cell_size if hit)

    // Settings (persisted scalars via SettingsRegistry; rivers persisted separately as JSON).
    bool occlude_behind_terrain = true;
    float render_max_distance = 5000.f;
    float fog_factor = 1.0f;     // distance-fade strength fed to the shader
    float glow = 0.4f;           // emissive brightness boost (0 = plain texture)
    float flow_speed = 0.15f;    // texture tiles/second scrolled (in the wandering flow direction)
    float flow_dir_change = 0.06f; // radians/second the flow heading drifts
    float tile_length = 256.f;   // world units per texture repeat (ground UV tiling / river length)
    float z_lift = 5.f;          // raise the surface above the floor to avoid z-fighting (GW up is -z)
    // Selected GW .dat texture ids. When >1 is selected they're spread across the floor in patches for variety;
    // empty = nothing drawn. Persisted via SettingsDoc (a vector isn't a scalar SettingsRegistry field).
    std::vector<uint32_t> textures = {0x45478};
    unsigned int lava_tint = 0xFFFFFFFFu; // ImGui-packed; white shows the texture untinted
    float new_river_width = 200.f;        // default width for newly created rivers

    bool cover_entire_ground = true; // true = flood the whole walkable floor; false = only authored rivers
    float wave_amplitude = 40.f;     // peak wave height in world units (modulated by a slow envelope)
    float wave_scale = 1.0f;         // wavelength multiplier (higher = shorter, choppier waves)
    float cell_size = 100.f;         // ground tessellation cell (world units); smaller = finer waves, more verts

    // Per-map authored rivers, keyed by MapID. Persisted to LavaRivers.json via SettingsDoc.
    std::map<uint32_t, std::vector<LavaRiver>> rivers_by_map;

    // POSITION (world, draped on floor) + D3DCOLOR tint + UV (u across width, v along length).
    struct LavaVertex {
        float x, y, z;
        DWORD color;
        float u, v;
    };

    // Named textures offered in the settings multi-select (the in-game lava textures + the water sheet).
    struct KnownTex {
        uint32_t id;
        const char* name;
    };
    constexpr KnownTex kKnownTextures[] = {
        {0x45478, "Lava 1"}, {0x457eb, "Lava 2"}, {0x23e8, "Lava 3"},
        {0x1680b, "Lava 4"}, {0x1680c, "Lava 5"}, {0x20de, "Lava 6"},
        {0x1baa1, "Water"},
    };

    // Which selected texture a floor patch around (cx,cy) uses — a coarse spatial hash so the same texture
    // clusters into ~1024-unit patches instead of speckling per-trapezoid.
    int TexBucket(const float cx, const float cy, const int num)
    {
        if (num <= 1) return 0;
        const int qx = static_cast<int>(std::floor(cx / 1024.f));
        const int qy = static_cast<int>(std::floor(cy / 1024.f));
        uint32_t h = static_cast<uint32_t>(qx * 73856093) ^ static_cast<uint32_t>(qy * 19349663);
        h ^= h >> 13;
        h *= 0x85ebca6bu;
        h ^= h >> 16;
        return static_cast<int>(h % static_cast<uint32_t>(num));
    }

    std::vector<LavaVertex> mesh_vertices;
    struct TexRange {
        uint32_t file_id;
        size_t offset; // first vertex
        size_t count;  // vertex count (multiple of 3)
    };
    std::vector<TexRange> tex_ranges; // one contiguous run of mesh_vertices per selected texture
    IDirect3DVertexBuffer9* mesh_vb = nullptr;
    size_t mesh_cap = 0; // in vertices
    bool mesh_ready = false;
    bool mesh_dirty = true;
    uint32_t built_map_id = 0xFFFFFFFFu;

    // Incremental ground-mesh build. Tessellating every trapezoid (one QueryAltitude per grid vertex) across a
    // large explorable is far too heavy for one frame, and QueryAltitude isn't thread-safe (it swaps the global
    // map context), so the work can't move to a worker. Instead we spread it across frames on the render thread
    // under a per-frame query budget: the floor fills in over a handful of frames and the load never stalls.
    constexpr int kQueriesPerFrame = 2000; // max QueryAltitude calls per frame while a build is in progress
    struct GroundGridVert {
        float x, y, z;
    };
    std::vector<GroundGridVert> ground_grid_scratch; // reused per trapezoid to avoid re-allocating each one
    struct GroundBuild {
        bool active = false;
        uint32_t map_id = 0;
        uint32_t n_planes = 0;
        int num = 0;        // texture/bucket count captured at build start
        uint32_t plane = 0; // cursor: plane being tessellated
        uint32_t trap = 0;  // cursor: next trapezoid within the plane
        size_t total = 0;   // emitted vertices so far (for the kMaxVertices cap)
        std::vector<std::vector<LavaVertex>> buckets;
    };
    GroundBuild gbuild;

    IDirect3DVertexShader9* lava_vs = nullptr;
    IDirect3DPixelShader9* lava_ps = nullptr;
    IDirect3DVertexDeclaration9* lava_decl = nullptr;

    float t_seconds = 0.f;             // accumulated time fed to the wave shader
    float scroll_u = 0.f, scroll_v = 0.f; // accumulated texture scroll (wandering flow)
    float flow_angle = 0.f;            // current flow heading (radians)
    DWORD last_tick = 0;
    int compositor_token = 0;

    // Authoring state (not persisted): which river of the current map "Add point" appends to.
    int active_river = -1;

    float QueryAltAt(const float x, const float y, const uint32_t zplane)
    {
        GW::GamePos p{x, y, zplane};
        return GW::Map::QueryAltitude(&p);
    }

    // Highest terrain surface at (x,y) over all planes (GW up is -z, so highest = min altitude), or sentinel.
    float HighestSurfaceZ(const float x, const float y, const uint32_t n_planes)
    {
        float best = kAltUnknown;
        for (uint32_t zp = 0; zp < n_planes; ++zp) {
            const float a = QueryAltAt(x, y, zp);
            if (a != 0.f && (best == kAltUnknown || a < best)) best = a;
        }
        return best;
    }

    // Surface altitude at (x,y) closest to `prev` (so a draped ribbon follows the walked surface across
    // ramps/bridges instead of snapping to the ground beneath), or sentinel if no plane has data.
    float ClosestSurfaceZ(const float x, const float y, const uint32_t n_planes, const float prev)
    {
        float best = kAltUnknown, best_d = kAltUnknown;
        for (uint32_t zp = 0; zp < n_planes; ++zp) {
            const float a = QueryAltAt(x, y, zp);
            if (a == 0.f) continue;
            const float d = std::fabs(a - prev);
            if (best == kAltUnknown || d < best_d) {
                best_d = d;
                best = a;
            }
        }
        return best;
    }

    // Build a draped, textured ribbon for one river and append it to the given vertex bucket.
    void BuildRiverMesh(const LavaRiver& river, const uint32_t n_planes, std::vector<LavaVertex>& out)
    {
        if (river.points.size() < 2) return;

        // 1. Resample the centerline so each segment follows slopes/stairs between authored points.
        std::vector<RiverPoint> dense;
        for (size_t i = 0; i < river.points.size(); ++i) {
            if (!dense.empty()) {
                const float dx = river.points[i].x - river.points[i - 1].x;
                const float dy = river.points[i].y - river.points[i - 1].y;
                const int steps = std::max(1, static_cast<int>(std::sqrt(dx * dx + dy * dy) / kSampleSpacing));
                for (int j = 1; j < steps; ++j) {
                    const float t = static_cast<float>(j) / static_cast<float>(steps);
                    dense.push_back({river.points[i - 1].x + dx * t, river.points[i - 1].y + dy * t});
                }
            }
            dense.push_back(river.points[i]);
        }
        if (dense.size() < 2) return;

        const float half = std::max(1.f, river.width) * 0.5f;
        const float tile = std::max(1.f, tile_length);
        const DWORD col = lava_tint;

        struct Cross {
            float lx, ly, lz, rx, ry, rz, v;
        };
        std::vector<Cross> xs;
        xs.reserve(dense.size());

        float arc = 0.f;
        float prevz = HighestSurfaceZ(dense[0].x, dense[0].y, n_planes);
        if (prevz == kAltUnknown) prevz = 0.f;

        for (size_t i = 0; i < dense.size(); ++i) {
            const RiverPoint& a = dense[i > 0 ? i - 1 : i];
            const RiverPoint& b = dense[i + 1 < dense.size() ? i + 1 : i];
            float tx = b.x - a.x, ty = b.y - a.y;
            const float tl = std::sqrt(tx * tx + ty * ty);
            if (tl > 1e-4f) {
                tx /= tl;
                ty /= tl;
            }
            else {
                tx = 1.f;
                ty = 0.f;
            }
            const float px = -ty, py = tx; // perpendicular in XY

            if (i > 0) {
                const float dx = dense[i].x - dense[i - 1].x, dy = dense[i].y - dense[i - 1].y;
                arc += std::sqrt(dx * dx + dy * dy);
            }
            const float lx = dense[i].x + px * half, ly = dense[i].y + py * half;
            const float rx = dense[i].x - px * half, ry = dense[i].y - py * half;

            float lz = ClosestSurfaceZ(lx, ly, n_planes, prevz);
            if (lz == kAltUnknown) lz = prevz;
            float rz = ClosestSurfaceZ(rx, ry, n_planes, prevz);
            if (rz == kAltUnknown) rz = prevz;
            const float cz = ClosestSurfaceZ(dense[i].x, dense[i].y, n_planes, prevz);
            if (cz != kAltUnknown) prevz = cz;

            xs.push_back({lx, ly, lz - z_lift, rx, ry, rz - z_lift, arc / tile});
        }

        for (size_t i = 0; i + 1 < xs.size(); ++i) {
            if (out.size() + 6 > kMaxVertices) return;
            const Cross& c0 = xs[i];
            const Cross& c1 = xs[i + 1];
            out.push_back({c0.lx, c0.ly, c0.lz, col, 0.f, c0.v});
            out.push_back({c0.rx, c0.ry, c0.rz, col, 1.f, c0.v});
            out.push_back({c1.rx, c1.ry, c1.rz, col, 1.f, c1.v});
            out.push_back({c0.lx, c0.ly, c0.lz, col, 0.f, c0.v});
            out.push_back({c1.rx, c1.ry, c1.rz, col, 1.f, c1.v});
            out.push_back({c1.lx, c1.ly, c1.lz, col, 0.f, c1.v});
        }
    }

    // Tessellate one pathing trapezoid into its texture bucket: grid it (fine enough for the wave displacement to
    // read), drape each sub-vertex onto the trapezoid's own plane via an altitude query, and tile the texture by
    // world position so it's seamless across trapezoids. Returns the number of QueryAltitude calls made, or -1 if
    // the per-map geometry cap was hit (the caller should stop the build).
    int EmitGroundTrapezoid(const GW::PathingTrapezoid& tz, const uint32_t p)
    {
        if (tz.YT == tz.YB) return 0; // degenerate connector

        const float cell = std::max(16.f, cell_size);
        const float tile = std::max(1.f, tile_length);
        const DWORD col = lava_tint;

        const float maxw = std::max(std::fabs(tz.XTR - tz.XTL), std::fabs(tz.XBR - tz.XBL));
        const int rows = std::clamp(static_cast<int>(std::fabs(tz.YT - tz.YB) / cell), 1, 64);
        const int cols = std::clamp(static_cast<int>(maxw / cell), 1, 64);
        if (gbuild.total + static_cast<size_t>(rows) * cols * 6 > kMaxVertices) return -1;

        const float cx = (tz.XTL + tz.XTR + tz.XBL + tz.XBR) * 0.25f;
        const float cy = (tz.YT + tz.YB) * 0.5f;
        std::vector<LavaVertex>& out = gbuild.buckets[TexBucket(cx, cy, gbuild.num)]; // which texture this patch uses

        int queries = 0;
        const float fallback = QueryAltAt(cx, cy, p); // centre altitude, for sub-verts with no data
        ++queries;

        std::vector<GroundGridVert>& grid = ground_grid_scratch;
        grid.assign(static_cast<size_t>(rows + 1) * (cols + 1), {});
        for (int j = 0; j <= rows; ++j) {
            const float v = static_cast<float>(j) / static_cast<float>(rows);
            const float y = tz.YB + (tz.YT - tz.YB) * v;
            const float xl = tz.XBL + (tz.XTL - tz.XBL) * v;
            const float xr = tz.XBR + (tz.XTR - tz.XBR) * v;
            for (int i = 0; i <= cols; ++i) {
                const float u = static_cast<float>(i) / static_cast<float>(cols);
                const float x = xl + (xr - xl) * u;
                float z = QueryAltAt(x, y, p);
                ++queries;
                if (z == 0.f) z = fallback;
                grid[static_cast<size_t>(j) * (cols + 1) + i] = {x, y, z};
            }
        }
        auto push = [&](const GroundGridVert& g) { out.push_back({g.x, g.y, g.z - z_lift, col, g.x / tile, g.y / tile}); };
        for (int j = 0; j < rows; ++j) {
            for (int i = 0; i < cols; ++i) {
                const GroundGridVert& a = grid[static_cast<size_t>(j) * (cols + 1) + i];
                const GroundGridVert& b = grid[static_cast<size_t>(j) * (cols + 1) + i + 1];
                const GroundGridVert& c = grid[static_cast<size_t>(j + 1) * (cols + 1) + i];
                const GroundGridVert& d = grid[static_cast<size_t>(j + 1) * (cols + 1) + i + 1];
                push(a);
                push(b);
                push(d);
                push(a);
                push(d);
                push(c);
                gbuild.total += 6;
            }
        }
        return queries;
    }

    // Assemble the finished per-texture buckets into the draw buffers and mark the map built.
    void FinalizeGroundBuild()
    {
        mesh_vertices.clear();
        tex_ranges.clear();
        const int n = std::min(gbuild.num, static_cast<int>(textures.size())); // textures may have changed mid-build
        for (int i = 0; i < n; ++i) {
            if (gbuild.buckets[i].empty()) continue;
            tex_ranges.push_back({textures[i], mesh_vertices.size(), gbuild.buckets[i].size()});
            mesh_vertices.insert(mesh_vertices.end(), gbuild.buckets[i].begin(), gbuild.buckets[i].end());
        }
        Log::Info("[lava] build map=%u ground=1 verts=%zu planes=%u textures=%d ranges=%zu",
            gbuild.map_id, mesh_vertices.size(), gbuild.n_planes, gbuild.num, tex_ranges.size());
        built_map_id = gbuild.map_id;
        gbuild = {}; // active=false, drop buckets
    }

    // Start (or restart) an incremental ground build for map_id. Clears the currently-drawn mesh so the previous
    // map's lava stops showing immediately; the new floor fills in over the next few frames via StepGroundBuild.
    void BeginGroundBuild(const uint32_t map_id)
    {
        const GW::PathingMapArray* pm = GW::Map::GetPathingMap();
        const uint32_t n_planes = pm ? static_cast<uint32_t>(pm->size()) : 0;
        const int num = static_cast<int>(textures.size());
        mesh_vertices.clear();
        tex_ranges.clear();
        built_map_id = 0xFFFFFFFFu;
        gbuild = {};
        if (!n_planes || num == 0) {
            mesh_dirty = true; // pathing map not loaded yet (still loading); retry next frame
            return;
        }
        gbuild.active = true;
        gbuild.map_id = map_id;
        gbuild.n_planes = n_planes;
        gbuild.num = num;
        gbuild.buckets.assign(num, {});
        mesh_dirty = false;
    }

    // Advance the in-progress ground build within this frame's query budget; never blocks the render thread.
    void StepGroundBuild()
    {
        if (!gbuild.active) return;
        const GW::PathingMapArray* pm = GW::Map::GetPathingMap();
        if (!pm || static_cast<uint32_t>(pm->size()) != gbuild.n_planes) {
            // Map geometry changed under us (zoning) — abandon; DrawInWorld's map-change check restarts the build.
            gbuild = {};
            built_map_id = 0xFFFFFFFFu;
            mesh_dirty = true;
            return;
        }
        int queries = 0;
        while (gbuild.plane < gbuild.n_planes) {
            const GW::PathingMap& map = (*pm)[gbuild.plane];
            while (gbuild.trap < map.trapezoid_count) {
                const int q = EmitGroundTrapezoid(map.trapezoids[gbuild.trap], gbuild.plane);
                ++gbuild.trap;
                if (q < 0) { // hit the geometry cap; finish with what we have
                    FinalizeGroundBuild();
                    return;
                }
                queries += q;
                if (queries >= kQueriesPerFrame) return; // budget spent; resume next frame
            }
            ++gbuild.plane;
            gbuild.trap = 0;
        }
        FinalizeGroundBuild(); // all planes tessellated
    }

    void BuildMesh(const uint32_t map_id)
    {
        mesh_vertices.clear();
        tex_ranges.clear();
        mesh_ready = false;
        built_map_id = map_id;
        mesh_dirty = false;

        const GW::PathingMapArray* pm = GW::Map::GetPathingMap();
        const uint32_t n_planes = pm ? static_cast<uint32_t>(pm->size()) : 0;
        if (!n_planes) {
            mesh_dirty = true; // pathing map not loaded yet; retry next frame
            return;
        }
        const int num = static_cast<int>(textures.size());
        if (num == 0) {
            Log::Info("[lava] build map=%u: no textures selected", map_id);
            return;
        }

        // One vertex bucket per selected texture; concatenated into mesh_vertices with a TexRange each.
        // The cover-entire-ground flood is built incrementally (see BeginGroundBuild); here we only lay down the
        // authored rivers, which are few enough to build in a single frame.
        std::vector<std::vector<LavaVertex>> buckets(num);
        size_t river_count = 0;
        if (const auto it = rivers_by_map.find(map_id); it != rivers_by_map.end()) {
            river_count = it->second.size();
            for (size_t r = 0; r < it->second.size(); ++r)
                BuildRiverMesh(it->second[r], n_planes, buckets[r % static_cast<size_t>(num)]);
        }
        for (int i = 0; i < num; ++i) {
            if (buckets[i].empty()) continue;
            tex_ranges.push_back({textures[i], mesh_vertices.size(), buckets[i].size()});
            mesh_vertices.insert(mesh_vertices.end(), buckets[i].begin(), buckets[i].end());
        }
        Log::Info("[lava] build map=%u rivers=%zu verts=%zu planes=%u textures=%d ranges=%zu",
            map_id, river_count, mesh_vertices.size(), n_planes, num, tex_ranges.size());
    }

    bool EnsureVb(IDirect3DDevice9* device)
    {
        const size_t needed = mesh_vertices.size();
        if (needed == 0) return false;
        if (!mesh_vb || mesh_cap < needed) {
            if (mesh_vb) {
                mesh_vb->Release();
                mesh_vb = nullptr;
            }
            const size_t c = needed + needed / 2; // headroom so small edits don't reallocate every frame
            if (device->CreateVertexBuffer(static_cast<UINT>(c * sizeof(LavaVertex)), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &mesh_vb, nullptr) != D3D_OK) {
                mesh_cap = 0;
                return false;
            }
            mesh_cap = c;
        }
        void* mem = nullptr;
        if (mesh_vb->Lock(0, static_cast<UINT>(needed * sizeof(LavaVertex)), &mem, 0) != D3D_OK || !mem) return false;
        memcpy(mem, mesh_vertices.data(), needed * sizeof(LavaVertex));
        mesh_vb->Unlock();
        return true;
    }

    bool EnsureShaders(IDirect3DDevice9* device)
    {
        if (lava_vs && lava_ps && lava_decl) return true;
        constexpr D3DVERTEXELEMENT9 decl[] = {
            {0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0}, {0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0}, {0, 16, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0}, D3DDECL_END()
        };
        if (!lava_decl && device->CreateVertexDeclaration(decl, &lava_decl) != D3D_OK) return false;
        if (!lava_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&river_vs), &lava_vs) != D3D_OK) return false;
        if (!lava_ps && device->CreatePixelShader(reinterpret_cast<const DWORD*>(&river_ps), &lava_ps) != D3D_OK) return false;
        return true;
    }
} // namespace

void RiverModule::DrawInWorld(IDirect3DDevice9* device)
{
    if (textures.empty()) return; // nothing selected -> nothing to draw

    const uint32_t cur_map = static_cast<uint32_t>(GW::Map::GetMapID());
    if (cover_entire_ground) {
        // Whole-floor flood is too heavy for one frame and QueryAltitude can't run off-thread — build it
        // incrementally across frames under a query budget so entering a map never stalls the render thread.
        if ((cur_map != built_map_id || mesh_dirty) && (!gbuild.active || gbuild.map_id != cur_map))
            BeginGroundBuild(cur_map);
        if (gbuild.active)
            StepGroundBuild();
    }
    else if (cur_map != built_map_id || mesh_dirty) {
        BuildMesh(cur_map); // authored rivers only: cheap enough to build in one frame
    }

    if (mesh_vertices.empty() || tex_ranges.empty()) return;
    mesh_ready = EnsureVb(device);
    if (!mesh_ready || !EnsureShaders(device)) return;

    const DWORD now = GetTickCount();
    float dt = last_tick ? static_cast<float>(now - last_tick) / 1000.f : 0.f;
    last_tick = now;
    dt = std::clamp(dt, 0.f, 0.1f); // ignore alt-tab / breakpoint gaps
    t_seconds += dt;

    // Flow heading wanders slowly; accumulate the texture scroll along it so the current changes direction.
    flow_angle += dt * flow_dir_change;
    const float heading = flow_angle + 0.6f * std::sin(t_seconds * 0.05f);
    scroll_u = std::fmod(scroll_u + std::cos(heading) * flow_speed * dt, 1.f);
    scroll_v = std::fmod(scroll_v + std::sin(heading) * flow_speed * dt, 1.f);
    // Slow, incommensurate envelope so the waves swell and calm without an obvious period.
    const float env = std::max(0.15f, 1.f + 0.5f * std::sin(t_seconds * 0.13f) + 0.3f * std::sin(t_seconds * 0.071f));

    IDirect3DStateBlock9* state_block = nullptr; // restored on exit so GW's own rendering isn't corrupted
    if (device->CreateStateBlock(D3DSBT_ALL, &state_block) != D3D_OK) return;
    if (device->SetVertexShader(lava_vs) == D3D_OK && device->SetPixelShader(lava_ps) == D3D_OK && device->SetVertexDeclaration(lava_decl) == D3D_OK && GameWorldCompositor::SetWorldViewProj(device, kZNear, kZFar)) {
        GameWorldCompositor::SetWorldRenderStates(device, occlude_behind_terrain);
        GameWorldCompositor::SetDistanceFog(device, render_max_distance, fog_factor);
        const float wave_const[4] = {t_seconds, wave_amplitude * env, wave_scale, 0.f};
        device->SetVertexShaderConstantF(8, wave_const, 1);
        const float lava_params[4] = {scroll_u, scroll_v, glow, 0.f};
        device->SetPixelShaderConstantF(3, lava_params, 1);
        device->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_ADDRESSU, D3DTADDRESS_WRAP); // tile the texture across the floor
        device->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_WRAP);
        if (device->SetStreamSource(0, mesh_vb, 0, sizeof(LavaVertex)) == D3D_OK) {
            // One draw per selected texture (each its own contiguous run of the shared vertex buffer).
            for (const auto& r : tex_ranges) {
                IDirect3DTexture9** pp = GwDatModule::LoadTextureFromFileId(r.file_id);
                IDirect3DTexture9* tex = pp ? *pp : nullptr;
                if (!tex || r.count < 3) continue;
                device->SetTexture(0, tex);
                device->DrawPrimitive(D3DPT_TRIANGLELIST, static_cast<UINT>(r.offset), static_cast<UINT>(r.count / 3));
            }
        }
    }
    state_block->Apply();
    state_block->Release();
}

void RiverModule::RegisterSettings(ToolboxModule* module)
{
    SettingsRegistry::RegisterField(module, "occlude_behind_terrain", &occlude_behind_terrain);
    SettingsRegistry::RegisterField(module, "render_max_distance", &render_max_distance);
    SettingsRegistry::RegisterField(module, "glow", &glow);
    SettingsRegistry::RegisterField(module, "flow_speed", &flow_speed);
    SettingsRegistry::RegisterField(module, "tile_length", &tile_length);
    SettingsRegistry::RegisterField(module, "z_lift", &z_lift);
    SettingsRegistry::RegisterField(module, "lava_tint", &lava_tint);
    SettingsRegistry::RegisterField(module, "new_river_width", &new_river_width);
    SettingsRegistry::RegisterField(module, "cover_entire_ground", &cover_entire_ground);
    SettingsRegistry::RegisterField(module, "wave_amplitude", &wave_amplitude);
    SettingsRegistry::RegisterField(module, "wave_scale", &wave_scale);
    SettingsRegistry::RegisterField(module, "flow_dir_change", &flow_dir_change);
    SettingsRegistry::RegisterField(module, "cell_size", &cell_size);
}

void RiverModule::LoadSettings(SettingsDoc& doc, ToolboxIni* legacy)
{
    ToolboxModule::LoadSettings(doc, legacy);
    doc.Get(Name(), "rivers", rivers_by_map); // keeps current (empty) map if the key is absent
    doc.Get(Name(), "textures", textures);
    if (textures.empty()) textures = {0x45478}; // never persist to a permanently-blank selection
    mesh_dirty = true;
}

void RiverModule::SaveSettings(SettingsDoc& doc)
{
    ToolboxModule::SaveSettings(doc);
    doc.Set(Name(), "rivers", rivers_by_map);
    doc.Set(Name(), "textures", textures);
}

void RiverModule::DrawSettings()
{
    const auto red = ImGui::ColorConvertU32ToFloat4(Colors::Red());
    const auto green = ImGui::ColorConvertU32ToFloat4(Colors::Green());
    ImGui::TextColored(red, "Warning: This is a beta feature.");
    if (!GameWorldCompositor::IsActive())
        ImGui::TextColored(red, GameWorldCompositor::HasFailed() ? "  in-world compositor FAILED to install." : "  in-world compositor: not installed yet.");

    ImGui::TextUnformatted("Textures");
    ImGui::ShowHelp("The in-game lava textures (plus the water sheet). Pick one for a uniform surface, or several\nto mix them across the map in ~1024-unit patches. Nothing selected = nothing drawn.");
    for (const auto& kt : kKnownTextures) {
        const auto it = std::find(textures.begin(), textures.end(), kt.id);
        bool on = it != textures.end();
        ImGui::PushID(static_cast<int>(kt.id));
        if (ImGui::Checkbox(kt.name, &on)) {
            if (on) textures.push_back(kt.id);
            else textures.erase(std::find(textures.begin(), textures.end(), kt.id));
            mesh_dirty = true;
        }
        ImGui::SameLine(0.f, 8.f);
        ImGui::TextDisabled("0x%X", kt.id);
        if (on) {
            IDirect3DTexture9** pp = GwDatModule::LoadTextureFromFileId(kt.id);
            const bool ok = pp && *pp;
            ImGui::SameLine();
            ImGui::TextColored(ok ? green : red, ok ? ICON_FA_CHECK : "loading/invalid");
        }
        ImGui::PopID();
    }
    if (textures.empty()) ImGui::TextColored(red, "No texture selected - nothing will draw.");

    ImGui::Checkbox("Occlude behind terrain", &occlude_behind_terrain);
    ImGui::DragFloat("Maximum render distance", &render_max_distance, 5.f, 10.f, 100000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Glow", &glow, 0.02f, 0.f, 4.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Flow speed", &flow_speed, 0.01f, -2.f, 2.f, "%.2f");
    ImGui::DragFloat("Flow direction drift", &flow_dir_change, 0.005f, 0.f, 1.f, "%.3f rad/s", ImGuiSliderFlags_AlwaysClamp);
    if (ImGui::DragFloat("Texture tile length", &tile_length, 4.f, 16.f, 4096.f, "%.0f", ImGuiSliderFlags_AlwaysClamp)) mesh_dirty = true;
    if (ImGui::DragFloat("Height lift", &z_lift, 0.5f, 0.f, 200.f, "%.1f", ImGuiSliderFlags_AlwaysClamp)) mesh_dirty = true;
    auto col = ImGui::ColorConvertU32ToFloat4(lava_tint);
    if (ImGui::ColorEdit4("Tint", &col.x, ImGuiColorEditFlags_AlphaBar)) lava_tint = ImGui::ColorConvertFloat4ToU32(col);

    ImGui::Separator();
    ImGui::TextUnformatted("Waves");
    ImGui::DragFloat("Wave amplitude", &wave_amplitude, 1.f, 0.f, 500.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::DragFloat("Wave scale", &wave_scale, 0.05f, 0.05f, 8.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("Wavelength multiplier. Higher = shorter, choppier waves.");

    ImGui::Separator();
    if (ImGui::Checkbox("Cover entire ground", &cover_entire_ground)) mesh_dirty = true;
    ImGui::SameLine();
    ImGui::ShowHelp("On: flood the whole walkable floor.\nOff: only the rivers you author below.");
    if (cover_entire_ground) {
        if (ImGui::DragFloat("Ground cell size", &cell_size, 5.f, 16.f, 1000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp)) mesh_dirty = true;
        ImGui::ShowHelp("Tessellation cell (world units). Smaller = finer waves but more geometry.");
        return;
    }

    const uint32_t map_id = static_cast<uint32_t>(GW::Map::GetMapID());
    ImGui::Text("Rivers on this map (id %u)", map_id);
    auto& rivers = rivers_by_map[map_id];
    if (active_river >= static_cast<int>(rivers.size())) active_river = -1;

    int to_remove = -1;
    for (int i = 0; i < static_cast<int>(rivers.size()); i++) {
        auto& r = rivers[i];
        ImGui::PushID(i);
        const bool is_active = (i == active_river);
        if (ImGui::RadioButton("##active", is_active)) active_river = is_active ? -1 : i;
        ImGui::SameLine();
        if (ImGui::CollapsingHeader((std::string("River ") + std::to_string(i) + " (" + std::to_string(r.points.size()) + " pts)").c_str())) {
            if (ImGui::DragFloat("Width", &r.width, 5.f, 10.f, 5000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp)) mesh_dirty = true;
            if (ImGui::SmallButton("Undo last point") && !r.points.empty()) {
                r.points.pop_back();
                mesh_dirty = true;
            }
            ImGui::SameLine();
            if (ImGui::SmallButton("Delete river")) to_remove = i;
        }
        ImGui::PopID();
    }
    if (to_remove >= 0) {
        rivers.erase(rivers.begin() + to_remove);
        if (active_river == to_remove) active_river = -1;
        mesh_dirty = true;
    }

    if (ImGui::Button("New river")) {
        rivers.push_back({{}, new_river_width});
        active_river = static_cast<int>(rivers.size()) - 1;
    }
    ImGui::SameLine();
    const bool can_add = active_river >= 0 && active_river < static_cast<int>(rivers.size());
    ImGui::BeginDisabled(!can_add);
    if (ImGui::Button("Add point at player")) {
        if (const auto* me = GW::Agents::GetControlledCharacter()) {
            rivers[active_river].points.push_back({me->pos.x, me->pos.y});
            mesh_dirty = true;
        }
    }
    ImGui::EndDisabled();
    ImGui::SameLine();
    ImGui::DragFloat("New width", &new_river_width, 5.f, 10.f, 5000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    if (!can_add) ImGui::TextDisabled("Select a river (radio button) or 'New river', then walk and 'Add point at player'.");
}

void RiverModule::Initialize()
{
    ToolboxModule::Initialize();
    RegisterSettings(this);
    if (!compositor_token) compositor_token = GameWorldCompositor::RegisterDraw(&RiverModule::DrawInWorld);
}

void RiverModule::DrawSettingsInternal()
{
    DrawSettings();
}

void RiverModule::SignalTerminate()
{
    if (compositor_token) {
        GameWorldCompositor::UnregisterDraw(compositor_token);
        compositor_token = 0;
    }
}

void RiverModule::Terminate()
{
    SignalTerminate();
    if (mesh_vb) {
        mesh_vb->Release();
        mesh_vb = nullptr;
    }
    if (lava_vs) {
        lava_vs->Release();
        lava_vs = nullptr;
    }
    if (lava_ps) {
        lava_ps->Release();
        lava_ps = nullptr;
    }
    if (lava_decl) {
        lava_decl->Release();
        lava_decl = nullptr;
    }
    mesh_cap = 0;
    mesh_vertices.clear();
    tex_ranges.clear();
    mesh_ready = false;
    mesh_dirty = true;
    built_map_id = 0xFFFFFFFFu;
    ToolboxModule::Terminate();
}
