#include "stdafx.h"

#include <GWCA/Constants/Maps.h>
#include <GWCA/GameContainers/GamePos.h>
#include <GWCA/GameEntities/Camera.h>
#include <GWCA/GameEntities/Map.h>
#include <GWCA/Managers/CameraMgr.h>
#include <GWCA/Managers/ChatMgr.h>
#include <GWCA/Managers/MapMgr.h>

#include <Color.h>
#include <Defines.h>
#include <ImGuiAddons.h>
#include <Logger.h>
#include <Modules/AudioSettings.h>
#include <Modules/GwDatTextureModule.h>
#include <Modules/Resources.h>
#include <Modules/WeatherModule.h>
#include <Timer.h>
#include <Utils/ArenaNetFileParser.h>
#include <Utils/GameWorldCompositor.h>
#include <Utils/GuiUtils.h>
#include <Utils/SettingsDoc.h>
#include <Utils/SettingsRegistry.h>
#include <Utils/TextUtils.h>

// Generated by CMake (fxc) from the .hlsl in the shared shaders dir.
#include <GWCA/Context/MapContext.h>
#include <Utils/ToolboxUtils.h>
#include "Widgets/Minimap/Shaders/weather_billboard_ps.h"
#include "Widgets/Minimap/Shaders/weather_billboard_vs.h"
#include "Widgets/Minimap/Shaders/weather_instanced_vs.h"

// External linkage (not the anonymous namespace) so glaze can reflect it as a vector element when
// (de)serialising the conditions list. A plain aggregate so reflection works without a glz::meta.
namespace weather_module {
    constexpr int kTypeRain = 0; // weather type
    constexpr int kTypeSnow = 1;
    constexpr int kTypeCount = 2;

    constexpr int kDecalNone = 0; // floor decal left at each impact
    constexpr int kDecalSplash = 1;
    constexpr int kDecalSettle = 2;
    constexpr int kDecalCount = 3;
    constexpr int kDecalAuto = -1;     // not set: derive from type (rain -> splash, snow -> settle)
    constexpr float kDriftAuto = -1.f; // drift not set: derive from type (snow floats sideways, rain does not)

    struct WeatherCondition {
        std::string name = "Rain";
        int type = kTypeRain;
        bool active = false;
        int drop_count = 1000;
        float drop_size = 8.f;
        float fall_speed = 2000.f;    // gwinch/sec
        float spread_radius = 2500.f; // horizontal half-extent of the volume; fixed (forced on load, no UI)
        float wind_dir_min = 0.f; // a heading is picked at random in [min, max] when the condition activates (degrees)
        float wind_dir_max = 0.f;
        float wind_tilt = 0.f; // how far the fall is tilted from straight-down, degrees (0 = vertical, 89 = sideways)
        float splash_chance = 1.f;      // 0..1 chance an impact spawns a splash
        std::vector<uint32_t> sounds;   // .dat sound file ids played at random while active
        float sound_min_interval = 8.f; // seconds between sounds
        float sound_max_interval = 25.f;
        bool sound_3d = false;                    // play from a random nearby position (varies volume/pan)
        float ambient = 0.f;                      // 0..1 overcast dimming this condition contributes to the scene
        unsigned int tint = 0xFFFFFFFFu;          // this condition's particle tint (ImGui-packed); white = untinted
        unsigned int overcast_tint = 0xFFA09078u; // the scene-dimming colour while this condition drives the overcast
        int floor_decal = kDecalAuto;             // what each impact leaves on the ground: none/splash/settle
        float drift = kDriftAuto;                 // lateral float as particles fall (gwinch/sec amplitude); 0 = none
        bool wind_camera_relative = false;        // wind heading is relative to the camera (stays screen-fixed as you rotate)
    };

    // A broad weather climate. Maps/regions are grouped into one of these (see ClimateForRegion), so weather is
    // authored per-climate rather than per-region - the same region can later host more than one climate.
    enum class Climate {
        Temperate,
        Arid,
        Tropical,
        Mountainous,
        Volcanic,
        Desertous, // appended so existing serialised values keep their meaning
    };

    // Automatic weather, defined separately from the conditions themselves: within a climate, a reference to one
    // condition (by name) and how likely it is to be chosen. The leftover probability across a climate's entries
    // is "clear" (no weather). Both are plain aggregates so glaze reflects them as the conditions list does.
    struct ClimateWeather {
        std::string condition; // name of a WeatherCondition
        float weight = 0.3f;   // 0..1 probability this condition is picked for the climate on each weather roll
    };
    struct ClimateProfile {
        Climate climate = Climate::Temperate;
        std::vector<ClimateWeather> entries;
    };
} // namespace weather_module

namespace {
    using namespace weather_module;

    // Game weather assets in the .dat: a 32px raindrop, a 32px snowflake, and a 128x128 splash sheet (4x4 keyframes).
    constexpr uint32_t kRaindropFileId = 0x1997d;
    constexpr uint32_t kSnowflakeFileId = 0xca1a;
    constexpr uint32_t kSplashFileId = 0x1baa1;
    constexpr int kSplashCols = 4, kSplashRows = 4, kSplashFrames = kSplashCols * kSplashRows;
    constexpr float kZNear = 47.0f, kZFar = 100000.f; // must match GW's projection for occlusion to line up
    constexpr float kMaxRadius = 2500.f;              // compass range; cap for any radius in the UI

    // Fixed in code (deliberately not in the UI, but handy to tweak while debugging).
    float column_height = 2500.f;     // vertical span drops fall through
    float fog_factor = 1.0f;          // distance-fade strength fed to the shader
    float splash_size = 8.f;          // world size of a splash billboard
    float splash_duration = 0.5f;     // seconds to play the 16 keyframes
    float recycle_below = 600.f;      // fallback recycle band when no terrain altitude is available
    float splash_lift = 5.f;          // raise splash base above the ground to avoid z-fighting
    int max_splashes = 4000;          // per-condition cap on live splashes
    float snow_sway_speed = 1.5f;     // radians/sec of snow's lateral wobble
    float snow_sway_amp = 120.f;      // gwinch/sec horizontal sway velocity (positional amplitude = amp / speed)
    float snow_settle_chance = 0.15f; // fraction of landed flakes that leave a lingering patch
    float snow_settle_size = 14.f;    // world size of a settled flake billboard
    float snow_settle_duration = 4.f; // seconds a settled flake holds before it has fully faded
    float snow_settle_fade = 0.4f;    // last fraction of the lifetime spent fading out
    int max_settled = 4000;           // per-condition cap on settled flakes

    // The floor decal a condition leaves; resolves kDecalAuto from the weather type so old saved conditions and
    // freshly-added ones behave as before (rain splashes, snow settles).
    constexpr int EffectiveDecal(const WeatherCondition& c)
    {
        return c.floor_decal != kDecalAuto ? c.floor_decal : (c.type == kTypeSnow ? kDecalSettle : kDecalSplash);
    }
    // The lateral float amplitude; resolves kDriftAuto from the type (snow floats by default, rain falls straight).
    float EffectiveDrift(const WeatherCondition& c)
    {
        return c.drift >= 0.f ? c.drift : (c.type == kTypeSnow ? snow_sway_amp : 0.f);
    }

    std::vector<WeatherCondition> DefaultConditions()
    {
        return {
            {"Heavy Rain", kTypeRain, false, 4000, 10.f, 1000.f, 2500.f, 0.f, 25.f, 0.f, 0.30f, {0x20ed0, 0x20ed1}, 6.f, 60.f, false, 0.50f},
            {"Light Rain", kTypeRain, false, 300, 8.f, 1600.f, 2500.f, 0.f, 25.f, 0.f, 0.30f, {0x20ed0, 0x20ed1}, 6.f, 60.f, false, 0.20f},
            {"Snow", kTypeSnow, false, 1500, 8.f, 400.f, 2500.f, 30.f, 55.f, 10.f, 0.f, {}, 10.f, 30.f, false, 0.30f},
            // Ash: snow's drift (no floor decal) with a dark warm-grey tint and a heavier overcast.
            {"Ashfall", kTypeSnow, false, 1200, 9.f, 350.f, 2500.f, 30.f, 55.f, 8.f, 0.f, {}, 12.f, 35.f, false, 0.45f, 0xFF42464Au, 0xFFA09078u, kDecalNone},
            // Sand: snow-type tilted nearly sideways, blown across the view (camera-relative), dense, sandy, no decal.
            {"Sandstorm", kTypeSnow, false, 10000, 6.f, 250.f, 2500.f, 90.f, 90.f, 80.f, 0.f, {}, 12.f, 35.f, false, 0.55f, 0xFF6EA8C2u, 0xFF00717Fu, kDecalNone, 0.f, true},
        };
    }
    std::vector<WeatherCondition> conditions = DefaultConditions();

    // Default climate->weather table, referencing the default condition names above. Leftover probability per
    // climate is clear weather. Arid is omitted on purpose: dry by default, but offered in the picker to edit.
    std::vector<ClimateProfile> DefaultClimateProfiles()
    {
        const auto p = [](const Climate c, std::vector<ClimateWeather> e) { return ClimateProfile{c, std::move(e)}; };
        return {
            p(Climate::Temperate, {{"Light Rain", 0.45f}, {"Heavy Rain", 0.15f}}),
            p(Climate::Tropical, {{"Heavy Rain", 0.55f}, {"Light Rain", 0.25f}}),
            p(Climate::Mountainous, {{"Snow", 0.6f}}),
            p(Climate::Volcanic, {{"Ashfall", 0.6f}}),
            p(Climate::Desertous, {{"Sandstorm", 0.30f}}),
            p(Climate::Arid, {{"Sandstorm", 0.10f}}),
        };
    }
    std::vector<ClimateProfile> climate_profiles = DefaultClimateProfiles();

    // Fixed, not user-facing: weather always occludes behind terrain and renders to the compass range.
    constexpr bool occlude_behind_terrain = true;
    constexpr float render_max_distance = kMaxRadius;
    unsigned int ambient_color = 0xFFA09078u; // overcast tint of the condition currently driving the dimming (runtime)
    float ambient_strength = 0.f;             // eased aggregate dimming of active conditions (runtime, not saved)

    bool auto_weather = false;   // drive which conditions are active from the climate->weather table
    float auto_change_min = 3.f; // minutes between automatic weather rolls (random in [min, max])
    float auto_change_max = 8.f;
    Climate auto_climate = Climate::Temperate; // climate the current automatic weather was last rolled for (runtime)
    float auto_timer = -1.f;                   // minutes until the next automatic roll; <0 = roll on the next update (runtime)

    // The climates the picker offers, with their display names (our own concept, so plain text - not EncStrings).
    constexpr struct {
        Climate climate;
        const char* name;
    } kClimates[] = {
        {Climate::Temperate, "Temperate"}, {Climate::Arid, "Arid"}, {Climate::Desertous, "Desertous"}, {Climate::Tropical, "Tropical"}, {Climate::Mountainous, "Mountainous"}, {Climate::Volcanic, "Volcanic"},
    };

    const char* ClimateName(const Climate climate)
    {
        for (const auto& k : kClimates)
            if (k.climate == climate) return k.name;
        return "(climate)";
    }

    // Which climate a region currently belongs to. Coarse for now (whole-region); later this can become
    // per-map so e.g. the arid stretches of Maguuma differ from its rainforest.
    Climate ClimateForRegion(const GW::Region region)
    {
        switch (region) {
            case GW::Region_NorthernShiverpeaks:
            case GW::Region_FarShiverpeaks:
            case GW::Region_DepthsOfTyria:
                return Climate::Mountainous;
            case GW::Region_CrystalDesert:
            case GW::Region_Desolation:
                return Climate::Desertous;
            case GW::Region_Kourna:
            case GW::Region_Vaabi:
                return Climate::Arid;
            case GW::Region_FissureOfWoe:
            case GW::Region_DomainOfAnguish:
                return Climate::Volcanic;
            case GW::Region_Maguuma:
            case GW::Region_Kurzick:
            case GW::Region_ShingJea:
            case GW::Region_Istan:
            case GW::Region_TarnishedCoast:
                return Climate::Tropical;
            default: // Kryta, Ascalon, Kaineng, Luxon, Charr Homelands, ...
                return Climate::Temperate;
        }
    }

    // Climate for a specific map: an explicit per-map override wins, else fall back to the map's region. This is
    // where sub-region variation lives - e.g. Dry Top sits in (tropical) Maguuma but is itself arid.
    Climate ClimateForMap(const GW::Constants::MapID map_id)
    {
        static const std::unordered_map<GW::Constants::MapID, Climate> overrides = {
            {GW::Constants::MapID::Dry_Top, Climate::Arid},
        };
        if (const auto it = overrides.find(map_id); it != overrides.end()) return it->second;
        const auto info = GW::Map::GetMapInfo(map_id);
        return ClimateForRegion(info ? info->region : GW::Region_DevRegion);
    }

    // POSITION (world) + D3DCOLOR tint + UV; quads are built camera-/ground-aligned on the CPU.
    struct WeatherVertex {
        float x, y, z;
        DWORD color;
        float u, v;
    };
    struct Raindrop {
        float x, y, z, ground_z, sway_phase;
    }; // falls in +z (GW up is -z); ground_z queried at seed time; sway_phase drives snow's lateral wander
    struct Splash {
        float x, y, z, age;
    };
    struct Settle {
        float x, y, z, age;
    }; // a snowflake lying flat on the ground; ages out with an alpha fade
    struct Particles {
        std::vector<Raindrop> raindrops;
        std::vector<Splash> splashes;
        std::vector<Settle> settled;
        float sound_timer = -1.f; // seconds until the next sound; <0 = not yet scheduled
    };
    // Only one condition runs at a time (enforced at every toggle point), so a single live particle set suffices
    // instead of one per condition - a large memory saving at high drop counts. active_condition is the index
    // currently driving it, -1 = clear.
    Particles active_particles;
    int active_condition = -1;
    float active_wind_dir = 0.f; // heading rolled from the active condition's [wind_dir_min, max] when it activated
    float center_z = 0.f;        // last update's focus altitude; the column is shifted by its change each tick so a
                                 // slow-falling condition (which rarely reseeds its top) still tracks the player's height
    bool reset_requested = false;     // set by WeatherModule::Reset(); consumed on the next update

    // Rain is GPU-instanced: one record per drop (centre + the two half-extent axes), expanded to a quad
    // by weather_instanced_vs. Snow/splash/settle keep the CPU-built indexed-quad path (per-instance UV
    // animation and alpha fade don't fit the simple instance record).
    struct WeatherInstance {
        float cx, cy, cz;
        float ax0, ax1, ax2;
        float ay0, ay1, ay2;
        float cr, cg, cb, ca; // per-instance tint (RGBA, unpacked) so rain conditions keep their own tint in one draw
    };
    struct GeomVert {
        float sx, sy, u, v;
    }; // static unit quad: corner sign + uv

    std::vector<WeatherInstance> rain_instances;
    std::vector<WeatherVertex> snow_vertices, splash_vertices;
    IDirect3DVertexBuffer9 *rain_inst_vb = nullptr, *snow_vb = nullptr, *splash_vb = nullptr;
    IDirect3DVertexBuffer9* quad_geom_vb = nullptr; // shared unit quad (stream 0 for instancing)
    size_t rain_inst_cap = 0;                       // bytes
    size_t snow_cap = 0, splash_cap = 0;            // in vertices
    IDirect3DIndexBuffer9* quad_ib = nullptr;       // shared 0-1-2 / 0-2-3 indices for every 4-vertex quad
    size_t quad_ib_quads = 0;                       // capacity in quads
    IDirect3DVertexShader9* weather_vs = nullptr;
    IDirect3DVertexShader9* weather_inst_vs = nullptr;
    IDirect3DPixelShader9* weather_ps = nullptr;
    IDirect3DVertexDeclaration9* weather_decl = nullptr;
    IDirect3DVertexDeclaration9* weather_inst_decl = nullptr;
    IDirect3DTexture9 **raindrop_tex_pp = nullptr, **snowflake_tex_pp = nullptr, **splash_tex_pp = nullptr; // stable slots from the texture cache
    bool textures_requested = false;
    clock_t last_update = 0;                  // TIMER_INIT() at the last throttled update (0 = not yet run)
    constexpr clock_t kUpdateIntervalMs = 16; // rebuild physics + geometry at ~60 Hz; drawing stays per-frame
    uint32_t rng = 0x1234567u;
    bool rain_ready = false, snow_ready = false, splash_ready = false;
    int compositor_token = 0;
    GW::HookEntry chat_hook_entry;

    float frand(const float lo, const float hi)
    {
        rng = rng * 1664525u + 1013904223u;
        return lo + static_cast<float>(rng >> 8) / static_cast<float>(0xFFFFFFu) * (hi - lo);
    }

    void cross3(const float a[3], const float b[3], float o[3])
    {
        o[0] = a[1] * b[2] - a[2] * b[1];
        o[1] = a[2] * b[0] - a[0] * b[2];
        o[2] = a[0] * b[1] - a[1] * b[0];
    }

    void normalize3(float v[3])
    {
        const float l = std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
        if (l > 1e-6f) {
            v[0] /= l;
            v[1] /= l;
            v[2] /= l;
        }
    }

    // Unit fall direction: straight down (world up is -z, so +z) tilted tilt_deg from vertical toward the dir_deg
    // heading. Velocity is this scaled by fall_speed, so wind only sets direction. dir_deg is the per-activation
    // roll within the condition's [wind_dir_min, wind_dir_max] range.
    void WindDir(const float dir_deg, const float tilt_deg, float out[3])
    {
        constexpr float kDeg2Rad = 0.01745329f;
        const float st = std::sin(tilt_deg * kDeg2Rad), ct = std::cos(tilt_deg * kDeg2Rad);
        out[0] = st * std::cos(dir_deg * kDeg2Rad);
        out[1] = st * std::sin(dir_deg * kDeg2Rad);
        out[2] = ct;
    }

    constexpr float kNoGround = std::numeric_limits<float>::max(); // "no terrain here" sentinel
    constexpr float kGroundCell = 64.f;                            // world-grid resolution of the altitude cache (gwinch)
    constexpr size_t kGroundCacheMax = 1u << 16;                   // entry cap; cleared wholesale past this
    std::unordered_map<uint64_t, float> ground_cache;              // (x,y) cell -> terrain altitude, valid within a map

    // Highest terrain surface at (x,y) over all planes (GW up is -z, so highest = min altitude), or kNoGround.
    float RawGroundZAt(const float x, const float y)
    {
        const GW::PathingMapArray* pm = GW::Map::GetPathingMap();
        const uint32_t n = pm ? static_cast<uint32_t>(pm->size()) : 0;
        float best = kNoGround;
        for (uint32_t zp = 0; zp < n; ++zp) {
            GW::GamePos p{x, y, zp};
            const float a = GW::Map::QueryAltitude(&p);
            if (a != 0.f && a < best) best = a;
        }
        return best;
    }

    // Memoised by a coarse world cell: terrain is static per (x,y), but the per-plane query is costly and we
    // sample it for every drop that lands, so nearby drops reuse a cell. Invalidated on map change in SyncWeather.
    float GroundZAt(const float x, const float y, const float fallback)
    {
        const int gx = static_cast<int>(std::floor(x / kGroundCell));
        const int gy = static_cast<int>(std::floor(y / kGroundCell));
        const uint64_t key = static_cast<uint64_t>(static_cast<uint32_t>(gx)) << 32 | static_cast<uint32_t>(gy);
        if (const auto it = ground_cache.find(key); it != ground_cache.end()) return it->second == kNoGround ? fallback : it->second;
        const float z = RawGroundZAt(x, y);
        if (z != kNoGround) { // don't cache misses: they're rare (drops over the void) and risk poisoning on transient null maps
            if (ground_cache.size() >= kGroundCacheMax) ground_cache.clear();
            ground_cache.emplace(key, z);
        }
        return z == kNoGround ? fallback : z;
    }

    // A .dat file is a sound if its type bytes look like an ANet/MP3 stream (mirrors FavorTracker).
    bool IsValidSound(const uint32_t id)
    {
        static std::map<uint32_t, bool> cache;
        if (!id) return false;
        if (const auto it = cache.find(id); it != cache.end()) return it->second;
        ArenaNetFileParser::GameAssetFile f;
        f.readFromDat(id);
        const char* ft = f.fileType();
        const bool ok = f.file_id == id && ft && static_cast<unsigned char>(ft[0]) == 0xFF && (static_cast<unsigned char>(ft[1]) & 0xE6) == 0xE2;
        cache[id] = ok;
        return ok;
    }

    void UpdateSounds(const WeatherCondition& c, Particles& p, const float dt, const float cx, const float cy, const float cz)
    {
        if (c.sounds.empty() || c.sound_max_interval <= 0.f) return;
        if (p.sound_timer < 0.f) { // first active frame: schedule, don't play immediately
            p.sound_timer = frand(c.sound_min_interval, c.sound_max_interval);
            return;
        }
        if ((p.sound_timer -= dt) > 0.f) return;
        const size_t idx = std::min(c.sounds.size() - 1, static_cast<size_t>(frand(0.f, static_cast<float>(c.sounds.size()))));
        if (c.sounds[idx]) {
            // PlaySound marshals to the game thread itself, so calling from here is safe.
            if (c.sound_3d) {
                const float ang = frand(0.f, 6.2831853f), dist = frand(200.f, 1500.f);
                const GW::Vec3f pos{cx + dist * std::cos(ang), cy + dist * std::sin(ang), cz - frand(0.f, 1000.f)};
                AudioSettings::PlaySoundFileId(c.sounds[idx], &pos);
            }
            else {
                AudioSettings::PlaySoundFileId(c.sounds[idx]);
            }
        }
        p.sound_timer = frand(c.sound_min_interval, c.sound_max_interval);
    }

    // Pick one condition (or clear) for the region from its profile, weighted by each entry's probability, and
    // set exactly that condition active. Probability left over beyond the entries' sum is clear weather; if the
    // entries sum past 1 they are normalised among themselves (no clear).
    void RerollAutoWeather(const Climate climate)
    {
        const ClimateProfile* prof = nullptr;
        for (const auto& cp : climate_profiles)
            if (cp.climate == climate) { prof = &cp; break; }

        int chosen = -1; // index into conditions; -1 = clear
        if (prof) {
            float sum = 0.f;
            for (const auto& e : prof->entries) sum += std::max(0.f, e.weight);
            float r = frand(0.f, std::max(sum, 1.f));
            for (const auto& e : prof->entries) {
                const float w = std::max(0.f, e.weight);
                if (w <= 0.f) continue;
                if (r < w) { // this entry won the roll; resolve its name to a live condition (clear if it's gone)
                    for (int i = 0; i < static_cast<int>(conditions.size()); i++)
                        if (conditions[i].name == e.condition) { chosen = i; break; }
                    break;
                }
                r -= w;
            }
        }
        for (int i = 0; i < static_cast<int>(conditions.size()); i++)
            conditions[i].active = i == chosen;
    }

    // While enabled, drive the active conditions from the climate table: re-roll when the climate changes (incl.
    // the first run), and then every few (random) minutes. dt is in seconds.
    void UpdateAutoWeather(const float dt)
    {
        if (!auto_weather) return;
        if (!GW::Map::GetCurrentMapInfo()) return; // map not loaded yet; leave whatever is showing
        const Climate climate = ClimateForMap(GW::Map::GetMapID());
        if (climate != auto_climate || auto_timer < 0.f) {
            auto_climate = climate;
            RerollAutoWeather(climate);
            auto_timer = frand(auto_change_min, auto_change_max);
            return;
        }
        if ((auto_timer -= dt / 60.f) <= 0.f) { // timer is in minutes
            RerollAutoWeather(climate);
            auto_timer = frand(auto_change_min, auto_change_max);
        }
    }

    // Side count of the square grid that tiles the spawn area for stratified placement.
    int SpawnGrid(const int drop_count)
    {
        return std::max(1, static_cast<int>(std::ceil(std::sqrt(static_cast<float>(std::max(1, drop_count))))));
    }

    // Initial fill of the column. Stratified placement: each drop owns one grid cell, jittered within it, so the
    // volume is evenly spread over the player-centred area instead of clumping. The column stays centred on the
    // player; wind only drifts drops through it (UpdateCondition wraps them at the bubble edge), so the origin
    // does not shift with the wind direction.
    void seed_drop(Raindrop& d, const WeatherCondition& c, const float cx, const float cy, const float cz, const int index, const int grid)
    {
        const float top_z = cz - column_height;
        const float cell = 2.f * c.spread_radius / static_cast<float>(grid);
        d.x = cx - c.spread_radius + (static_cast<float>(index % grid) + frand(0.f, 1.f)) * cell;
        d.y = cy - c.spread_radius + (static_cast<float>(index / grid) + frand(0.f, 1.f)) * cell;
        d.ground_z = GroundZAt(d.x, d.y, cz + recycle_below);
        // Spread the fill through the visible column (top..ground) so the drops don't fall as one synchronised lump.
        d.z = top_z + frand(0.f, std::max(0.f, d.ground_z - top_z));
        d.sway_phase = frand(0.f, 6.2831853f);
    }

    void UpdateCondition(const WeatherCondition& c, Particles& p, const float dt, const float cx, const float cy, const float cz, const float wind_dir, const float center_dz)
    {
        const int grid = SpawnGrid(c.drop_count);
        if (static_cast<int>(p.raindrops.size()) != c.drop_count) {
            p.raindrops.resize(std::max(0, c.drop_count));
            for (int i = 0; i < static_cast<int>(p.raindrops.size()); i++)
                seed_drop(p.raindrops[i], c, cx, cy, cz, i, grid);
        }
        const int decal = EffectiveDecal(c);
        const bool splash = decal == kDecalSplash;
        const float drift = EffectiveDrift(c);
        const bool settle = decal == kDecalSettle;
        const float top_z = cz - column_height;
        const float diameter = 2.f * c.spread_radius;
        // Velocity is the (unit) fall direction scaled by fall_speed, so wind sets the direction, not the speed.
        float vel[3];
        WindDir(wind_dir, c.wind_tilt, vel);
        const float vx = vel[0] * c.fall_speed, vy = vel[1] * c.fall_speed, vz = vel[2] * c.fall_speed;
        for (int i = 0; i < static_cast<int>(p.raindrops.size()); i++) {
            auto& d = p.raindrops[i];
            d.z += vz * dt + center_dz; // fall, plus the whole column tracking the player's vertical movement
            // Float: an out-of-phase sin/cos wobble so each flake wanders sideways rather than falling in a line.
            const float sway_x = drift > 0.f ? drift * std::sin(d.sway_phase) : 0.f;
            const float sway_y = drift > 0.f ? drift * std::cos(d.sway_phase) : 0.f;
            d.sway_phase += snow_sway_speed * dt;
            d.x += (vx + sway_x) * dt;
            d.y += (vy + sway_y) * dt;
            // Keep the volume centred on the player: a drop blown past one edge of the bubble wraps to the
            // opposite edge (entering from upwind), so the wind only sets which way drops stream through a fixed,
            // player-centred column. Re-query the terrain under the wrapped position.
            bool wrapped = false;
            if (const float rx = d.x - cx; rx > c.spread_radius) { d.x -= diameter; wrapped = true; }
            else if (rx < -c.spread_radius) { d.x += diameter; wrapped = true; }
            if (const float ry = d.y - cy; ry > c.spread_radius) { d.y -= diameter; wrapped = true; }
            else if (ry < -c.spread_radius) { d.y += diameter; wrapped = true; }
            if (wrapped) d.ground_z = GroundZAt(d.x, d.y, cz + recycle_below);
            if (d.z >= d.ground_z) {
                // Landed: drop a decal here (within the bubble, since x/y are kept centred), then fall again from
                // the top of the same column. Resample the terrain in case it differs from the spawn point.
                if (splash && frand(0.f, 1.f) < c.splash_chance && static_cast<int>(p.splashes.size()) < max_splashes) p.splashes.push_back({d.x, d.y, GroundZAt(d.x, d.y, d.ground_z), 0.f});
                if (settle && frand(0.f, 1.f) < snow_settle_chance && static_cast<int>(p.settled.size()) < max_settled) p.settled.push_back({d.x, d.y, GroundZAt(d.x, d.y, d.ground_z), 0.f});
                d.z = top_z;
                d.ground_z = GroundZAt(d.x, d.y, cz + recycle_below);
                d.sway_phase = frand(0.f, 6.2831853f);
            }
        }
        for (size_t i = 0; i < p.splashes.size();) {
            if ((p.splashes[i].age += dt) >= splash_duration) {
                p.splashes[i] = p.splashes.back();
                p.splashes.pop_back();
            }
            else
                ++i;
        }
        for (size_t i = 0; i < p.settled.size();) {
            if ((p.settled[i].age += dt) >= snow_settle_duration) {
                p.settled[i] = p.settled.back();
                p.settled.pop_back();
            }
            else
                ++i;
        }
    }

    // ImGui packs colours as 0xAABBGGRR (R low), but D3DDECLTYPE_D3DCOLOR (the CPU billboard vertex colour) wants
    // 0xAARRGGBB - so swap R and B. The instanced rain path feeds float4 RGBA instead and needs no conversion.
    DWORD ToD3DColor(const unsigned int imgui_col)
    {
        return (imgui_col & 0xFF00FF00u) | ((imgui_col & 0xFFu) << 16) | ((imgui_col >> 16) & 0xFFu);
    }

    // The 4 corners of a quad spanning center +/- the half-extent vectors ax, ay, with the given UV rect.
    // Drawn as two triangles (0-1-2, 0-2-3) via the shared index buffer, so only 4 verts are stored per quad.
    void emit_quad(std::vector<WeatherVertex>& out, const float cx, const float cy, const float cz, const float ax[3], const float ay[3], const DWORD col, const float u0, const float v0, const float u1, const float v1)
    {
        const WeatherVertex c00{cx - ax[0] - ay[0], cy - ax[1] - ay[1], cz - ax[2] - ay[2], col, u0, v1};
        const WeatherVertex c10{cx + ax[0] - ay[0], cy + ax[1] - ay[1], cz + ax[2] - ay[2], col, u1, v1};
        const WeatherVertex c11{cx + ax[0] + ay[0], cy + ax[1] + ay[1], cz + ax[2] + ay[2], col, u1, v0};
        const WeatherVertex c01{cx - ax[0] + ay[0], cy - ax[1] + ay[1], cz - ax[2] + ay[2], col, u0, v0};
        out.insert(out.end(), {c00, c10, c11, c01});
    }

    // Snow: camera-aligned square billboards on the CPU indexed path (flakes tumble, no streak).
    void AppendSnow(const WeatherCondition& c, std::vector<WeatherVertex>& out, const std::vector<Raindrop>& drops, const float right[3], const float up[3])
    {
        const float h = c.drop_size * 0.5f;
        const float ax[3] = {right[0] * h, right[1] * h, right[2] * h};
        const float ay[3] = {up[0] * h, up[1] * h, up[2] * h};
        const DWORD col = ToD3DColor(c.tint); // per-condition tint (e.g. dark for ashfall)
        for (const auto& d : drops)
            emit_quad(out, d.x, d.y, d.z, ax, ay, col, 0.f, 0.f, 1.f, 1.f);
    }

    // Rain: one instance record per drop. Streak axes (long axis along the downward velocity, width axis
    // facing the camera) are constant per condition, so they are baked into every record; the GPU expands
    // the quad. The instanced VS applies the V-flip so the texture stays upright.
    void AppendRainInstances(std::vector<WeatherInstance>& out, const WeatherCondition& c, const std::vector<Raindrop>& drops, const float right[3], const float fwd[3], const float wind_dir)
    {
        const float h = c.drop_size * 0.5f;
        float vel[3];
        WindDir(wind_dir, c.wind_tilt, vel); // unit fall direction (streak runs along it)
        float w[3];
        cross3(vel, fwd, w);
        const float wl = std::sqrt(w[0] * w[0] + w[1] * w[1] + w[2] * w[2]);
        if (wl > 1e-4f) {
            w[0] /= wl;
            w[1] /= wl;
            w[2] /= wl;
        }
        else {
            w[0] = right[0];
            w[1] = right[1];
            w[2] = right[2];
        }
        const auto t = ImGui::ColorConvertU32ToFloat4(c.tint); // unpacked RGBA, baked per instance (no R/B swap)
        const WeatherInstance base{0.f, 0.f, 0.f, w[0] * h, w[1] * h, w[2] * h, vel[0] * h, vel[1] * h, vel[2] * h, t.x, t.y, t.z, t.w};
        out.reserve(out.size() + drops.size());
        for (const auto& d : drops) {
            WeatherInstance inst = base;
            inst.cx = d.x;
            inst.cy = d.y;
            inst.cz = d.z;
            out.push_back(inst);
        }
    }

    // Vertical billboard standing on the ground: horizontal axis follows the camera so it faces the
    // viewer, vertical axis is world up (-z), anchored so the base sits at the impact point.
    void AppendSplashes(const std::vector<Splash>& s, const float right[3], const unsigned int tint)
    {
        const float hs = splash_size * 0.5f;
        const float ax[3] = {right[0] * hs, right[1] * hs, right[2] * hs};
        const float ay[3] = {0.f, 0.f, -hs};
        const DWORD col = ToD3DColor(tint);
        const float u_step = 1.f / kSplashCols, v_step = 1.f / kSplashRows;
        for (const auto& sp : s) {
            const int f = std::clamp(static_cast<int>(sp.age / splash_duration * kSplashFrames), 0, kSplashFrames - 1);
            const float u0 = static_cast<float>(f % kSplashCols) * u_step, v0 = static_cast<float>(f / kSplashCols) * v_step;
            emit_quad(splash_vertices, sp.x, sp.y, sp.z - hs - splash_lift, ax, ay, col, u0, v0, u0 + u_step, v0 + v_step);
        }
    }


    // Flat quad lying on the ground (world XY plane) drawn with the snowflake texture, so it shares the
    // snow vertex buffer/pass. Holds at full tint, then fades its alpha out over the tail of its lifetime.
    void AppendSettled(const std::vector<Settle>& s, const unsigned int tint)
    {
        const float hs = snow_settle_size * 0.5f;
        const float ax[3] = {hs, 0.f, 0.f};
        const float ay[3] = {0.f, hs, 0.f};
        const DWORD base_col = ToD3DColor(tint);
        const DWORD base_a = (base_col >> 24) & 0xFFu;
        const float fade_span = std::clamp(snow_settle_fade, 0.01f, 1.f);
        for (const auto& sp : s) {
            const float life = snow_settle_duration > 0.f ? sp.age / snow_settle_duration : 1.f;
            const float fade = life < 1.f - fade_span ? 1.f : std::max(0.f, (1.f - life) / fade_span);
            const DWORD col = (base_col & 0x00FFFFFFu) | (static_cast<DWORD>(static_cast<float>(base_a) * fade) << 24);
            emit_quad(snow_vertices, sp.x, sp.y, sp.z - splash_lift, ax, ay, col, 0.f, 0.f, 1.f, 1.f);
        }
    }

    // Grow-and-upload a raw byte blob into a write-only managed vertex buffer (used for the instance stream).
    bool UploadVB(IDirect3DDevice9* device, IDirect3DVertexBuffer9*& vb, size_t& cap_bytes, const void* data, const size_t bytes)
    {
        if (bytes == 0) return false;
        if (!vb || cap_bytes < bytes) {
            if (vb) {
                vb->Release();
                vb = nullptr;
            }
            const size_t c = bytes + bytes / 2; // headroom so count tweaks don't reallocate every frame
            if (device->CreateVertexBuffer(static_cast<UINT>(c), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &vb, nullptr) != D3D_OK) {
                cap_bytes = 0;
                return false;
            }
            cap_bytes = c;
        }
        void* mem = nullptr;
        if (vb->Lock(0, static_cast<UINT>(bytes), &mem, 0) != D3D_OK || !mem) return false;
        memcpy(mem, data, bytes);
        vb->Unlock();
        return true;
    }

    bool EnsureVb(IDirect3DDevice9* device, IDirect3DVertexBuffer9*& vb, size_t& cap, const std::vector<WeatherVertex>& verts)
    {
        const size_t needed = verts.size();
        if (needed == 0) return false;
        if (!vb || cap < needed) {
            if (vb) {
                vb->Release();
                vb = nullptr;
            }
            const size_t c = needed + needed / 2; // headroom so count tweaks don't reallocate every frame
            if (device->CreateVertexBuffer(static_cast<UINT>(c * sizeof(WeatherVertex)), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &vb, nullptr) != D3D_OK) {
                cap = 0;
                return false;
            }
            cap = c;
        }
        void* mem = nullptr;
        if (vb->Lock(0, static_cast<UINT>(needed * sizeof(WeatherVertex)), &mem, 0) != D3D_OK || !mem) return false;
        memcpy(mem, verts.data(), needed * sizeof(WeatherVertex));
        vb->Unlock();
        return true;
    }

    // The quad index pattern is static (only the count grows), so build it once and reuse it across all passes.
    bool EnsureQuadIB(IDirect3DDevice9* device, const size_t quads)
    {
        if (quads == 0) return false;
        if (quad_ib && quad_ib_quads >= quads) return true;
        if (quad_ib) {
            quad_ib->Release();
            quad_ib = nullptr;
        }
        const size_t cap = quads + quads / 2; // headroom so count tweaks don't reallocate every frame
        if (device->CreateIndexBuffer(static_cast<UINT>(cap * 6 * sizeof(uint32_t)), D3DUSAGE_WRITEONLY, D3DFMT_INDEX32, D3DPOOL_MANAGED, &quad_ib, nullptr) != D3D_OK) {
            quad_ib_quads = 0;
            return false;
        }
        void* mem = nullptr;
        if (quad_ib->Lock(0, 0, &mem, 0) != D3D_OK || !mem) {
            quad_ib->Release();
            quad_ib = nullptr;
            quad_ib_quads = 0;
            return false;
        }
        auto* idx = static_cast<uint32_t*>(mem);
        for (size_t q = 0; q < cap; q++) {
            const uint32_t b = static_cast<uint32_t>(q * 4);
            idx[q * 6 + 0] = b + 0;
            idx[q * 6 + 1] = b + 1;
            idx[q * 6 + 2] = b + 2;
            idx[q * 6 + 3] = b + 0;
            idx[q * 6 + 4] = b + 2;
            idx[q * 6 + 5] = b + 3;
        }
        quad_ib->Unlock();
        quad_ib_quads = cap;
        return true;
    }

    bool EnsureShaders(IDirect3DDevice9* device)
    {
        if (weather_vs && weather_ps && weather_decl && weather_inst_vs && weather_inst_decl && quad_geom_vb) return true;
        constexpr D3DVERTEXELEMENT9 decl[] = {
            {0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0}, {0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0}, {0, 16, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0}, D3DDECL_END()
        };
        if (!weather_decl && device->CreateVertexDeclaration(decl, &weather_decl) != D3D_OK) return false;
        if (!weather_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&weather_billboard_vs), &weather_vs) != D3D_OK) return false;
        if (!weather_ps && device->CreatePixelShader(reinterpret_cast<const DWORD*>(&weather_billboard_ps), &weather_ps) != D3D_OK) return false;

        // Instanced pipeline: stream 0 = unit quad (POSITION = corner sign, TEXCOORD0 = uv); stream 1 =
        // per-drop instance record (TEXCOORD1 = centre, TEXCOORD2/3 = the two half-extent axes, COLOR = tint).
        constexpr D3DVERTEXELEMENT9 inst_decl[] = {{0, 0, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},  {0, 8, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
                                                   {1, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1},  {1, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 2},
                                                   {1, 24, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 3}, {1, 36, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0}, D3DDECL_END()};
        if (!weather_inst_decl && device->CreateVertexDeclaration(inst_decl, &weather_inst_decl) != D3D_OK) return false;
        if (!weather_inst_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&weather_instanced_vs), &weather_inst_vs) != D3D_OK) return false;
        if (!quad_geom_vb) {
            constexpr GeomVert quad[4] = {{-1.f, -1.f, 0.f, 1.f}, {1.f, -1.f, 1.f, 1.f}, {1.f, 1.f, 1.f, 0.f}, {-1.f, 1.f, 0.f, 0.f}};
            if (device->CreateVertexBuffer(sizeof(quad), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &quad_geom_vb, nullptr) != D3D_OK) return false;
            void* mem = nullptr;
            if (quad_geom_vb->Lock(0, 0, &mem, 0) != D3D_OK || !mem) return false;
            memcpy(mem, quad, sizeof(quad));
            quad_geom_vb->Unlock();
        }
        return true;
    }

    // Advance every active condition and accumulate its geometry, then upload once per frame.
    void SyncWeather(IDirect3DDevice9* device, const GW::Camera* cam, const float dt)
    {
        rain_ready = snow_ready = splash_ready = false;
        rain_instances.clear();
        snow_vertices.clear();
        splash_vertices.clear();
        UpdateAutoWeather(dt); // may toggle which condition is active before it's read below
        if (!cam) return;

        bool reset = reset_requested; // explicit Reset() request
        reset_requested = false;

        if (!GW::Map::GetIsMapLoaded() || GW::UI::IsLoadingScreenShown()) reset = true;
        const auto ready = !reset && !GW::UI::GetIsWorldMapShowing();
        if (reset) ground_cache.clear(); // terrain altitudes are per-map; drop them when the map changes

        const float cx = cam->look_at_target.x, cy = cam->look_at_target.y, cz = cam->look_at_target.z;

        // The single active condition (first one flagged active; single-active is enforced wherever it's toggled).
        int active = -1;
        for (int i = 0; i < static_cast<int>(conditions.size()); i++)
            if (conditions[i].active) { active = i; break; }
        if (active != active_condition || reset) { // switched condition (or reset): drop the old particles, reseed fresh
            active_particles = {};
            active_condition = active;
            center_z = cz; // freshly seeded around the current altitude - no shift on this frame
            if (active >= 0) active_wind_dir = frand(conditions[active].wind_dir_min, conditions[active].wind_dir_max); // roll a heading for this run
        }
        const float dcz = cz - center_z; // the focus's vertical move this tick; the column is shifted by it so it
        center_z = cz;                   // keeps tracking the player's height even when drops barely fall (sandstorm)

        float fwd[3] = {cx - cam->position.x, cy - cam->position.y, cz - cam->position.z};
        normalize3(fwd);
        constexpr float world_up[3] = {0.f, 0.f, -1.f};
        float right[3];
        cross3(world_up, fwd, right);
        normalize3(right);
        float up[3];
        cross3(fwd, right, up);

        float ambient_target = 0.f;
        if (active >= 0 && ready) {
            auto& c = conditions[active];
            ambient_target = c.ambient;
            ambient_color = c.overcast_tint;
            // For camera-relative wind, add the camera's heading (yaw, origin @ east) so the storm keeps the same
            // on-screen direction as you rotate; recomputed each tick so it follows the camera live.
            const float heading = active_wind_dir + (c.wind_camera_relative ? cam->yaw * 57.29578f : 0.f);
            UpdateCondition(c, active_particles, dt, cx, cy, cz, heading, dcz);
            if (c.type == kTypeSnow)
                AppendSnow(c, snow_vertices, active_particles.raindrops, right, up);
            else
                AppendRainInstances(rain_instances, c, active_particles.raindrops, right, fwd, heading);
            AppendSplashes(active_particles.splashes, right, c.tint);
            AppendSettled(active_particles.settled, c.tint);
            UpdateSounds(c, active_particles, dt, cx, cy, cz);
        }
        ambient_strength += (ambient_target - ambient_strength) * std::clamp(dt * 3.f, 0.f, 1.f); // ease ~1/3 s
        rain_ready = UploadVB(device, rain_inst_vb, rain_inst_cap, rain_instances.data(), rain_instances.size() * sizeof(WeatherInstance));
        snow_ready = EnsureVb(device, snow_vb, snow_cap, snow_vertices);
        splash_ready = EnsureVb(device, splash_vb, splash_cap, splash_vertices);
    }

    // Overcast: multiply-blend a screen-filling quad UNDER the HUD so the scene dims like cloud cover.
    void DrawAmbient(IDirect3DDevice9* device, const float strength)
    {
        const GW::Camera* cam = GW::CameraMgr::GetCamera();
        if (!cam || strength <= 0.003f) return;

        // Per channel: scale the scene toward the tint by strength (white = untouched), then multiply-blend.
        const auto t = ImGui::ColorConvertU32ToFloat4(ambient_color);
        const auto chan = [&](const float c) {
            return static_cast<DWORD>(std::clamp(1.f - strength * (1.f - c), 0.f, 1.f) * 255.f + 0.5f);
        };
        const DWORD col = D3DCOLOR_ARGB(255, chan(t.x), chan(t.y), chan(t.z));

        float fwd[3] = {cam->look_at_target.x - cam->position.x, cam->look_at_target.y - cam->position.y, cam->look_at_target.z - cam->position.z};
        normalize3(fwd);
        constexpr float world_up[3] = {0.f, 0.f, -1.f};
        float right[3];
        cross3(world_up, fwd, right);
        normalize3(right);
        float up[3];
        cross3(fwd, right, up);

        const float d = kZNear + 1.f, hw = d * 4.f; // sit just past the near plane, oversized to cover any FOV
        const float qx = cam->position.x + fwd[0] * d, qy = cam->position.y + fwd[1] * d, qz = cam->position.z + fwd[2] * d;
        struct ColVtx {
            float x, y, z;
            DWORD c;
        };
        const auto corner = [&](const float sx, const float sy) -> ColVtx {
            return {qx + (right[0] * sx + up[0] * sy) * hw, qy + (right[1] * sx + up[1] * sy) * hw, qz + (right[2] * sx + up[2] * sy) * hw, col};
        };
        const ColVtx q[6] = {corner(-1, -1), corner(1, -1), corner(1, 1), corner(-1, -1), corner(1, 1), corner(-1, 1)};

        IDirect3DStateBlock9* sb = nullptr;
        if (device->CreateStateBlock(D3DSBT_ALL, &sb) != D3D_OK) return;
        if (GameWorldCompositor::SetupPipeline(device, false, kZNear, kZFar, kZFar, 0.f)) {
            device->SetRenderState(D3DRS_ZENABLE, FALSE);
            device->SetRenderState(D3DRS_ZWRITEENABLE, FALSE); // must not touch the depth buffer or it culls the scene/particles
            device->SetRenderState(D3DRS_ALPHABLENDENABLE, TRUE);
            device->SetRenderState(D3DRS_SRCBLEND, D3DBLEND_DESTCOLOR); // result = scene * quad colour (multiply)
            device->SetRenderState(D3DRS_DESTBLEND, D3DBLEND_ZERO);
            device->DrawPrimitiveUP(D3DPT_TRIANGLELIST, 2, q, sizeof(ColVtx));
        }
        sb->Apply();
        sb->Release();
    }

    // /weather <condition name> [on|off|toggle|1|0] - toggle a condition by name (names may be multi-word).
    void CHAT_CMD_FUNC(CmdWeather)
    {
        if (argc < 2) {
            Log::Info("Weather conditions:");
            for (const auto& c : conditions)
                Log::Info("  %s: %s", c.name.c_str(), c.active ? "on" : "off");
            Log::Info("Usage: /weather <condition> [on|off|toggle]");
            return;
        }
        // The trailing word, if it is a state keyword, sets the state; otherwise the whole tail is the name and
        // the command toggles. Names can contain spaces, so join everything that is not the state word.
        const std::string last = TextUtils::ToLower(TextUtils::WStringToString(argv[argc - 1]));
        int state = -1; // -1 unset, 0 off, 1 on, 2 toggle
        if (last == "on" || last == "1")
            state = 1;
        else if (last == "off" || last == "0")
            state = 0;
        else if (last == "toggle")
            state = 2;
        const int name_end = state < 0 ? argc : argc - 1;
        std::string name;
        for (int i = 1; i < name_end; i++) {
            if (i > 1) name += ' ';
            name += TextUtils::WStringToString(argv[i]);
        }
        if (name.empty()) return Log::Error("Usage: /weather <condition> [on|off|toggle]");
        if (state < 0) state = 2; // no explicit state given -> toggle

        const std::string want = TextUtils::ToLower(name);
        for (size_t i = 0; i < conditions.size(); i++) {
            if (TextUtils::ToLower(conditions[i].name) != want) continue;
            const bool on = state == 2 ? !conditions[i].active : state == 1;
            // Only one condition at a time: activate this one and clear the rest (deactivating just turns it off).
            for (auto& o : conditions)
                o.active = false;
            conditions[i].active = on;
            Log::Info("%s: %s", conditions[i].name.c_str(), on ? "on" : "off");
            return;
        }
        Log::Error("No weather condition named '%s'", name.c_str());
    }
} // namespace

void WeatherModule::DrawInWorld(IDirect3DDevice9* device)
{
    if (!textures_requested) {
        raindrop_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kRaindropFileId);
        snowflake_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kSnowflakeFileId);
        splash_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kSplashFileId);
        textures_requested = true;
    }

    // Throttle the physics + geometry rebuild to ~30 Hz; the cached vertex buffers are still drawn every
    // frame below, so motion advances in 30 Hz steps (with the full elapsed dt) while rendering stays smooth.
    if (!last_update || TIMER_DIFF(last_update) >= kUpdateIntervalMs) {
        const float dt = last_update ? std::clamp(static_cast<float>(TIMER_DIFF(last_update)) / 1000.f, 0.f, 0.1f) : 0.f;
        last_update = TIMER_INIT();
        SyncWeather(device, GW::CameraMgr::GetCamera(), dt);
    }

    DrawAmbient(device, ambient_strength); // dim the scene first, so the particles stay bright on top

    IDirect3DTexture9* rain_tex = raindrop_tex_pp ? *raindrop_tex_pp : nullptr;
    IDirect3DTexture9* snow_tex = snowflake_tex_pp ? *snowflake_tex_pp : nullptr;
    IDirect3DTexture9* splash_tex = splash_tex_pp ? *splash_tex_pp : nullptr;
    const bool have_rain = rain_ready && rain_tex && !rain_instances.empty();
    const bool have_snow = snow_ready && snow_tex && !snow_vertices.empty();
    const bool have_splash = splash_ready && splash_tex && !splash_vertices.empty();
    if ((!have_rain && !have_snow && !have_splash) || !EnsureShaders(device)) return;

    IDirect3DStateBlock9* state_block = nullptr; // restored on exit so GW's own rendering isn't corrupted
    if (device->CreateStateBlock(D3DSBT_ALL, &state_block) != D3D_OK) return;
    if (device->SetPixelShader(weather_ps) == D3D_OK && GameWorldCompositor::SetWorldViewProj(device, kZNear, kZFar)) {
        GameWorldCompositor::SetWorldRenderStates(device, occlude_behind_terrain);
        GameWorldCompositor::SetDistanceFog(device, render_max_distance, fog_factor);
        device->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_ADDRESSU, D3DTADDRESS_CLAMP);
        device->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP);
        // One shared index buffer serves both passes: the instanced pass only needs its first quad's 6 indices.
        const size_t indexed_verts = std::max(snow_vertices.size(), splash_vertices.size());
        const bool ib_ok = EnsureQuadIB(device, std::max<size_t>(indexed_verts / 4, 1)) && device->SetIndices(quad_ib) == D3D_OK;

        // Indexed pass: snow flakes + settle (snow_tex) and splashes (splash_tex), CPU-built 4-vert quads.
        if (ib_ok && device->SetVertexShader(weather_vs) == D3D_OK && device->SetVertexDeclaration(weather_decl) == D3D_OK) {
            const auto draw = [&](IDirect3DVertexBuffer9* vb, const size_t nverts) {
                if (device->SetStreamSource(0, vb, 0, sizeof(WeatherVertex)) != D3D_OK) return;
                device->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, static_cast<UINT>(nverts), 0, static_cast<UINT>(nverts / 2));
            };
            if (have_snow) {
                device->SetTexture(0, snow_tex);
                draw(snow_vb, snow_vertices.size());
            }
            if (have_splash) {
                device->SetTexture(0, splash_tex);
                draw(splash_vb, splash_vertices.size());
            }
        }

        // Instanced pass: each rain drop is one record expanded into a quad on the GPU (stream 0 = unit
        // quad, stream 1 = per-drop data with INSTANCEDATA frequency).
        if (ib_ok && have_rain && device->SetVertexShader(weather_inst_vs) == D3D_OK && device->SetVertexDeclaration(weather_inst_decl) == D3D_OK) {
            const float flags[4] = {1.f, 0.f, 0.f, 0.f}; // flip texture V (streak runs along the downward velocity)
            device->SetVertexShaderConstantF(9, flags, 1);   // tint is now per-instance (stream 1 COLOR), not a constant
            const UINT ninst = static_cast<UINT>(rain_instances.size());
            if (device->SetStreamSource(0, quad_geom_vb, 0, sizeof(GeomVert)) == D3D_OK && device->SetStreamSourceFreq(0, D3DSTREAMSOURCE_INDEXEDDATA | ninst) == D3D_OK && device->SetStreamSource(1, rain_inst_vb, 0, sizeof(WeatherInstance)) == D3D_OK &&
                device->SetStreamSourceFreq(1, D3DSTREAMSOURCE_INSTANCEDATA | 1u) == D3D_OK) {
                device->SetTexture(0, rain_tex);
                device->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, 4, 0, 2);
            }
            device->SetStreamSourceFreq(0, 1); // restore non-instanced frequency (state block also restores)
            device->SetStreamSourceFreq(1, 1);
        }
    }
    state_block->Apply();
    state_block->Release();
}

void WeatherModule::RegisterSettings(ToolboxModule* module)
{
    SettingsRegistry::RegisterField(module, "auto_weather", &auto_weather);
    SettingsRegistry::RegisterField(module, "auto_change_min", &auto_change_min);
    SettingsRegistry::RegisterField(module, "auto_change_max", &auto_change_max);
}

void WeatherModule::OnSettingsLoaded()
{
    bool seen_active = false; // single-active: keep only the first active condition (older configs may have several)
    for (auto& c : conditions) {
        if (c.active && std::exchange(seen_active, true)) c.active = false;
        c.type = std::clamp(c.type, 0, kTypeCount - 1);
        c.floor_decal = std::clamp(c.floor_decal, kDecalAuto, kDecalCount - 1);
        c.drift = std::max(c.drift, kDriftAuto);
        c.wind_dir_max = std::max(c.wind_dir_max, c.wind_dir_min);
        c.wind_tilt = std::clamp(c.wind_tilt, 0.f, 89.f);
        c.drop_count = std::clamp(c.drop_count, 0, 20000);
        c.spread_radius = kMaxRadius; // fixed, not user-editable
        c.splash_chance = std::clamp(c.splash_chance, 0.f, 1.f);
        c.sound_min_interval = std::max(c.sound_min_interval, 0.f);
        c.sound_max_interval = std::max(c.sound_max_interval, c.sound_min_interval);
        c.ambient = std::clamp(c.ambient, 0.f, 1.f);
    }
    auto_change_min = std::max(auto_change_min, 0.1f);
    auto_change_max = std::max(auto_change_max, auto_change_min);
    for (auto& cp : climate_profiles)
        for (auto& e : cp.entries)
            e.weight = std::clamp(e.weight, 0.f, 1.f);
}

void WeatherModule::LoadSettings(SettingsDoc& doc, ToolboxIni* legacy)
{
    ToolboxModule::LoadSettings(doc, legacy);
    doc.Get(Name(), "conditions", conditions);             // keeps defaults if the key is absent
    doc.Get(Name(), "climate_profiles", climate_profiles); // climate->weather table for automatic weather
    OnSettingsLoaded();
}

void WeatherModule::SaveSettings(SettingsDoc& doc)
{
    ToolboxModule::SaveSettings(doc);
    doc.Set(Name(), "conditions", conditions);
    doc.Set(Name(), "climate_profiles", climate_profiles);
}

void WeatherModule::DrawSettings()
{
    const auto red = ImGui::ColorConvertU32ToFloat4(Colors::Red());
    const auto green = ImGui::ColorConvertU32ToFloat4(Colors::Green());
    ImGui::TextColored(red, "Warning: This is a beta feature.");
    if (!GameWorldCompositor::IsActive()) ImGui::TextColored(red, GameWorldCompositor::HasFailed() ? "  in-world compositor FAILED to install." : "  in-world compositor: not installed yet.");

    // Info: the current map's climate, and which condition(s) are currently being shown.
    if (const GW::AreaInfo* info = GW::Map::GetCurrentMapInfo())
        ImGui::Text("Current map: %s (climate: %s)", Resources::GetRegionName(info->region)->string().c_str(), ClimateName(ClimateForMap(GW::Map::GetMapID())));
    std::string showing;
    for (const auto& c : conditions)
        if (c.active) showing += (showing.empty() ? "" : ", ") + c.name;
    ImGui::Text("Showing: %s", showing.empty() ? "Clear" : showing.c_str());

    ImGui::Separator();
    int to_remove = -1, to_duplicate = -1;
    for (int i = 0; i < static_cast<int>(conditions.size()); i++) {
        auto& c = conditions[i];
        ImGui::PushID(i);
        ImGui::BeginDisabled(auto_weather); // automatic weather owns the active state; show it read-only
        if (ImGui::Checkbox("##active", &c.active) && c.active) // only one condition at a time: turning one on turns the rest off
            for (int j = 0; j < static_cast<int>(conditions.size()); j++)
                if (j != i) conditions[j].active = false;
        ImGui::EndDisabled();
        ImGui::SameLine();
        char header[64];
        snprintf(header, sizeof(header), "%s###cond", c.name.empty() ? "(unnamed)" : c.name.c_str()); // stable id so editing the name doesn't collapse/unfocus the section
        if (ImGui::CollapsingHeader(header)) {
            ImGui::InputText("Name", c.name, 32);
            const char* type_names[kTypeCount] = {"Rain", "Snow"};
            ImGui::Combo("Type", &c.type, type_names, kTypeCount);
            ImGui::DragInt("Drop count", &c.drop_count, 25.f, 0, 20000, "%d", ImGuiSliderFlags_AlwaysClamp);
            ImGui::DragFloat("Drop size", &c.drop_size, 1.f, 1.f, 500.f, "%.0f");
            ImGui::DragFloat("Fall speed", &c.fall_speed, 50.f, 0.f, 30000.f, "%.0f");
            ImGui::ShowHelp("The constant speed drops travel at. Wind tilts their direction without changing this speed.");
            ImGui::DragFloatRange2("Wind direction", &c.wind_dir_min, &c.wind_dir_max, 2.f, 0.f, 360.f, "%.0f deg", "%.0f deg", ImGuiSliderFlags_AlwaysClamp);
            ImGui::ShowHelp("Range of compass headings the wind may blow toward; one is picked at random each time the\ncondition activates. A wide range (e.g. 0-360) varies the direction; a narrow one keeps it consistent.");
            ImGui::DragFloat("Wind tilt", &c.wind_tilt, 1.f, 0.f, 89.f, "%.0f deg", ImGuiSliderFlags_AlwaysClamp);
            ImGui::ShowHelp("How far the fall is tilted from straight down: 0 = vertical, 89 = almost sideways.");
            ImGui::Checkbox("Wind relative to camera", &c.wind_camera_relative);
            ImGui::ShowHelp("Measure the wind direction from the camera instead of the world, so the storm keeps the same\non-screen direction as you rotate the camera (e.g. always blowing across the view).");
            if (c.type == kTypeSnow) {
                float drift = EffectiveDrift(c);
                if (ImGui::DragFloat("Drift", &drift, 1.f, 0.f, 1000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp)) c.drift = drift;
                ImGui::ShowHelp("How much flakes wander sideways as they float down. 0 = fall straight (e.g. sandstorm).");
            }
            const char* decal_names[kDecalCount] = {"None", "Splash", "Settle"};
            int decal = EffectiveDecal(c);
            if (ImGui::Combo("Floor decal", &decal, decal_names, kDecalCount)) c.floor_decal = decal;
            ImGui::ShowHelp("What each impact leaves on the ground: nothing, a water splash, or a settled flake/patch.");
            if (decal == kDecalSplash) ImGui::DragFloat("Splash chance", &c.splash_chance, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
            auto ct = ImGui::ColorConvertU32ToFloat4(c.tint);
            if (ImGui::ColorEdit4("Tint", &ct.x, ImGuiColorEditFlags_AlphaBar)) c.tint = ImGui::ColorConvertFloat4ToU32(ct);
            ImGui::ShowHelp("This condition's particle colour - e.g. a dark grey for ashfall.");
            ImGui::DragFloat("Overcast", &c.ambient, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
            ImGui::ShowHelp("How strongly this condition dims the scene toward its overcast tint while active.");
            auto oc = ImGui::ColorConvertU32ToFloat4(c.overcast_tint);
            if (ImGui::ColorEdit3("Overcast tint", &oc.x)) c.overcast_tint = ImGui::ColorConvertFloat4ToU32(oc);
            ImGui::ShowHelp("The colour the scene is dimmed toward while this condition drives the overcast.");

            ImGui::TextUnformatted("Sounds (file id, played at random while active)");
            int snd_remove = -1;
            for (int s = 0; s < static_cast<int>(c.sounds.size()); s++) {
                ImGui::PushID(s);
                ImGui::SetNextItemWidth(120.f);
                ImGui::InputScalar("##sid", ImGuiDataType_U32, &c.sounds[s], nullptr, nullptr, "%X", ImGuiInputTextFlags_CharsHexadecimal);
                const bool ok = IsValidSound(c.sounds[s]);
                ImGui::SameLine();
                ImGui::TextColored(ok ? green : red, ok ? ICON_FA_CHECK : ICON_FA_TIMES);
                ImGui::SameLine();
                if (ImGui::SmallButton("Test")) AudioSettings::PlaySoundFileId(c.sounds[s]);
                ImGui::SameLine();
                if (ImGui::SmallButton("Remove##snd")) snd_remove = s;
                ImGui::PopID();
            }
            if (snd_remove >= 0) c.sounds.erase(c.sounds.begin() + snd_remove);
            if (ImGui::SmallButton("Add sound")) c.sounds.push_back(0);
            ImGui::DragFloat2("Sound interval (s)", &c.sound_min_interval, 0.5f, 0.f, 600.f, "%.0f");
            ImGui::Checkbox("Play sounds in 3D", &c.sound_3d);
            ImGui::ShowHelp("Play each sound from a random nearby position so the game's 3D audio varies its\nvolume and stereo panning - reduces repetition when there's only one sound.\nNo effect if the sound isn't a positional one.");

            if (ImGui::Button("Duplicate")) to_duplicate = i;
            ImGui::SameLine();
            if (ImGui::Button("Remove condition")) to_remove = i;
        }
        ImGui::PopID();
    }
    if (to_remove >= 0) {
        conditions.erase(conditions.begin() + to_remove);
        active_particles = {};  // free the live buffer and let SyncWeather re-resolve (indices shifted)
        active_condition = -1;
    }
    if (to_duplicate >= 0) {
        WeatherCondition copy = conditions[to_duplicate]; // copy first: insert may reallocate the vector
        copy.name += " copy";
        copy.active = false; // single-active: the duplicate starts off
        conditions.insert(conditions.begin() + to_duplicate + 1, std::move(copy));
    }

    if (ImGui::Button("Add condition")) conditions.push_back({});
    ImGui::SameLine();
    if (ImGui::Button("Reset to defaults")) ImGui::OpenPopup("Reset weather conditions?");
    if (ImGui::BeginPopupModal("Reset weather conditions?", nullptr, ImGuiWindowFlags_AlwaysAutoResize)) {
        ImGui::Text("Replace all conditions with the %d defaults?", static_cast<int>(DefaultConditions().size()));
        if (ImGui::Button("Reset")) {
            conditions = DefaultConditions();
            active_particles = {};
            active_condition = -1;
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("Cancel")) ImGui::CloseCurrentPopup();
        ImGui::EndPopup();
    }

    ImGui::Separator();
    if (ImGui::Checkbox("Automatic weather (by climate)", &auto_weather) && auto_weather) auto_timer = -1.f; // roll at once on enable
    ImGui::ShowHelp("Choose the active weather automatically from the table below, based on the climate of the region\nyou're in, re-rolling every few minutes. While on, the manual on/off toggles above are disabled.");
    if (auto_weather) // two separate globals (not a contiguous pair), so DragFloatRange2's two pointers - not DragFloat2
        ImGui::DragFloatRange2("Change interval (min)", &auto_change_min, &auto_change_max, 0.25f, 0.1f, 240.f, "%.1f", "%.1f", ImGuiSliderFlags_AlwaysClamp);

    ImGui::PushID("climates"); // keep these widget ids from colliding with the conditions loop above
    int climate_remove = -1;
    for (int i = 0; i < static_cast<int>(climate_profiles.size()); i++) {
        auto& cp = climate_profiles[i];
        ImGui::PushID(i);
        if (ImGui::CollapsingHeader(ClimateName(cp.climate))) {
            int ent_remove = -1;
            for (int e = 0; e < static_cast<int>(cp.entries.size()); e++) {
                ImGui::PushID(e);
                ImGui::SetNextItemWidth(160.f);
                if (ImGui::BeginCombo("##cond", cp.entries[e].condition.c_str())) {
                    for (const auto& c : conditions)
                        if (ImGui::Selectable(c.name.c_str(), c.name == cp.entries[e].condition)) cp.entries[e].condition = c.name;
                    ImGui::EndCombo();
                }
                ImGui::SameLine();
                ImGui::SetNextItemWidth(110.f);
                ImGui::DragFloat("##weight", &cp.entries[e].weight, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
                ImGui::SameLine();
                if (ImGui::SmallButton("Remove##ent")) ent_remove = e;
                ImGui::PopID();
            }
            if (ent_remove >= 0) cp.entries.erase(cp.entries.begin() + ent_remove);
            if (ImGui::SmallButton("Add condition##ent")) cp.entries.push_back({conditions.empty() ? "" : conditions.front().name, 0.3f});
            float sum = 0.f;
            for (const auto& e : cp.entries) sum += std::max(0.f, e.weight);
            ImGui::Text("Clear weather: %.0f%%", std::max(0.f, 1.f - sum) * 100.f);
            if (ImGui::Button("Remove climate")) climate_remove = i;
        }
        ImGui::PopID();
    }
    if (climate_remove >= 0) climate_profiles.erase(climate_profiles.begin() + climate_remove);

    if (ImGui::Button("Add climate")) ImGui::OpenPopup("add_climate");
    if (ImGui::BeginPopup("add_climate")) {
        for (const auto& k : kClimates) {
            if (std::any_of(climate_profiles.begin(), climate_profiles.end(), [&](const ClimateProfile& cp) { return cp.climate == k.climate; })) continue;
            if (ImGui::Selectable(k.name)) climate_profiles.push_back({k.climate, {}});
        }
        ImGui::EndPopup();
    }
    ImGui::SameLine();
    if (ImGui::Button("Reset climate table")) climate_profiles = DefaultClimateProfiles();
    ImGui::PopID();
}

void WeatherModule::Reset()
{
    reset_requested = true; // consumed by SyncWeather on the next update (clears particles -> reseed fresh)
}

void WeatherModule::Initialize()
{
    ToolboxModule::Initialize();
    RegisterSettings(this);
    if (!compositor_token) compositor_token = GameWorldCompositor::RegisterDraw(&WeatherModule::DrawInWorld);
    GW::Chat::CreateCommand(&chat_hook_entry, L"weather", CmdWeather);
}

void WeatherModule::DrawSettingsInternal()
{
    DrawSettings();
}

void WeatherModule::SignalTerminate()
{
    if (compositor_token) {
        GameWorldCompositor::UnregisterDraw(compositor_token);
        compositor_token = 0;
    }
    GW::Chat::DeleteCommand(&chat_hook_entry);
}

void WeatherModule::Terminate()
{
    SignalTerminate();
    for (auto** p : {&rain_inst_vb, &snow_vb, &splash_vb, &quad_geom_vb})
        if (*p) {
            (*p)->Release();
            *p = nullptr;
        }
    if (quad_ib) {
        quad_ib->Release();
        quad_ib = nullptr;
    }
    for (auto** s : {&weather_vs, &weather_inst_vs})
        if (*s) {
            (*s)->Release();
            *s = nullptr;
        }
    if (weather_ps) {
        weather_ps->Release();
        weather_ps = nullptr;
    }
    for (auto** d : {&weather_decl, &weather_inst_decl})
        if (*d) {
            (*d)->Release();
            *d = nullptr;
        }
    rain_inst_cap = snow_cap = splash_cap = quad_ib_quads = 0;
    active_particles = {};
    active_condition = -1;
    raindrop_tex_pp = snowflake_tex_pp = splash_tex_pp = nullptr; // owned by GwDatTextureModule's cache
    textures_requested = false;
    last_update = 0;
    auto_climate = Climate::Temperate;
    auto_timer = -1.f;
    ToolboxModule::Terminate();
}
