#include "stdafx.h"

#include <GWCA/GameContainers/GamePos.h>
#include <GWCA/GameEntities/Camera.h>
#include <GWCA/Managers/CameraMgr.h>
#include <GWCA/Managers/ChatMgr.h>
#include <GWCA/Managers/MapMgr.h>

#include <Color.h>
#include <Defines.h>
#include <ImGuiAddons.h>
#include <Logger.h>
#include <Timer.h>
#include <Modules/AudioSettings.h>
#include <Modules/GwDatTextureModule.h>
#include <Modules/WeatherModule.h>
#include <Utils/ArenaNetFileParser.h>
#include <Utils/GameWorldCompositor.h>
#include <Utils/SettingsDoc.h>
#include <Utils/SettingsRegistry.h>
#include <Utils/TextUtils.h>

// Generated by CMake (fxc) from the .hlsl in the shared shaders dir.
#include "Widgets/Minimap/Shaders/weather_billboard_ps.h"
#include "Widgets/Minimap/Shaders/weather_billboard_vs.h"
#include "Widgets/Minimap/Shaders/weather_instanced_vs.h"

// External linkage (not the anonymous namespace) so glaze can reflect it as a vector element when
// (de)serialising the conditions list. A plain aggregate so reflection works without a glz::meta.
namespace weather_module {
    constexpr int kTypeRain = 0; // weather type
    constexpr int kTypeSnow = 1;
    constexpr int kTypeCount = 2;

    struct WeatherCondition {
        std::string name = "Rain";
        int type = kTypeRain;
        bool active = false;
        int drop_count = 1000;
        float drop_size = 8.f;
        float fall_speed = 2000.f;    // gwinch/sec
        float spread_radius = 2500.f; // horizontal half-extent of the volume; fixed (forced on load, no UI)
        float wind_x = 0.f, wind_y = 0.f;
        float splash_chance = 1.f;      // 0..1 chance an impact spawns a splash
        std::vector<uint32_t> sounds;   // .dat sound file ids played at random while active
        float sound_min_interval = 8.f; // seconds between sounds
        float sound_max_interval = 25.f;
        bool sound_3d = false;  // play from a random nearby position (varies volume/pan)
        float ambient = 0.f;    // 0..1 overcast dimming this condition contributes to the scene
    };
} // namespace weather_module

namespace {
    using namespace weather_module;

    // Game weather assets in the .dat: a 32px raindrop, a 32px snowflake, and a 128x128 splash sheet (4x4 keyframes).
    constexpr uint32_t kRaindropFileId = 0x1997d;
    constexpr uint32_t kSnowflakeFileId = 0xca1a;
    constexpr uint32_t kSplashFileId = 0x1baa1;
    constexpr int kSplashCols = 4, kSplashRows = 4, kSplashFrames = kSplashCols * kSplashRows;
    constexpr float kZNear = 47.0f, kZFar = 100000.f; // must match GW's projection for occlusion to line up
    constexpr float kMaxRadius = 2500.f;              // compass range; cap for any radius in the UI

    // Fixed in code (deliberately not in the UI, but handy to tweak while debugging).
    float column_height = 2500.f; // vertical span drops fall through
    float fog_factor = 1.0f;      // distance-fade strength fed to the shader
    float splash_size = 8.f;      // world size of a splash billboard
    float splash_duration = 0.5f; // seconds to play the 16 keyframes
    float recycle_below = 600.f;  // fallback recycle band when no terrain altitude is available
    float splash_lift = 5.f;      // raise splash base above the ground to avoid z-fighting
    int max_splashes = 4000;      // per-condition cap on live splashes
    float snow_sway_speed = 1.5f;     // radians/sec of snow's lateral wobble
    float snow_sway_amp = 120.f;      // gwinch/sec horizontal sway velocity (positional amplitude = amp / speed)
    float snow_settle_chance = 0.15f; // fraction of landed flakes that leave a lingering patch
    float snow_settle_size = 14.f;    // world size of a settled flake billboard
    float snow_settle_duration = 4.f; // seconds a settled flake holds before it has fully faded
    float snow_settle_fade = 0.4f;    // last fraction of the lifetime spent fading out
    int max_settled = 4000;           // per-condition cap on settled flakes

    constexpr bool HasSplash(const int type)
    {
        return type == kTypeRain;
    }
    constexpr bool HasMeander(const int type)
    {
        return type == kTypeSnow;
    }
    constexpr bool HasSettle(const int type)
    {
        return type == kTypeSnow;
    }

    std::vector<WeatherCondition> DefaultConditions()
    {
        return {
            {"Heavy Rain", kTypeRain, false, 4000, 10.f, 1000.f, 2500.f, 0.f, 0.f, 0.30f, {0x20ed0, 0x20ed1}, 6.f, 60.f, false, 0.50f},
            {"Light Rain", kTypeRain, false, 300, 8.f, 1600.f, 2500.f, 0.f, 0.f, 0.30f, {0x20ed0, 0x20ed1}, 6.f, 60.f, false, 0.20f},
            {"Snow", kTypeSnow, false, 1500, 8.f, 400.f, 2500.f, 40.f, 40.f, 0.f, {}, 10.f, 30.f, false, 0.30f},
        };
    }
    std::vector<WeatherCondition> conditions = DefaultConditions();

    bool occlude_behind_terrain = true;
    float render_max_distance = 2500.f;
    unsigned int rain_color = 0xFFFFFFFFu;     // tint (ImGui-packed); white shows the texture untinted
    unsigned int ambient_color = 0xFFA09078u;  // fully-overcast multiply tint (ImGui-packed RGB; alpha ignored)
    float ambient_strength = 0.f;              // eased aggregate dimming of active conditions (runtime, not saved)

    // POSITION (world) + D3DCOLOR tint + UV; quads are built camera-/ground-aligned on the CPU.
    struct WeatherVertex {
        float x, y, z;
        DWORD color;
        float u, v;
    };
    struct Raindrop {
        float x, y, z, ground_z, sway_phase;
    }; // falls in +z (GW up is -z); ground_z queried at seed time; sway_phase drives snow's lateral wander
    struct Splash {
        float x, y, z, age;
    };
    struct Settle {
        float x, y, z, age;
    }; // a snowflake lying flat on the ground; ages out with an alpha fade
    struct Particles {
        std::vector<Raindrop> raindrops;
        std::vector<Splash> splashes;
        std::vector<Settle> settled;
        float sound_timer = -1.f; // seconds until the next sound; <0 = not yet scheduled
    };
    std::vector<Particles> particles; // runtime state, parallel to conditions (not saved)

    // Rain is GPU-instanced: one record per drop (centre + the two half-extent axes), expanded to a quad
    // by weather_instanced_vs. Snow/splash/settle keep the CPU-built indexed-quad path (per-instance UV
    // animation and alpha fade don't fit the simple instance record).
    struct WeatherInstance {
        float cx, cy, cz;
        float ax0, ax1, ax2;
        float ay0, ay1, ay2;
    };
    struct GeomVert {
        float sx, sy, u, v;
    }; // static unit quad: corner sign + uv

    std::vector<WeatherInstance> rain_instances;
    std::vector<WeatherVertex> snow_vertices, splash_vertices;
    IDirect3DVertexBuffer9 *rain_inst_vb = nullptr, *snow_vb = nullptr, *splash_vb = nullptr;
    IDirect3DVertexBuffer9* quad_geom_vb = nullptr; // shared unit quad (stream 0 for instancing)
    size_t rain_inst_cap = 0;                       // bytes
    size_t snow_cap = 0, splash_cap = 0;            // in vertices
    IDirect3DIndexBuffer9* quad_ib = nullptr;       // shared 0-1-2 / 0-2-3 indices for every 4-vertex quad
    size_t quad_ib_quads = 0;                       // capacity in quads
    IDirect3DVertexShader9* weather_vs = nullptr;
    IDirect3DVertexShader9* weather_inst_vs = nullptr;
    IDirect3DPixelShader9* weather_ps = nullptr;
    IDirect3DVertexDeclaration9* weather_decl = nullptr;
    IDirect3DVertexDeclaration9* weather_inst_decl = nullptr;
    IDirect3DTexture9 **raindrop_tex_pp = nullptr, **snowflake_tex_pp = nullptr, **splash_tex_pp = nullptr; // stable slots from the texture cache
    bool textures_requested = false;
    clock_t last_update = 0;                   // TIMER_INIT() at the last throttled update (0 = not yet run)
    constexpr clock_t kUpdateIntervalMs = 16;  // rebuild physics + geometry at ~60 Hz; drawing stays per-frame
    uint32_t rng = 0x1234567u;
    bool rain_ready = false, snow_ready = false, splash_ready = false;
    int compositor_token = 0;
    GW::HookEntry chat_hook_entry;

    float frand(const float lo, const float hi)
    {
        rng = rng * 1664525u + 1013904223u;
        return lo + static_cast<float>(rng >> 8) / static_cast<float>(0xFFFFFFu) * (hi - lo);
    }

    void cross3(const float a[3], const float b[3], float o[3])
    {
        o[0] = a[1] * b[2] - a[2] * b[1];
        o[1] = a[2] * b[0] - a[0] * b[2];
        o[2] = a[0] * b[1] - a[1] * b[0];
    }

    void normalize3(float v[3])
    {
        const float l = std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
        if (l > 1e-6f) {
            v[0] /= l;
            v[1] /= l;
            v[2] /= l;
        }
    }

    constexpr float kNoGround = std::numeric_limits<float>::max(); // "no terrain here" sentinel
    constexpr float kGroundCell = 64.f;               // world-grid resolution of the altitude cache (gwinch)
    constexpr size_t kGroundCacheMax = 1u << 16;      // entry cap; cleared wholesale past this
    std::unordered_map<uint64_t, float> ground_cache; // (x,y) cell -> terrain altitude, valid within a map
    uint32_t ground_cache_map = 0xFFFFFFFFu;          // map id the cache was built for

    // Highest terrain surface at (x,y) over all planes (GW up is -z, so highest = min altitude), or kNoGround.
    float RawGroundZAt(const float x, const float y)
    {
        const GW::PathingMapArray* pm = GW::Map::GetPathingMap();
        const uint32_t n = pm ? static_cast<uint32_t>(pm->size()) : 0;
        float best = kNoGround;
        for (uint32_t zp = 0; zp < n; ++zp) {
            GW::GamePos p{x, y, zp};
            const float a = GW::Map::QueryAltitude(&p);
            if (a != 0.f && a < best) best = a;
        }
        return best;
    }

    // Memoised by a coarse world cell: terrain is static per (x,y), but the per-plane query is costly and we
    // sample it for every drop that lands, so nearby drops reuse a cell. Invalidated on map change in SyncWeather.
    float GroundZAt(const float x, const float y, const float fallback)
    {
        const int gx = static_cast<int>(std::floor(x / kGroundCell));
        const int gy = static_cast<int>(std::floor(y / kGroundCell));
        const uint64_t key = static_cast<uint64_t>(static_cast<uint32_t>(gx)) << 32 | static_cast<uint32_t>(gy);
        if (const auto it = ground_cache.find(key); it != ground_cache.end()) return it->second == kNoGround ? fallback : it->second;
        const float z = RawGroundZAt(x, y);
        if (z != kNoGround) { // don't cache misses: they're rare (drops over the void) and risk poisoning on transient null maps
            if (ground_cache.size() >= kGroundCacheMax) ground_cache.clear();
            ground_cache.emplace(key, z);
        }
        return z == kNoGround ? fallback : z;
    }

    // A .dat file is a sound if its type bytes look like an ANet/MP3 stream (mirrors FavorTracker).
    bool IsValidSound(const uint32_t id)
    {
        static std::map<uint32_t, bool> cache;
        if (!id) return false;
        if (const auto it = cache.find(id); it != cache.end()) return it->second;
        ArenaNetFileParser::GameAssetFile f;
        f.readFromDat(id);
        const char* ft = f.fileType();
        const bool ok = f.file_id == id && ft && static_cast<unsigned char>(ft[0]) == 0xFF && (static_cast<unsigned char>(ft[1]) & 0xE6) == 0xE2;
        cache[id] = ok;
        return ok;
    }

    void UpdateSounds(const WeatherCondition& c, Particles& p, const float dt, const float cx, const float cy, const float cz)
    {
        if (c.sounds.empty() || c.sound_max_interval <= 0.f) return;
        if (p.sound_timer < 0.f) { // first active frame: schedule, don't play immediately
            p.sound_timer = frand(c.sound_min_interval, c.sound_max_interval);
            return;
        }
        if ((p.sound_timer -= dt) > 0.f) return;
        const size_t idx = std::min(c.sounds.size() - 1, static_cast<size_t>(frand(0.f, static_cast<float>(c.sounds.size()))));
        if (c.sounds[idx]) {
            // PlaySound marshals to the game thread itself, so calling from here is safe.
            if (c.sound_3d) {
                const float ang = frand(0.f, 6.2831853f), dist = frand(200.f, 1500.f);
                const GW::Vec3f pos{cx + dist * std::cos(ang), cy + dist * std::sin(ang), cz - frand(0.f, 1000.f)};
                AudioSettings::PlaySoundFileId(c.sounds[idx], &pos);
            }
            else {
                AudioSettings::PlaySoundFileId(c.sounds[idx]);
            }
        }
        p.sound_timer = frand(c.sound_min_interval, c.sound_max_interval);
    }

    // Side count of the square grid that tiles the spawn area for stratified placement.
    int SpawnGrid(const int drop_count) { return std::max(1, static_cast<int>(std::ceil(std::sqrt(static_cast<float>(std::max(1, drop_count)))))); }

    void seed_drop(Raindrop& d, const WeatherCondition& c, const float cx, const float cy, const float cz, const bool randomize, const int index, const int grid)
    {
        const float top_z = cz - column_height;
        // Stratified placement: each drop owns one cell of the grid, jittered within it, so its landing spot is
        // evenly spread over the area around the player instead of clumping the way random positions do.
        const float cell = 2.f * c.spread_radius / static_cast<float>(grid);
        const float base_x = cx - c.spread_radius + (static_cast<float>(index % grid) + frand(0.f, 1.f)) * cell;
        const float base_y = cy - c.spread_radius + (static_cast<float>(index / grid) + frand(0.f, 1.f)) * cell;
        d.ground_z = GroundZAt(base_x, base_y, cz + recycle_below);
        // Spread the initial fill only through the visible column (top..ground). Seeding past the ground would
        // make every below-ground drop recycle together on the first frame and then fall as a synchronised
        // "lump" once per cycle - very visible at high drop counts.
        d.z = randomize ? top_z + frand(0.f, std::max(0.f, d.ground_z - top_z)) : top_z;
        // Tilt the whole column about its landing point so wind angles the fall but it still lands on base_xy
        // (around the player), instead of shearing the impact zone downwind into a "trapeze". bias is the time
        // left until landing, negated: 0 at the ground, -t_fall at the top, so the drop starts upwind and
        // converges to base_xy as it descends.
        const float inv_speed = c.fall_speed > 0.f ? 1.f / c.fall_speed : 0.f;
        const float bias = (d.z - d.ground_z) * inv_speed;
        d.x = base_x + c.wind_x * bias;
        d.y = base_y + c.wind_y * bias;
        d.sway_phase = frand(0.f, 6.2831853f);
    }

    void UpdateCondition(const WeatherCondition& c, Particles& p, const float dt, const float cx, const float cy, const float cz)
    {
        const int grid = SpawnGrid(c.drop_count);
        if (static_cast<int>(p.raindrops.size()) != c.drop_count) {
            p.raindrops.resize(std::max(0, c.drop_count));
            for (int i = 0; i < static_cast<int>(p.raindrops.size()); i++)
                seed_drop(p.raindrops[i], c, cx, cy, cz, true, i, grid);
        }
        const bool splash = HasSplash(c.type);
        const bool meander = HasMeander(c.type);
        const bool settle = HasSettle(c.type);
        const float spread_sq = c.spread_radius * c.spread_radius;
        for (int i = 0; i < static_cast<int>(p.raindrops.size()); i++) {
            auto& d = p.raindrops[i];
            d.z += c.fall_speed * dt;
            // Snow drifts on an out-of-phase sin/cos wobble so each flake wanders rather than falling in a line.
            const float sway_x = meander ? snow_sway_amp * std::sin(d.sway_phase) : 0.f;
            const float sway_y = meander ? snow_sway_amp * std::cos(d.sway_phase) : 0.f;
            d.sway_phase += snow_sway_speed * dt;
            d.x += (c.wind_x + sway_x) * dt;
            d.y += (c.wind_y + sway_y) * dt;
            // Harsh wind/sway can carry a drop out of the radius before it ever lands near the player; once it is
            // outside and still heading out (so upwind, inbound spawns are spared) it can never contribute, so
            // recycle it now rather than rendering it falling off into the distance.
            const float dx = d.x - cx, dy = d.y - cy;
            if (dx * dx + dy * dy > spread_sq && dx * (c.wind_x + sway_x) + dy * (c.wind_y + sway_y) > 0.f) {
                seed_drop(d, c, cx, cy, cz, false, i, grid);
                continue;
            }
            if (d.z >= d.ground_z) {
                // d.ground_z is the terrain height at the spawn point; wind/sway drift the drop sideways as it
                // falls, so resample under where it actually lands - otherwise the mark sits above/below the
                // real surface. The cache keeps this cheap despite running per impact.
                if (splash && frand(0.f, 1.f) < c.splash_chance && static_cast<int>(p.splashes.size()) < max_splashes) p.splashes.push_back({d.x, d.y, GroundZAt(d.x, d.y, d.ground_z), 0.f});
                if (settle && frand(0.f, 1.f) < snow_settle_chance && static_cast<int>(p.settled.size()) < max_settled) p.settled.push_back({d.x, d.y, GroundZAt(d.x, d.y, d.ground_z), 0.f});
                seed_drop(d, c, cx, cy, cz, false, i, grid);
            }
        }
        for (size_t i = 0; i < p.splashes.size();) {
            if ((p.splashes[i].age += dt) >= splash_duration) {
                p.splashes[i] = p.splashes.back();
                p.splashes.pop_back();
            }
            else
                ++i;
        }
        for (size_t i = 0; i < p.settled.size();) {
            if ((p.settled[i].age += dt) >= snow_settle_duration) {
                p.settled[i] = p.settled.back();
                p.settled.pop_back();
            }
            else
                ++i;
        }
    }

    // The 4 corners of a quad spanning center +/- the half-extent vectors ax, ay, with the given UV rect.
    // Drawn as two triangles (0-1-2, 0-2-3) via the shared index buffer, so only 4 verts are stored per quad.
    void emit_quad(std::vector<WeatherVertex>& out, const float cx, const float cy, const float cz, const float ax[3], const float ay[3], const DWORD col, const float u0, const float v0, const float u1, const float v1)
    {
        const WeatherVertex c00{cx - ax[0] - ay[0], cy - ax[1] - ay[1], cz - ax[2] - ay[2], col, u0, v1};
        const WeatherVertex c10{cx + ax[0] - ay[0], cy + ax[1] - ay[1], cz + ax[2] - ay[2], col, u1, v1};
        const WeatherVertex c11{cx + ax[0] + ay[0], cy + ax[1] + ay[1], cz + ax[2] + ay[2], col, u1, v0};
        const WeatherVertex c01{cx - ax[0] + ay[0], cy - ax[1] + ay[1], cz - ax[2] + ay[2], col, u0, v0};
        out.insert(out.end(), {c00, c10, c11, c01});
    }

    // Snow: camera-aligned square billboards on the CPU indexed path (flakes tumble, no streak).
    void AppendSnow(const WeatherCondition& c, std::vector<WeatherVertex>& out, const std::vector<Raindrop>& drops, const float right[3], const float up[3])
    {
        const float h = c.drop_size * 0.5f;
        const float ax[3] = {right[0] * h, right[1] * h, right[2] * h};
        const float ay[3] = {up[0] * h, up[1] * h, up[2] * h};
        for (const auto& d : drops)
            emit_quad(out, d.x, d.y, d.z, ax, ay, rain_color, 0.f, 0.f, 1.f, 1.f);
    }

    // Rain: one instance record per drop. Streak axes (long axis along the downward velocity, width axis
    // facing the camera) are constant per condition, so they are baked into every record; the GPU expands
    // the quad. The instanced VS applies the V-flip so the texture stays upright.
    void AppendRainInstances(std::vector<WeatherInstance>& out, const WeatherCondition& c, const std::vector<Raindrop>& drops, const float right[3], const float fwd[3])
    {
        const float h = c.drop_size * 0.5f;
        float vel[3] = {c.wind_x, c.wind_y, c.fall_speed};
        normalize3(vel);
        float w[3];
        cross3(vel, fwd, w);
        const float wl = std::sqrt(w[0] * w[0] + w[1] * w[1] + w[2] * w[2]);
        if (wl > 1e-4f) {
            w[0] /= wl;
            w[1] /= wl;
            w[2] /= wl;
        }
        else {
            w[0] = right[0];
            w[1] = right[1];
            w[2] = right[2];
        }
        const WeatherInstance base{0.f, 0.f, 0.f, w[0] * h, w[1] * h, w[2] * h, vel[0] * h, vel[1] * h, vel[2] * h};
        out.reserve(out.size() + drops.size());
        for (const auto& d : drops) {
            WeatherInstance inst = base;
            inst.cx = d.x;
            inst.cy = d.y;
            inst.cz = d.z;
            out.push_back(inst);
        }
    }

    // Vertical billboard standing on the ground: horizontal axis follows the camera so it faces the
    // viewer, vertical axis is world up (-z), anchored so the base sits at the impact point.
    void AppendSplashes(const std::vector<Splash>& s, const float right[3])
    {
        const float hs = splash_size * 0.5f;
        const float ax[3] = {right[0] * hs, right[1] * hs, right[2] * hs};
        const float ay[3] = {0.f, 0.f, -hs};
        const float u_step = 1.f / kSplashCols, v_step = 1.f / kSplashRows;
        for (const auto& sp : s) {
            const int f = std::clamp(static_cast<int>(sp.age / splash_duration * kSplashFrames), 0, kSplashFrames - 1);
            const float u0 = static_cast<float>(f % kSplashCols) * u_step, v0 = static_cast<float>(f / kSplashCols) * v_step;
            emit_quad(splash_vertices, sp.x, sp.y, sp.z - hs - splash_lift, ax, ay, rain_color, u0, v0, u0 + u_step, v0 + v_step);
        }
    }

    // Flat quad lying on the ground (world XY plane) drawn with the snowflake texture, so it shares the
    // snow vertex buffer/pass. Holds at full tint, then fades its alpha out over the tail of its lifetime.
    void AppendSettled(const std::vector<Settle>& s)
    {
        const float hs = snow_settle_size * 0.5f;
        const float ax[3] = {hs, 0.f, 0.f};
        const float ay[3] = {0.f, hs, 0.f};
        const DWORD base_a = (rain_color >> 24) & 0xFFu;
        const float fade_span = std::clamp(snow_settle_fade, 0.01f, 1.f);
        for (const auto& sp : s) {
            const float life = snow_settle_duration > 0.f ? sp.age / snow_settle_duration : 1.f;
            const float fade = life < 1.f - fade_span ? 1.f : std::max(0.f, (1.f - life) / fade_span);
            const DWORD col = (rain_color & 0x00FFFFFFu) | (static_cast<DWORD>(static_cast<float>(base_a) * fade) << 24);
            emit_quad(snow_vertices, sp.x, sp.y, sp.z - splash_lift, ax, ay, col, 0.f, 0.f, 1.f, 1.f);
        }
    }

    // Grow-and-upload a raw byte blob into a write-only managed vertex buffer (used for the instance stream).
    bool UploadVB(IDirect3DDevice9* device, IDirect3DVertexBuffer9*& vb, size_t& cap_bytes, const void* data, const size_t bytes)
    {
        if (bytes == 0) return false;
        if (!vb || cap_bytes < bytes) {
            if (vb) {
                vb->Release();
                vb = nullptr;
            }
            const size_t c = bytes + bytes / 2; // headroom so count tweaks don't reallocate every frame
            if (device->CreateVertexBuffer(static_cast<UINT>(c), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &vb, nullptr) != D3D_OK) {
                cap_bytes = 0;
                return false;
            }
            cap_bytes = c;
        }
        void* mem = nullptr;
        if (vb->Lock(0, static_cast<UINT>(bytes), &mem, 0) != D3D_OK || !mem) return false;
        memcpy(mem, data, bytes);
        vb->Unlock();
        return true;
    }

    bool EnsureVb(IDirect3DDevice9* device, IDirect3DVertexBuffer9*& vb, size_t& cap, const std::vector<WeatherVertex>& verts)
    {
        const size_t needed = verts.size();
        if (needed == 0) return false;
        if (!vb || cap < needed) {
            if (vb) {
                vb->Release();
                vb = nullptr;
            }
            const size_t c = needed + needed / 2; // headroom so count tweaks don't reallocate every frame
            if (device->CreateVertexBuffer(static_cast<UINT>(c * sizeof(WeatherVertex)), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &vb, nullptr) != D3D_OK) {
                cap = 0;
                return false;
            }
            cap = c;
        }
        void* mem = nullptr;
        if (vb->Lock(0, static_cast<UINT>(needed * sizeof(WeatherVertex)), &mem, 0) != D3D_OK || !mem) return false;
        memcpy(mem, verts.data(), needed * sizeof(WeatherVertex));
        vb->Unlock();
        return true;
    }

    // The quad index pattern is static (only the count grows), so build it once and reuse it across all passes.
    bool EnsureQuadIB(IDirect3DDevice9* device, const size_t quads)
    {
        if (quads == 0) return false;
        if (quad_ib && quad_ib_quads >= quads) return true;
        if (quad_ib) {
            quad_ib->Release();
            quad_ib = nullptr;
        }
        const size_t cap = quads + quads / 2; // headroom so count tweaks don't reallocate every frame
        if (device->CreateIndexBuffer(static_cast<UINT>(cap * 6 * sizeof(uint32_t)), D3DUSAGE_WRITEONLY, D3DFMT_INDEX32, D3DPOOL_MANAGED, &quad_ib, nullptr) != D3D_OK) {
            quad_ib_quads = 0;
            return false;
        }
        void* mem = nullptr;
        if (quad_ib->Lock(0, 0, &mem, 0) != D3D_OK || !mem) {
            quad_ib->Release();
            quad_ib = nullptr;
            quad_ib_quads = 0;
            return false;
        }
        auto* idx = static_cast<uint32_t*>(mem);
        for (size_t q = 0; q < cap; q++) {
            const uint32_t b = static_cast<uint32_t>(q * 4);
            idx[q * 6 + 0] = b + 0;
            idx[q * 6 + 1] = b + 1;
            idx[q * 6 + 2] = b + 2;
            idx[q * 6 + 3] = b + 0;
            idx[q * 6 + 4] = b + 2;
            idx[q * 6 + 5] = b + 3;
        }
        quad_ib->Unlock();
        quad_ib_quads = cap;
        return true;
    }

    bool EnsureShaders(IDirect3DDevice9* device)
    {
        if (weather_vs && weather_ps && weather_decl && weather_inst_vs && weather_inst_decl && quad_geom_vb) return true;
        constexpr D3DVERTEXELEMENT9 decl[] = {
            {0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0}, {0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0}, {0, 16, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0}, D3DDECL_END()
        };
        if (!weather_decl && device->CreateVertexDeclaration(decl, &weather_decl) != D3D_OK) return false;
        if (!weather_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&weather_billboard_vs), &weather_vs) != D3D_OK) return false;
        if (!weather_ps && device->CreatePixelShader(reinterpret_cast<const DWORD*>(&weather_billboard_ps), &weather_ps) != D3D_OK) return false;

        // Instanced pipeline: stream 0 = unit quad (POSITION = corner sign, TEXCOORD0 = uv); stream 1 =
        // per-drop instance record (TEXCOORD1 = centre, TEXCOORD2/3 = the two half-extent axes).
        constexpr D3DVERTEXELEMENT9 inst_decl[] = {
            {0, 0, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
            {0, 8, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0},
            {1, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1},
            {1, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 2},
            {1, 24, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 3},
            D3DDECL_END()
        };
        if (!weather_inst_decl && device->CreateVertexDeclaration(inst_decl, &weather_inst_decl) != D3D_OK) return false;
        if (!weather_inst_vs && device->CreateVertexShader(reinterpret_cast<const DWORD*>(&weather_instanced_vs), &weather_inst_vs) != D3D_OK) return false;
        if (!quad_geom_vb) {
            constexpr GeomVert quad[4] = {{-1.f, -1.f, 0.f, 1.f}, {1.f, -1.f, 1.f, 1.f}, {1.f, 1.f, 1.f, 0.f}, {-1.f, 1.f, 0.f, 0.f}};
            if (device->CreateVertexBuffer(sizeof(quad), D3DUSAGE_WRITEONLY, 0, D3DPOOL_MANAGED, &quad_geom_vb, nullptr) != D3D_OK) return false;
            void* mem = nullptr;
            if (quad_geom_vb->Lock(0, 0, &mem, 0) != D3D_OK || !mem) return false;
            memcpy(mem, quad, sizeof(quad));
            quad_geom_vb->Unlock();
        }
        return true;
    }

    // Advance every active condition and accumulate its geometry, then upload once per frame.
    void SyncWeather(IDirect3DDevice9* device, const GW::Camera* cam, const float dt)
    {
        rain_ready = snow_ready = splash_ready = false;
        rain_instances.clear();
        snow_vertices.clear();
        splash_vertices.clear();
        particles.resize(conditions.size());
        if (!cam) return;

        if (const uint32_t map_id = static_cast<uint32_t>(GW::Map::GetMapID()); map_id != ground_cache_map) {
            ground_cache.clear(); // terrain altitudes are per-map; drop them when the map changes
            ground_cache_map = map_id;
            // Drop carried-over particles: their old-map positions and stale ground heights otherwise recycle
            // in waves around the new camera, reforming a dense band. Cleared particles reseed fresh below.
            for (auto& p : particles)
                p = {};
        }

        const float cx = cam->look_at_target.x, cy = cam->look_at_target.y, cz = cam->look_at_target.z;
        float fwd[3] = {cx - cam->position.x, cy - cam->position.y, cz - cam->position.z};
        normalize3(fwd);
        constexpr float world_up[3] = {0.f, 0.f, -1.f};
        float right[3];
        cross3(world_up, fwd, right);
        normalize3(right);
        float up[3];
        cross3(fwd, right, up);

        float ambient_target = 0.f;
        for (size_t i = 0; i < conditions.size(); i++) {
            if (!conditions[i].active) {
                particles[i] = {};
                continue;
            }
            ambient_target = std::max(ambient_target, conditions[i].ambient);
            UpdateCondition(conditions[i], particles[i], dt, cx, cy, cz);
            if (conditions[i].type == kTypeSnow)
                AppendSnow(conditions[i], snow_vertices, particles[i].raindrops, right, up);
            else
                AppendRainInstances(rain_instances, conditions[i], particles[i].raindrops, right, fwd);
            AppendSplashes(particles[i].splashes, right);
            AppendSettled(particles[i].settled);
            UpdateSounds(conditions[i], particles[i], dt, cx, cy, cz);
        }
        ambient_strength += (ambient_target - ambient_strength) * std::clamp(dt * 3.f, 0.f, 1.f); // ease ~1/3 s
        rain_ready = UploadVB(device, rain_inst_vb, rain_inst_cap, rain_instances.data(), rain_instances.size() * sizeof(WeatherInstance));
        snow_ready = EnsureVb(device, snow_vb, snow_cap, snow_vertices);
        splash_ready = EnsureVb(device, splash_vb, splash_cap, splash_vertices);
    }

    // Overcast: multiply-blend a screen-filling quad UNDER the HUD so the scene dims like cloud cover.
    void DrawAmbient(IDirect3DDevice9* device, const float strength)
    {
        const GW::Camera* cam = GW::CameraMgr::GetCamera();
        if (!cam || strength <= 0.003f) return;

        // Per channel: scale the scene toward the tint by strength (white = untouched), then multiply-blend.
        const auto t = ImGui::ColorConvertU32ToFloat4(ambient_color);
        const auto chan = [&](const float c) { return static_cast<DWORD>(std::clamp(1.f - strength * (1.f - c), 0.f, 1.f) * 255.f + 0.5f); };
        const DWORD col = D3DCOLOR_ARGB(255, chan(t.x), chan(t.y), chan(t.z));

        float fwd[3] = {cam->look_at_target.x - cam->position.x, cam->look_at_target.y - cam->position.y, cam->look_at_target.z - cam->position.z};
        normalize3(fwd);
        constexpr float world_up[3] = {0.f, 0.f, -1.f};
        float right[3];
        cross3(world_up, fwd, right);
        normalize3(right);
        float up[3];
        cross3(fwd, right, up);

        const float d = kZNear + 1.f, hw = d * 4.f; // sit just past the near plane, oversized to cover any FOV
        const float qx = cam->position.x + fwd[0] * d, qy = cam->position.y + fwd[1] * d, qz = cam->position.z + fwd[2] * d;
        struct ColVtx {
            float x, y, z;
            DWORD c;
        };
        const auto corner = [&](const float sx, const float sy) -> ColVtx {
            return {qx + (right[0] * sx + up[0] * sy) * hw, qy + (right[1] * sx + up[1] * sy) * hw, qz + (right[2] * sx + up[2] * sy) * hw, col};
        };
        const ColVtx q[6] = {corner(-1, -1), corner(1, -1), corner(1, 1), corner(-1, -1), corner(1, 1), corner(-1, 1)};

        IDirect3DStateBlock9* sb = nullptr;
        if (device->CreateStateBlock(D3DSBT_ALL, &sb) != D3D_OK) return;
        if (GameWorldCompositor::SetupPipeline(device, false, kZNear, kZFar, kZFar, 0.f)) {
            device->SetRenderState(D3DRS_ZENABLE, FALSE);
            device->SetRenderState(D3DRS_ZWRITEENABLE, FALSE); // must not touch the depth buffer or it culls the scene/particles
            device->SetRenderState(D3DRS_ALPHABLENDENABLE, TRUE);
            device->SetRenderState(D3DRS_SRCBLEND, D3DBLEND_DESTCOLOR); // result = scene * quad colour (multiply)
            device->SetRenderState(D3DRS_DESTBLEND, D3DBLEND_ZERO);
            device->DrawPrimitiveUP(D3DPT_TRIANGLELIST, 2, q, sizeof(ColVtx));
        }
        sb->Apply();
        sb->Release();
    }

    // /weather <condition name> [on|off|toggle|1|0] - toggle a condition by name (names may be multi-word).
    void CHAT_CMD_FUNC(CmdWeather)
    {
        if (argc < 2) {
            Log::Info("Weather conditions:");
            for (const auto& c : conditions)
                Log::Info("  %s: %s", c.name.c_str(), c.active ? "on" : "off");
            Log::Info("Usage: /weather <condition> [on|off|toggle]");
            return;
        }
        // The trailing word, if it is a state keyword, sets the state; otherwise the whole tail is the name and
        // the command toggles. Names can contain spaces, so join everything that is not the state word.
        const std::string last = TextUtils::ToLower(TextUtils::WStringToString(argv[argc - 1]));
        int state = -1; // -1 unset, 0 off, 1 on, 2 toggle
        if (last == "on" || last == "1") state = 1;
        else if (last == "off" || last == "0") state = 0;
        else if (last == "toggle") state = 2;
        const int name_end = state < 0 ? argc : argc - 1;
        std::string name;
        for (int i = 1; i < name_end; i++) {
            if (i > 1) name += ' ';
            name += TextUtils::WStringToString(argv[i]);
        }
        if (name.empty()) return Log::Error("Usage: /weather <condition> [on|off|toggle]");
        if (state < 0) state = 2; // no explicit state given -> toggle

        const std::string want = TextUtils::ToLower(name);
        bool found = false;
        for (auto& c : conditions) {
            if (TextUtils::ToLower(c.name) != want) continue;
            c.active = state == 2 ? !c.active : state == 1;
            Log::Info("%s: %s", c.name.c_str(), c.active ? "on" : "off");
            found = true;
        }
        if (!found) Log::Error("No weather condition named '%s'", name.c_str());
    }
} // namespace

void WeatherModule::DrawInWorld(IDirect3DDevice9* device)
{
    if (!textures_requested) {
        raindrop_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kRaindropFileId);
        snowflake_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kSnowflakeFileId);
        splash_tex_pp = GwDatTextureModule::LoadTextureFromFileId(kSplashFileId);
        textures_requested = true;
    }

    // Throttle the physics + geometry rebuild to ~30 Hz; the cached vertex buffers are still drawn every
    // frame below, so motion advances in 30 Hz steps (with the full elapsed dt) while rendering stays smooth.
    if (!last_update || TIMER_DIFF(last_update) >= kUpdateIntervalMs) {
        const float dt = last_update ? std::clamp(static_cast<float>(TIMER_DIFF(last_update)) / 1000.f, 0.f, 0.1f) : 0.f;
        last_update = TIMER_INIT();
        SyncWeather(device, GW::CameraMgr::GetCamera(), dt);
    }

    DrawAmbient(device, ambient_strength); // dim the scene first, so the particles stay bright on top

    IDirect3DTexture9* rain_tex = raindrop_tex_pp ? *raindrop_tex_pp : nullptr;
    IDirect3DTexture9* snow_tex = snowflake_tex_pp ? *snowflake_tex_pp : nullptr;
    IDirect3DTexture9* splash_tex = splash_tex_pp ? *splash_tex_pp : nullptr;
    const bool have_rain = rain_ready && rain_tex && !rain_instances.empty();
    const bool have_snow = snow_ready && snow_tex && !snow_vertices.empty();
    const bool have_splash = splash_ready && splash_tex && !splash_vertices.empty();
    if ((!have_rain && !have_snow && !have_splash) || !EnsureShaders(device)) return;

    IDirect3DStateBlock9* state_block = nullptr; // restored on exit so GW's own rendering isn't corrupted
    if (device->CreateStateBlock(D3DSBT_ALL, &state_block) != D3D_OK) return;
    if (device->SetPixelShader(weather_ps) == D3D_OK && GameWorldCompositor::SetWorldViewProj(device, kZNear, kZFar)) {
        GameWorldCompositor::SetWorldRenderStates(device, occlude_behind_terrain);
        GameWorldCompositor::SetDistanceFog(device, render_max_distance, fog_factor);
        device->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_LINEAR);
        device->SetSamplerState(0, D3DSAMP_ADDRESSU, D3DTADDRESS_CLAMP);
        device->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP);
        // One shared index buffer serves both passes: the instanced pass only needs its first quad's 6 indices.
        const size_t indexed_verts = std::max(snow_vertices.size(), splash_vertices.size());
        const bool ib_ok = EnsureQuadIB(device, std::max<size_t>(indexed_verts / 4, 1)) && device->SetIndices(quad_ib) == D3D_OK;

        // Indexed pass: snow flakes + settle (snow_tex) and splashes (splash_tex), CPU-built 4-vert quads.
        if (ib_ok && device->SetVertexShader(weather_vs) == D3D_OK && device->SetVertexDeclaration(weather_decl) == D3D_OK) {
            const auto draw = [&](IDirect3DVertexBuffer9* vb, const size_t nverts) {
                if (device->SetStreamSource(0, vb, 0, sizeof(WeatherVertex)) != D3D_OK) return;
                device->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, static_cast<UINT>(nverts), 0, static_cast<UINT>(nverts / 2));
            };
            if (have_snow) {
                device->SetTexture(0, snow_tex);
                draw(snow_vb, snow_vertices.size());
            }
            if (have_splash) {
                device->SetTexture(0, splash_tex);
                draw(splash_vb, splash_vertices.size());
            }
        }

        // Instanced pass: each rain drop is one record expanded into a quad on the GPU (stream 0 = unit
        // quad, stream 1 = per-drop data with INSTANCEDATA frequency).
        if (ib_ok && have_rain && device->SetVertexShader(weather_inst_vs) == D3D_OK && device->SetVertexDeclaration(weather_inst_decl) == D3D_OK) {
            const auto tint = ImGui::ColorConvertU32ToFloat4(rain_color);
            const float tintf[4] = {tint.x, tint.y, tint.z, tint.w};
            const float flags[4] = {1.f, 0.f, 0.f, 0.f}; // flip texture V (streak runs along the downward velocity)
            device->SetVertexShaderConstantF(8, tintf, 1);
            device->SetVertexShaderConstantF(9, flags, 1);
            const UINT ninst = static_cast<UINT>(rain_instances.size());
            if (device->SetStreamSource(0, quad_geom_vb, 0, sizeof(GeomVert)) == D3D_OK && device->SetStreamSourceFreq(0, D3DSTREAMSOURCE_INDEXEDDATA | ninst) == D3D_OK && device->SetStreamSource(1, rain_inst_vb, 0, sizeof(WeatherInstance)) == D3D_OK &&
                device->SetStreamSourceFreq(1, D3DSTREAMSOURCE_INSTANCEDATA | 1u) == D3D_OK) {
                device->SetTexture(0, rain_tex);
                device->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, 4, 0, 2);
            }
            device->SetStreamSourceFreq(0, 1); // restore non-instanced frequency (state block also restores)
            device->SetStreamSourceFreq(1, 1);
        }
    }
    state_block->Apply();
    state_block->Release();
}

void WeatherModule::RegisterSettings(ToolboxModule* module)
{
    SettingsRegistry::RegisterField(module, "occlude_behind_terrain", &occlude_behind_terrain);
    SettingsRegistry::RegisterField(module, "render_max_distance", &render_max_distance);
    SettingsRegistry::RegisterField(module, "rain_color", &rain_color);
    SettingsRegistry::RegisterField(module, "ambient_color", &ambient_color);
}

void WeatherModule::OnSettingsLoaded()
{
    render_max_distance = std::clamp(render_max_distance, 10.0f, kMaxRadius);
    for (auto& c : conditions) {
        c.type = std::clamp(c.type, 0, kTypeCount - 1);
        c.drop_count = std::clamp(c.drop_count, 0, 20000);
        c.spread_radius = kMaxRadius; // fixed, not user-editable
        c.splash_chance = std::clamp(c.splash_chance, 0.f, 1.f);
        c.sound_min_interval = std::max(c.sound_min_interval, 0.f);
        c.sound_max_interval = std::max(c.sound_max_interval, c.sound_min_interval);
        c.ambient = std::clamp(c.ambient, 0.f, 1.f);
    }
}

void WeatherModule::LoadSettings(SettingsDoc& doc, ToolboxIni* legacy)
{
    ToolboxModule::LoadSettings(doc, legacy);
    doc.Get(Name(), "conditions", conditions); // keeps defaults if the key is absent
    OnSettingsLoaded();
}

void WeatherModule::SaveSettings(SettingsDoc& doc)
{
    ToolboxModule::SaveSettings(doc);
    doc.Set(Name(), "conditions", conditions);
}

void WeatherModule::DrawSettings()
{
    const auto red = ImGui::ColorConvertU32ToFloat4(Colors::Red());
    const auto green = ImGui::ColorConvertU32ToFloat4(Colors::Green());
    ImGui::TextColored(red, "Warning: This is a beta feature.");
    if (!GameWorldCompositor::IsActive()) ImGui::TextColored(red, GameWorldCompositor::HasFailed() ? "  in-world compositor FAILED to install." : "  in-world compositor: not installed yet.");

    ImGui::Checkbox("Occlude behind terrain", &occlude_behind_terrain);
    ImGui::DragFloat("Maximum render distance", &render_max_distance, 5.f, 10.f, kMaxRadius, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    auto col = ImGui::ColorConvertU32ToFloat4(rain_color);
    if (ImGui::ColorEdit4("Tint", &col.x, ImGuiColorEditFlags_AlphaBar)) rain_color = ImGui::ColorConvertFloat4ToU32(col);
    auto amb = ImGui::ColorConvertU32ToFloat4(ambient_color);
    if (ImGui::ColorEdit3("Overcast tint", &amb.x)) ambient_color = ImGui::ColorConvertFloat4ToU32(amb);
    ImGui::ShowHelp("Colour the scene is tinted toward while an overcast condition is active.\nPer-condition strength is set with each condition's \"Overcast\" slider.");

    ImGui::Separator();
    int to_remove = -1;
    for (int i = 0; i < static_cast<int>(conditions.size()); i++) {
        auto& c = conditions[i];
        ImGui::PushID(i);
        ImGui::Checkbox("##active", &c.active);
        ImGui::SameLine();
        if (ImGui::CollapsingHeader(c.name.empty() ? "(unnamed)" : c.name.c_str())) {
            ImGui::InputText("Name", c.name, 32);
            const char* type_names[kTypeCount] = {"Rain", "Snow"};
            ImGui::Combo("Type", &c.type, type_names, kTypeCount);
            ImGui::DragInt("Drop count", &c.drop_count, 25.f, 0, 20000, "%d", ImGuiSliderFlags_AlwaysClamp);
            ImGui::DragFloat("Drop size", &c.drop_size, 1.f, 1.f, 500.f, "%.0f");
            ImGui::DragFloat("Fall speed", &c.fall_speed, 50.f, 0.f, 30000.f, "%.0f");
            ImGui::DragFloat2("Wind (x, y)", &c.wind_x, 10.f, -10000.f, 10000.f, "%.0f");
            if (HasSplash(c.type)) ImGui::DragFloat("Splash chance", &c.splash_chance, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
            ImGui::DragFloat("Overcast", &c.ambient, 0.01f, 0.f, 1.f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
            ImGui::ShowHelp("How strongly this condition dims the scene toward the overcast tint while active.");

            ImGui::TextUnformatted("Sounds (file id, played at random while active)");
            int snd_remove = -1;
            for (int s = 0; s < static_cast<int>(c.sounds.size()); s++) {
                ImGui::PushID(s);
                ImGui::SetNextItemWidth(120.f);
                ImGui::InputScalar("##sid", ImGuiDataType_U32, &c.sounds[s], nullptr, nullptr, "%X", ImGuiInputTextFlags_CharsHexadecimal);
                const bool ok = IsValidSound(c.sounds[s]);
                ImGui::SameLine();
                ImGui::TextColored(ok ? green : red, ok ? ICON_FA_CHECK : ICON_FA_TIMES);
                ImGui::SameLine();
                if (ImGui::SmallButton("Test")) AudioSettings::PlaySoundFileId(c.sounds[s]);
                ImGui::SameLine();
                if (ImGui::SmallButton("Remove##snd")) snd_remove = s;
                ImGui::PopID();
            }
            if (snd_remove >= 0) c.sounds.erase(c.sounds.begin() + snd_remove);
            if (ImGui::SmallButton("Add sound")) c.sounds.push_back(0);
            ImGui::DragFloat2("Sound interval (s)", &c.sound_min_interval, 0.5f, 0.f, 600.f, "%.0f");
            ImGui::Checkbox("Play sounds in 3D", &c.sound_3d);
            ImGui::ShowHelp("Play each sound from a random nearby position so the game's 3D audio varies its\nvolume and stereo panning - reduces repetition when there's only one sound.\nNo effect if the sound isn't a positional one.");

            if (ImGui::Button("Remove condition")) to_remove = i;
        }
        ImGui::PopID();
    }
    if (to_remove >= 0) {
        conditions.erase(conditions.begin() + to_remove);
        if (to_remove < static_cast<int>(particles.size())) particles.erase(particles.begin() + to_remove);
    }

    if (ImGui::Button("Add condition")) conditions.push_back({});
    ImGui::SameLine();
    if (ImGui::Button("Reset to defaults")) ImGui::OpenPopup("Reset weather conditions?");
    if (ImGui::BeginPopupModal("Reset weather conditions?", nullptr, ImGuiWindowFlags_AlwaysAutoResize)) {
        ImGui::Text("Replace all conditions with the %d defaults?", static_cast<int>(DefaultConditions().size()));
        if (ImGui::Button("Reset")) {
            conditions = DefaultConditions();
            particles.clear();
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("Cancel")) ImGui::CloseCurrentPopup();
        ImGui::EndPopup();
    }
}

void WeatherModule::Initialize()
{
    ToolboxModule::Initialize();
    RegisterSettings(this);
    if (!compositor_token) compositor_token = GameWorldCompositor::RegisterDraw(&WeatherModule::DrawInWorld);
    GW::Chat::CreateCommand(&chat_hook_entry, L"weather", CmdWeather);
}

void WeatherModule::DrawSettingsInternal()
{
    DrawSettings();
}

void WeatherModule::SignalTerminate()
{
    if (compositor_token) {
        GameWorldCompositor::UnregisterDraw(compositor_token);
        compositor_token = 0;
    }
    GW::Chat::DeleteCommand(&chat_hook_entry);
}

void WeatherModule::Terminate()
{
    SignalTerminate();
    for (auto** p : {&rain_inst_vb, &snow_vb, &splash_vb, &quad_geom_vb})
        if (*p) {
            (*p)->Release();
            *p = nullptr;
        }
    if (quad_ib) {
        quad_ib->Release();
        quad_ib = nullptr;
    }
    for (auto** s : {&weather_vs, &weather_inst_vs})
        if (*s) {
            (*s)->Release();
            *s = nullptr;
        }
    if (weather_ps) {
        weather_ps->Release();
        weather_ps = nullptr;
    }
    for (auto** d : {&weather_decl, &weather_inst_decl})
        if (*d) {
            (*d)->Release();
            *d = nullptr;
        }
    rain_inst_cap = snow_cap = splash_cap = quad_ib_quads = 0;
    particles.clear();
    raindrop_tex_pp = snowflake_tex_pp = splash_tex_pp = nullptr; // owned by GwDatTextureModule's cache
    textures_requested = false;
    last_update = 0;
    ToolboxModule::Terminate();
}
