"""Turn standable_L<n>.bin into GWToolboxdll/Widgets/CartographyData.h.

Reads ./out by default, or a directory given as argv[1] - which is how you point it at the
in-game bake's output (Settings/cartography), the route that does not need the CDN reader.

Emits a fixed number of values per line. Do not wrap the joined text: a comma-separated
list has no spaces in it, so a text wrapper splits numbers down the middle (192 -> 19, 2),
which both breaks the syntax and silently corrupts the data.
"""
import os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'GWToolboxdll/Widgets/CartographyData.h')
PER_LINE = 32

HEADER = '''#pragma once

#include <cstdint>

// Which 32x32 world-map tiles each continent has standable ground on, baked offline from the
// game's own map files: every map that AreaInfo places on the world map, its pathing trapezoids
// taken from Gw.dat stream 1, reduced to the largest connected component (so terrain you cannot
// actually walk to is excluded), converted through that map's world-map anchor.
//
// Standable rather than discoverable on purpose - discoverable is this dilated by the reveal
// radius, and that radius depends on the Bird's Eye Compass, so it stays a runtime choice.
//
// Generated by tools/bake_cartography/make_header.py - do not edit by hand. 331 of the 350
// placed maps are covered; the rest have no map file id in maps_constant_data.h and are PvP,
// dev and event maps.
namespace CartographyData {
    struct Continent {
        int id;
        int x0, y0;      // tile coordinates of the grid's top-left
        int width, height;
        const uint8_t* bits;   // one bit per tile, row-major, LSB first
        int byte_count;
    };
'''

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'out')
    files = sorted(f for f in os.listdir(src) if f.endswith('.bin'))
    if not files:
        sys.exit(f"no .bin files in {src} - run bake.py, or the in-game bake, first")
    parts = [HEADER]
    entries = []
    for f in files:
        d = open(os.path.join(src, f), 'rb').read()
        if d[:4] != b'CSM1':
            sys.exit(f"{f}: bad magic")
        cont, x0, y0, w, h = struct.unpack_from('<5i', d, 4)
        bits = d[24:]
        var = f"kBits{cont}"
        entries.append((cont, x0, y0, w, h, var, len(bits), bits))
        set_bits = sum(bin(b).count('1') for b in bits)
        parts.append(f"\n    // continent {cont}: {w}x{h} tiles at ({x0},{y0}), {set_bits} standable\n")
        parts.append(f"    inline constexpr uint8_t {var}[] = {{\n")
        for i in range(0, len(bits), PER_LINE):
            row = ",".join(str(b) for b in bits[i:i+PER_LINE])
            parts.append(f"        {row},\n")
        parts.append("    };\n")
    parts.append("\n    inline constexpr Continent kContinents[] = {\n")
    for cont, x0, y0, w, h, var, n, _ in entries:
        parts.append(f"        {{{cont}, {x0}, {y0}, {w}, {h}, {var}, {n}}},\n")
    parts.append("    };\n}\n")
    open(OUT, 'w').write("".join(parts))
    print(f"wrote {OUT}: {os.path.getsize(OUT):,} bytes, {len(entries)} continents")
    verify(entries)

def verify(entries):
    """Read the arrays back out of the generated header and compare to the .bin bytes."""
    import re
    text = open(OUT).read()
    for cont, x0, y0, w, h, var, n, bits in entries:
        m = re.search(re.escape(f"uint8_t {var}[] = {{") + r"(.*?)\};", text, re.S)
        if not m:
            sys.exit(f"{var}: not found in generated header")
        vals = [int(v) for v in m.group(1).replace('\n', '').split(',') if v.strip()]
        if len(vals) != len(bits):
            sys.exit(f"{var}: {len(vals)} values round-tripped, expected {len(bits)}")
        if any(v > 255 for v in vals):
            sys.exit(f"{var}: value out of byte range - a number was split across lines")
        if bytes(vals) != bits:
            sys.exit(f"{var}: round-trip mismatch")
        print(f"  {var}: {len(vals)} bytes round-trip OK")

if __name__ == '__main__':
    main()
