"""Turn standable_L<n>.bin + creditable_L<n>.bin into GWToolboxdll/Widgets/CartographyData.h.

Reads ./out by default, or a directory given as argv[1] - which is how you point it at the
in-game bake's output (Settings/cartography), the route that does not need the CDN reader.

Emits a fixed number of values per line. Do not wrap the joined text: a comma-separated
list has no spaces in it, so a text wrapper splits numbers down the middle (192 -> 19, 2),
which both breaks the syntax and silently corrupts the data.
"""
import os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'GWToolboxdll/Widgets/CartographyData.h')
PER_LINE = 32

HEADER = '''#pragma once

#include <cstdint>

// Which 32x32 world-map tiles each continent has standable ground on, and which tiles that ground
// can credit, baked offline from the game's own map files: every map that AreaInfo places on the
// world map, its pathing trapezoids taken from Gw.dat stream 1, walked from the gates you can zone
// in on (unioned with the largest connected component, because a map whose portal props sit off in
// a side area loses everything otherwise), converted through that map's world-map anchor.
//
// `creditable` is `standable` dilated by the normal reveal radius and clipped to each map's own
// rectangle plus one square, because credit stops there - measured standing on Shenzun Tunnels
// ground a row past its south edge, which credits that row but not the next. It has to be baked
// per map: once the tiles are merged into one continent bitmap there is no way to tell whose
// rectangle to clip against. Bird's Eye Compass range stays a runtime question and uses
// `standable` directly.
//
// The `_glitched` pair is the same walk with travel portals not blocking, i.e. what you can reach
// by Shadow-stepping through a gate. Normal play cannot get there, so which pair the overlay reads
// is a setting rather than a fact.
//
// The `_any` pair is every trapezoid the file holds, walkable from an entrance or not: one map file
// carries every zone placed on that rectangle, so no single walk covers them all. It only answers
// whether ground exists, which is what deciding an explored square was explicable needs.
//
// Generated by tools/bake_cartography/make_header.py - do not edit by hand. 331 of the 350
// placed maps are covered; the rest have no map file id in maps_constant_data.h and are PvP,
// dev and event maps.
namespace CartographyData {
    struct Mask {
        int x0, y0;      // tile coordinates of the grid's top-left
        int width, height;
        const uint8_t* bits;   // one bit per tile, row-major, LSB first
        int byte_count;
    };

    struct Continent {
        int id;
        Mask standable;
        Mask creditable;
        // Same two, walked as if a travel portal did not stop you: what a Shadow-step gate glitch
        // puts in reach. Which pair the overlay reads is a runtime setting.
        Mask standable_glitched;
        Mask creditable_glitched;
        // Every trapezoid in the map file, reachable or not. A file holds every zone that shares
        // it, so no single walk covers them all; this is what answers "does ground exist here".
        Mask standable_any;
        Mask creditable_any;
    };
'''

KINDS = (('standable', b'CSM1', 'kBits'), ('creditable', b'CCM1', 'kCredit'),
         ('standable_glitched', b'CSG1', 'kBitsG'), ('creditable_glitched', b'CCG1', 'kCreditG'),
         ('standable_any', b'CSA1', 'kBitsA'), ('creditable_any', b'CCA1', 'kCreditA'))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'out')
    by_magic = {magic: kind for kind, magic, _ in KINDS}
    masks = {}
    for f in sorted(os.listdir(src)):
        if not f.endswith('.bin'):
            continue
        d = open(os.path.join(src, f), 'rb').read()
        if d[:4] not in by_magic:
            sys.exit("%s: bad magic %r" % (f, d[:4]))
        cont, x0, y0, w, h = struct.unpack_from('<5i', d, 4)
        masks.setdefault(cont, {})[by_magic[d[:4]]] = (x0, y0, w, h, d[24:])
    if not masks:
        sys.exit("no .bin files in %s - run bake.py, or the in-game bake, first" % src)
    incomplete = sorted(c for c, m in masks.items() if len(m) != len(KINDS))
    if incomplete:
        sys.exit("continents %s are missing a mask - re-run the bake, do not mix outputs" % incomplete)

    parts = [HEADER]
    arrays = []
    for cont in sorted(masks):
        for kind, _, prefix in KINDS:
            x0, y0, w, h, bits = masks[cont][kind]
            var = prefix + str(cont)
            arrays.append((var, bits))
            set_bits = sum(bin(b).count('1') for b in bits)
            parts.append("\n    // continent %d %s: %dx%d tiles at (%d,%d), %d set\n"
                         % (cont, kind, w, h, x0, y0, set_bits))
            parts.append("    inline constexpr uint8_t %s[] = {\n" % var)
            for i in range(0, len(bits), PER_LINE):
                parts.append("        %s,\n" % ",".join(str(b) for b in bits[i:i + PER_LINE]))
            parts.append("    };\n")
    parts.append("\n    inline constexpr Continent kContinents[] = {\n")
    for cont in sorted(masks):
        fields = []
        for kind, _, prefix in KINDS:
            x0, y0, w, h, bits = masks[cont][kind]
            fields.append("{%d, %d, %d, %d, %s%d, %d}" % (x0, y0, w, h, prefix, cont, len(bits)))
        parts.append("        {%d, %s},\n" % (cont, ", ".join(fields)))
    parts.append("    };\n}\n")
    open(OUT, 'w').write("".join(parts))
    print("wrote %s: %s bytes, %d continents" % (OUT, format(os.path.getsize(OUT), ','), len(masks)))
    verify(arrays)


def verify(arrays):
    """Read the arrays back out of the generated header and compare to the .bin bytes."""
    import re
    text = open(OUT).read()
    for var, bits in arrays:
        m = re.search(re.escape("uint8_t %s[] = {" % var) + r"(.*?)\};", text, re.S)
        if not m:
            sys.exit("%s: not found in generated header" % var)
        vals = [int(v) for v in m.group(1).replace("\n", "").split(",") if v.strip()]
        if len(vals) != len(bits):
            sys.exit("%s: %d values round-tripped, expected %d" % (var, len(vals), len(bits)))
        if any(v > 255 for v in vals):
            sys.exit("%s: value out of byte range - a number was split across lines" % var)
        if bytes(vals) != bits:
            sys.exit("%s: round-trip mismatch" % var)
        print("  %s: %d bytes round-trip OK" % (var, len(vals)))


if __name__ == '__main__':
    main()
