#include "stdafx.h"

#include <GWCA/Context/MapContext.h>
#include <GWCA/GameContainers/GamePos.h>
#include <GWCA/GameEntities/Camera.h>
#include <GWCA/Managers/CameraMgr.h>
#include <GWCA/Managers/MapMgr.h>
#include <GWCA/Managers/RenderMgr.h>
#include <GWCA/Managers/UIMgr.h>
#include <GWCA/GameContainers/Array.h>
#include <GWCA/Utilities/Hooker.h>
#include <GWCA/Utilities/Scanner.h>

#include <Defines.h>
#include <Widgets/Minimap/GameWorldRenderer.h>
#include <Widgets/Minimap/Minimap.h>
#include <ImGuiAddons.h>

// Note: these two files are autogenerated by CMake!
#include "GWCA/GameEntities/Agent.h"
#include "GWCA/Managers/AgentMgr.h"
#include "Shaders/game_world_renderer_vs.h"
#include "Shaders/game_world_renderer_dotted_ps.h"

namespace {
    unsigned lerp_steps_per_line = 10;
    float render_max_distance = 5000.f;
    float fog_factor = 0.5f;
    bool need_sync_markers = true;
    bool need_configure_pipeline = true;
    bool render_under_ui = true;
    // Stencil the round compass out of overlays so they don't bleed across the minimap.
    bool exclude_compass = true;

    // Test overlays against the scene depth buffer so world geometry hides them; z_near/z_far must match GW's projection (near clip ~47, valid 45-48; far insensitive 50k-200k).
    bool occlude_behind_terrain = true;
    float z_near = 47.0f;
    float z_far = 100000.f;


    GameWorldRenderer::RenderableVectors renderables;
    std::mutex renderables_mutex{};
    IDirect3DVertexShader9* vshader = nullptr;
    IDirect3DPixelShader9* pshader = nullptr;
    IDirect3DVertexDeclaration9* vertex_declaration = nullptr;

    // === FrCache compositor: draw the overlay between GW's world and UI passes ===
    // GW's deferred command buffer holds FRCACHE_GPU_RENDER (3D world) then frame entries (HUD); split at the boundary, flush world, draw, let GW render HUD on top.
    enum FrCacheEntryType : uint32_t {
        FRCACHE_GPU_RENDER = 0,
        FRCACHE_FRAME_CALLBACK = 1,
        FRCACHE_CLIENT_VIEWPORT = 2,
        FRCACHE_FRAME_VIEWPORT = 3,
    };
    struct FrCacheBufferEntry {
        FrCacheEntryType type;
        uint32_t index;
        uint32_t param;
    };
    using FrCacheRenderFn = void(__cdecl*)(uint32_t, uint32_t);
    FrCacheRenderFn FrCacheRenderAll_Func = nullptr;
    FrCacheRenderFn FrCacheRenderAll_Ret = nullptr;
    GW::Array<FrCacheBufferEntry>* render_buffer = nullptr;
    GW::Array<GW::UI::Frame*>* frame_array = nullptr;
    bool compositor_scanned = false;
    bool compositor_failed = false;
    bool compositor_hooked = false;
    bool in_compositor_draw = false; // true while drawing from the FrCache compositor
    bool drawn_this_frame = false;   // guard: draw only in the first world pass per frame

    void DrawOverlay(IDirect3DDevice9* device)
    {
        in_compositor_draw = true;
        GameWorldRenderer::Render(device);
        in_compositor_draw = false;
    }

    bool ScanCompositor()
    {
        if (compositor_scanned) return !compositor_failed;
        compositor_scanned = true;

        // FrCache_RenderAll asserts "frame" in FrCache.cpp at line 0x9e.
        const auto render_all = GW::Scanner::ToFunctionStart(
            GW::Scanner::FindAssertion("FrCache.cpp", "frame", 0x9e, 0), 0x200);
        if (!render_all) {
            compositor_failed = true;
            return false;
        }
        // FrCache_Render is the only caller of FrCache_RenderAll: scan back for the CALL.
        uintptr_t render_addr = 0;
        for (auto a = render_all - 5; a > render_all - 0x100; a--) {
            if (*reinterpret_cast<uint8_t*>(a) == 0xE8 && GW::Scanner::FunctionFromNearCall(a) == render_all) {
                render_addr = GW::Scanner::ToFunctionStart(a);
                break;
            }
        }
        if (!render_addr) {
            compositor_failed = true;
            return false;
        }
        // FrCache_Render opens with CMP [RenderFrameList.m_size], 0: the 4 bytes at +5 are &RenderFrameList.m_size; Array<T> globals are consecutive 16-byte structs, m_size at +8.
        const auto frame_list_size_addr = *reinterpret_cast<uintptr_t*>(render_addr + 5);
        const auto frame_list_base = frame_list_size_addr - 8;
        // Consecutive 16-byte Array<T> globals: RenderFrameList, FrameArray(+0x10), ..., RenderBuffer(+0x30).
        frame_array = reinterpret_cast<GW::Array<GW::UI::Frame*>*>(frame_list_base + 0x10);
        render_buffer = reinterpret_cast<GW::Array<FrCacheBufferEntry>*>(frame_list_base + 0x30);
        FrCacheRenderAll_Func = reinterpret_cast<FrCacheRenderFn>(render_all);
        if (!render_buffer || !FrCacheRenderAll_Func) {
            compositor_failed = true;
            return false;
        }
        return true;
    }

    void __cdecl OnFrCacheRenderAll(uint32_t param_1, uint32_t param_2)
    {
        GW::Hook::EnterHook();
        IDirect3DDevice9* device = GW::Render::GetDevice();

        // OFF (or unusable) -> run the original; the overlay is drawn at the 0xf hook instead.
        if (!render_under_ui || !render_buffer || !device) {
            FrCacheRenderAll_Ret(param_1, param_2);
            GW::Hook::LeaveHook();
            return;
        }

        auto& buffer = *render_buffer;

        // The main 3D scene is the FIRST GPU_RENDER block; everything after is HUD (incl. agent/UI 3D renders that correctly draw over us). Split right after it; UI-only/sub-render passes have no GPU block so boundary == size and skip below.
        uint32_t boundary = buffer.size();
        bool seen_gpu = false;
        for (uint32_t i = 0; i < buffer.size(); i++) {
            if (buffer[i].type == FRCACHE_GPU_RENDER) { seen_gpu = true; continue; }
            if (seen_gpu) { boundary = i; break; }
        }

        // Only the main world-then-HUD pass draws; others pass through, and the guard draws exactly once per frame.
        if (boundary == 0 || boundary >= buffer.size() || drawn_this_frame) {
            FrCacheRenderAll_Ret(param_1, param_2);
            GW::Hook::LeaveHook();
            return;
        }

        auto* const orig_buffer = buffer.m_buffer;
        const auto orig_size = buffer.m_size;

        // 1) world portion
        buffer.m_buffer = orig_buffer;
        buffer.m_size = boundary;
        FrCacheRenderAll_Ret(param_1, param_2);

        // 2) flush the world into the back/depth buffer, then draw the overlay
        buffer.m_buffer = orig_buffer;
        buffer.m_size = orig_size;
        GW::Render::FlushCommandQueue();
        DrawOverlay(device);
        drawn_this_frame = true;

        // 3) HUD portion (drawn on top of the overlay)
        buffer.m_buffer = orig_buffer + boundary;
        buffer.m_size = orig_size - boundary;
        FrCacheRenderAll_Ret(param_1, param_2);

        // restore the buffer for GW
        buffer.m_buffer = orig_buffer;
        buffer.m_size = orig_size;

        GW::Hook::LeaveHook();
    }

    void EnsureCompositorHook()
    {
        if (compositor_hooked || compositor_failed) return;
        if (!ScanCompositor()) return;
        if (GW::Hook::CreateHook(reinterpret_cast<void**>(&FrCacheRenderAll_Func), OnFrCacheRenderAll,
                                 reinterpret_cast<void**>(&FrCacheRenderAll_Ret)) != 0) {
            compositor_failed = true;
            return;
        }
        GW::Hook::EnableHooks(FrCacheRenderAll_Func);
        compositor_hooked = true;
    }

    // True when the compositor draws the overlay (under the UI), so the 0xf path must NOT also draw it.
    bool CompositorDrawing()
    {
        return render_under_ui && compositor_hooked && !compositor_failed;
    }

    // Screen-space circle of GW's compass terrain (inside the frame), or false when hidden. Mirrors Minimap's RepositionMinimapToCompass: inset by compass_padding, square off, inscribe.
    bool GetCompassTerrainCircle(float& cx, float& cy, float& radius)
    {
        const auto* frame = GW::UI::GetFrameByLabel(L"Compass");
        if (!frame || !frame->IsCreated() || !frame->IsVisible()) {
            return false;
        }
        constexpr float compass_padding = 1.05f;
        auto top_left = frame->position.GetTopLeftOnScreen(frame);
        auto bottom_right = frame->position.GetBottomRightOnScreen(frame);
        const float height = bottom_right.y - top_left.y;
        if (height <= 0.f) {
            return false;
        }
        const float diff = height - height / compass_padding;
        top_left.y += diff;
        top_left.x += diff;
        bottom_right.x -= diff;
        bottom_right.y = top_left.y + (bottom_right.x - top_left.x);
        cx = 0.5f * (top_left.x + bottom_right.x);
        cy = 0.5f * (top_left.y + bottom_right.y);
        radius = 0.5f * (bottom_right.x - top_left.x);
        return radius > 0.f;
    }

    // Set/clear `bit` in a screen-space disc over the compass terrain (fixed-function) so the overlay can be punched out to the circular minimap; touches only `bit` to spare GW's stencil, leaves pipeline unset for the caller to restore.
    void MarkCompassStencil(IDirect3DDevice9* device, const float cx, const float cy, const float radius, const DWORD bit, const bool set)
    {
        struct ScreenVertex { float x, y, z, rhw; };
        constexpr unsigned segments = 64;
        ScreenVertex fan[segments + 2];
        fan[0] = {cx, cy, 0.f, 1.f};
        for (unsigned i = 0; i <= segments; i++) {
            const float a = static_cast<float>(i) / static_cast<float>(segments) * DirectX::XM_2PI;
            fan[i + 1] = {cx + radius * std::cos(a), cy + radius * std::sin(a), 0.f, 1.f};
        }

        device->SetVertexShader(nullptr);
        device->SetPixelShader(nullptr);
        device->SetFVF(D3DFVF_XYZRHW);
        device->SetRenderState(D3DRS_COLORWRITEENABLE, 0);
        device->SetRenderState(D3DRS_ZENABLE, D3DZB_FALSE);
        device->SetRenderState(D3DRS_STENCILENABLE, TRUE);
        device->SetRenderState(D3DRS_STENCILMASK, 0xffffffff);
        device->SetRenderState(D3DRS_STENCILWRITEMASK, bit);
        device->SetRenderState(D3DRS_STENCILREF, set ? bit : 0);
        device->SetRenderState(D3DRS_STENCILFUNC, D3DCMP_ALWAYS);
        device->SetRenderState(D3DRS_STENCILFAIL, D3DSTENCILOP_REPLACE);
        device->SetRenderState(D3DRS_STENCILZFAIL, D3DSTENCILOP_REPLACE);
        device->SetRenderState(D3DRS_STENCILPASS, D3DSTENCILOP_REPLACE);
        device->DrawPrimitiveUP(D3DPT_TRIANGLEFAN, segments, fan, sizeof(ScreenVertex));
    }

    constexpr GW::Vec2f lerp(const GW::Vec2f& a, const GW::Vec2f& b, const float t)
    {
        return a * t + b * (1.f - t);
    }

    constexpr auto ALTITUDE_UNKNOWN = std::numeric_limits<float>::max();

    // Highest terrain surface at (x,y) among candidate planes (GW up is -z, so highest = min altitude). QueryAltitude returns 0.f out-of-bounds (ignored); ALTITUDE_UNKNOWN if no plane has data.
    float HighestSurfaceZ(const float x, const float y, const std::vector<uint32_t>& planes)
    {
        float best = ALTITUDE_UNKNOWN;
        for (const uint32_t zp : planes) {
            GW::GamePos p = {x, y, zp};
            const float a = GW::Map::QueryAltitude(&p);
            if (a != 0.f && (best == ALTITUDE_UNKNOWN || a < best))
                best = a;
        }
        return best;
    }

    // Surface altitude at (x,y) closest to `prev` over all planes (continuity tracking): the line follows whichever surface it walks (deck/ramp/ground), so a straight visgraph edge rides a bridge instead of cutting through, and unlike "highest wins" never floats a ground sample onto an overhead deck. 0.f is out-of-bounds (skipped); ALTITUDE_UNKNOWN if no data.
    float ClosestSurfaceZ(const float x, const float y, const uint32_t num_planes, const float prev)
    {
        float best = ALTITUDE_UNKNOWN, best_d = std::numeric_limits<float>::max();
        for (uint32_t zp = 0; zp < num_planes; ++zp) {
            GW::GamePos p = {x, y, zp};
            const float a = GW::Map::QueryAltitude(&p);
            if (a == 0.f) continue;
            const float d = std::abs(a - prev);
            if (d < best_d) { best_d = d; best = a; }
        }
        return best;
    }

    std::vector<GW::GamePos> circular_points_from_marker(const GW::GamePos& marker, const float size)
    {
        std::vector<GW::GamePos> points{};
        constexpr float pi = DirectX::XM_PI;
        constexpr size_t num_points_per_circle = 48;
        constexpr auto slice = 2.0f * pi / static_cast<float>(num_points_per_circle);
        for (auto i = 0u; i < num_points_per_circle; i++) {
            const auto angle = slice * static_cast<float>(i);
            points.emplace_back(marker.x + size * std::cos(angle), marker.y + size * std::sin(angle), marker.zplane);
        }
        points.push_back(points.at(0)); // close the loop
        return points;
    }

    GameWorldRenderer::GenericPolyRenderable* find_matching_poly(const GameWorldRenderer::GenericPolyRenderable& poly_to_find)
    {
        // Reuse an already-plotted poly to skip recomputing altitudes.
        const auto found = std::ranges::find_if(renderables, [&poly_to_find](const GameWorldRenderer::GenericPolyRenderable& check) {
            if (!(check.map_id == poly_to_find.map_id
                  && check.col == poly_to_find.col
                  && check.filled == poly_to_find.filled
                  && check.points.size() == poly_to_find.points.size()))
                return false;
            for (size_t i = 0; i < check.points.size(); i++) {
                if (check.points[i] != poly_to_find.points[i])
                    return false;
            }
            return true;
        });
        if (found != renderables.end()) {
            return &(*found);
        }
        return nullptr;
    }

    // Compute vertex altitudes (once, requires the correct map) then upload to the device buffer.
    bool AddPolyToDevice(GameWorldRenderer::GenericPolyRenderable& poly, IDirect3DDevice9* device)
    {
        if (poly.vb)
            return true; // vb exists => altitudes already done
        auto& vertices = poly.vertices;
        if (poly.vertices_processed == vertices.size())
            return true;
        const GW::PathingMapArray* pathing_map = GW::Map::GetPathingMap();
        if (!pathing_map || pathing_map->size() == 0)
            return false;
        const uint32_t num_planes = static_cast<uint32_t>(pathing_map->size());

        if (poly.filled) {
            // Filled shapes are an earcut triangle soup (no vertex order), so no continuity: drape each vertex on the highest surface among the shape's own planes.
            std::vector<uint32_t> candidate_planes;
            for (const auto& pt : poly.points) {
                if (std::ranges::find(candidate_planes, pt.zplane) == candidate_planes.end())
                    candidate_planes.push_back(pt.zplane);
            }
            for (size_t i = poly.vertices_processed; i < vertices.size(); i++, poly.vertices_processed++)
                vertices[i].z = HighestSurfaceZ(vertices[i].x, vertices[i].y, candidate_planes);
        }
        else {
            // Ordered, densely-sampled path: drape by continuity (each sample follows the walked surface across bridges even with no waypoint on that plane). Seed from the first waypoint; the leading from_player_pos segment is re-seeded from live player height below.
            GW::GamePos seed_pos = poly.points.empty() ? GW::GamePos{} : poly.points.front();
            float prev = GW::Map::QueryAltitude(&seed_pos);
            if (prev == 0.f) prev = ClosestSurfaceZ(seed_pos.x, seed_pos.y, num_planes, -1.0e9f); // highest surface
            for (size_t i = poly.vertices_processed; i < vertices.size(); i++, poly.vertices_processed++) {
                const float z = ClosestSurfaceZ(vertices[i].x, vertices[i].y, num_planes, prev);
                if (z != ALTITUDE_UNKNOWN) prev = z;
                vertices[i].z = z;
            }
        }

        // Backfill no-data vertices by holding the last known altitude so the line never spikes off-screen.
        float fill = ALTITUDE_UNKNOWN;
        for (const auto& v : vertices)
            if (v.z != ALTITUDE_UNKNOWN) { fill = v.z; break; }
        if (fill != ALTITUDE_UNKNOWN) {
            float last = fill;
            for (auto& v : vertices) {
                if (v.z == ALTITUDE_UNKNOWN) v.z = last;
                else last = v.z;
            }
        }

        auto res = device->CreateVertexBuffer(vertices.size() * sizeof(D3DVertex), D3DUSAGE_WRITEONLY, D3DFVF_CUSTOMVERTEX, D3DPOOL_MANAGED, &poly.vb, nullptr);
        if (res != S_OK) {
            poly.vb = nullptr;
            return false;
        }

        void* mem_loc = nullptr;
        res = poly.vb->Lock(0, vertices.size() * sizeof(D3DVertex), &mem_loc, D3DLOCK_DISCARD);
        if (res != S_OK || !mem_loc) {
            poly.vb->Release();
            poly.vb = nullptr;
            return false;
        }

        memcpy(mem_loc, vertices.data(), vertices.size() * sizeof(D3DVertex));
        poly.vb->Unlock();
        return true;
    }
} // namespace

GameWorldRenderer::GenericPolyRenderable::GenericPolyRenderable(
    const GW::Constants::MapID map_id,
    const std::vector<GW::GamePos>& points,
    const unsigned int col,
    const bool filled) noexcept
    : map_id(map_id),
      col(col),
      points(points),
      filled(filled) {}

GameWorldRenderer::GenericPolyRenderable::~GenericPolyRenderable() noexcept
{
    if (vb != nullptr) {
        vb->Release();
        vb = nullptr;
    }
}

void GameWorldRenderer::GenericPolyRenderable::Draw(IDirect3DDevice9* device)
{
    if (vertices.empty()) {
        if (filled && points.size() >= 3) { // need >= 3 points for one triangle
            std::vector<GW::GamePos> lerp_points{};
            for (size_t i = 0; i < points.size(); i++) {
                if (!lerp_points.empty() && lerp_steps_per_line > 0) {
                    for (auto j = 1u; j < lerp_steps_per_line; j++) {
                        const float div = static_cast<float>(j) / static_cast<float>(lerp_steps_per_line);
                        auto split = lerp(points[i], points[i - 1], div);
                        lerp_points.emplace_back(split.x, split.y, points[i].zplane);
                    }
                }
                lerp_points.push_back(points[i]);
            }
            const std::vector<unsigned> indices = mapbox::earcut<unsigned>(std::vector{{lerp_points}});
            for (size_t i = 0; i < indices.size(); i++) {
                const auto& pt = lerp_points[indices[i]];
                vertices.emplace_back(pt.x, pt.y, ALTITUDE_UNKNOWN, col);
            }
        }
        else {
            // Sample each segment ~every 50 gwinches so a slope/stairs/bridge between hops follows the surface instead of a straight chord; lerp_steps_per_line is the floor. Plane draping is resolved in AddPolyToDevice.
            constexpr float sample_spacing = 50.f;
            for (size_t i = 0; i < points.size(); i++) {
                const auto& pt = points[i];
                if (!vertices.empty()) {
                    const float dx = points[i].x - points[i - 1].x, dy = points[i].y - points[i - 1].y;
                    const auto steps = std::max(lerp_steps_per_line, static_cast<unsigned>(std::sqrt(dx * dx + dy * dy) / sample_spacing));
                    for (auto j = 1u; j < steps; j++) {
                        const auto div = static_cast<float>(j) / static_cast<float>(steps);
                        const auto split = lerp(points[i], points[i - 1], div);
                        vertices.emplace_back(split.x, split.y, ALTITUDE_UNKNOWN, col);
                    }
                }
                vertices.emplace_back(pt.x, pt.y, ALTITUDE_UNKNOWN, col);
            }
        }
    }

    if (!AddPolyToDevice(*this, device))
        return;

    if (from_player_pos && vertices.size() > 1) {
        if (const auto player = GW::Agents::GetControlledCharacter()) {
            // Re-anchor the leading line to the player's live position each frame and drape by continuity from player->z, which is reliable even when the reported plane is 0 on a bridge (seeding from the plane sank the line to the ground beneath the bridge).
            const float ex = vertices.back().x, ey = vertices.back().y;
            const GW::PathingMapArray* pathing_map = GW::Map::GetPathingMap();
            const uint32_t num_planes = pathing_map ? static_cast<uint32_t>(pathing_map->size()) : 0;
            const size_t last = vertices.size() - 1;
            float prev = player->z;
            for (size_t j = 0; j <= last; ++j) {
                const float t = static_cast<float>(j) / static_cast<float>(last);
                const float sx = player->pos.x + (ex - player->pos.x) * t;
                const float sy = player->pos.y + (ey - player->pos.y) * t;
                float z = num_planes ? ClosestSurfaceZ(sx, sy, num_planes, prev) : ALTITUDE_UNKNOWN;
                if (z != ALTITUDE_UNKNOWN) prev = z; else z = prev;
                vertices[j].x = sx;
                vertices[j].y = sy;
                vertices[j].z = z;
            }

            void* mem_loc = nullptr;
            auto res = vb->Lock(0, vertices.size() * sizeof(D3DVertex), &mem_loc, D3DLOCK_DISCARD);
            if (res == S_OK) {
                memcpy(mem_loc, vertices.data(), vertices.size() * sizeof(D3DVertex));
                vb->Unlock();
            }
        }
    }

    if (device->SetStreamSource(0, vb, 0, sizeof(D3DVertex)) != D3D_OK) {
        return;
    }

    const BOOL dotted_effect_constant[1] = {static_cast<BOOL>(use_dotted_effect)};
    if (device->SetPixelShaderConstantB(0, dotted_effect_constant, 1) != D3D_OK) {
        Log::Error("GameWorldRenderer: unable to SetPixelShaderConstantF#3, aborting render.");
        return;
    }

    // Guard the counts: an empty line would underflow vertices.size()-1 (size_t) and crash DrawPrimitive.
    if (filled) {
        if (vertices.size() >= 3) device->DrawPrimitive(D3DPT_TRIANGLELIST, 0, vertices.size() / 3);
    }
    else if (vertices.size() >= 2) {
        device->DrawPrimitive(D3DPT_LINESTRIP, 0, vertices.size() - 1);
    }
}

bool GameWorldRenderer::SetD3DTransform(IDirect3DDevice9* device)
{
    // Build view/proj matrices matching GW's world-render camera.
    if (device == nullptr) {
        return false;
    }

    constexpr auto vertex_shader_view_matrix_offset = 0u;
    constexpr auto vertex_shader_proj_matrix_offset = 4u;

    DirectX::XMFLOAT4X4A mat_view{};
    const auto cam = GW::CameraMgr::GetCamera();
    const DirectX::XMFLOAT3 eye_pos = {cam->position.x, cam->position.y, cam->position.z};
    const DirectX::XMFLOAT3 player_pos = {cam->look_at_target.x, cam->look_at_target.y, cam->look_at_target.z};
    constexpr DirectX::XMFLOAT3 up = {0.0f, 0.0f, -1.0f};
    XMStoreFloat4x4A(
        &mat_view,
        XMMatrixTranspose(
            DirectX::XMMatrixLookAtLH(XMLoadFloat3(&eye_pos), XMLoadFloat3(&player_pos), XMLoadFloat3(&up))
        )
    );
    if (device->SetVertexShaderConstantF(vertex_shader_view_matrix_offset, reinterpret_cast<const float*>(&mat_view), 4) != D3D_OK) {
        Log::Error("GameWorldRenderer: unable to SetVertexShaderConstantF(view), aborting render.");
        return false;
    }

    DirectX::XMFLOAT4X4A mat_proj{};
    const auto fov = GW::Render::GetFieldOfView();
    const auto aspect_ratio = static_cast<float>(GW::Render::GetViewportWidth()) / static_cast<float>(GW::Render::GetViewportHeight());

    XMStoreFloat4x4A(
        &mat_proj,
        XMMatrixTranspose(
            DirectX::XMMatrixPerspectiveFovLH(fov, aspect_ratio, z_near, z_far)
        )
    );
    if (device->SetVertexShaderConstantF(vertex_shader_proj_matrix_offset, reinterpret_cast<const float*>(&mat_proj), 4) != D3D_OK) {
        Log::Error("GameWorldRenderer: unable to SetVertexShaderConstantF(projection), aborting render.");
        return false;
    }

    return true;
}

void GameWorldRenderer::Render(IDirect3DDevice9* device)
{
    if (need_sync_markers) {
        // Sync on the render thread: creating vertex buffers needs the D3D device.
        SyncAllMarkers();
    }

    // When occluding, the compositor draws the overlay between GW's world and UI passes, not here; this 0xf path draws only when not occluding or the compositor can't run (in_compositor_draw means this IS the compositor).
    if (!in_compositor_draw) {
        // Runs once per frame at End Scene after all FrCache passes: reset the per-frame draw guard.
        drawn_this_frame = false;
        if (render_under_ui) {
            EnsureCompositorHook();
            if (CompositorDrawing()) {
                return;
            }
        }
    }

    if (renderables.empty()) {
        return;
    }
    if (need_configure_pipeline) {
        if (!ConfigureProgrammablePipeline(device)) {
            return;
        }
    }

    // Snapshot all device state; restored unconditionally on exit (incl. error paths) so GW's later rendering isn't corrupted.
    IDirect3DStateBlock9* state_block = nullptr;
    if (device->CreateStateBlock(D3DSBT_ALL, &state_block) != D3D_OK) {
        return;
    }

    if (device->SetVertexShader(vshader) == D3D_OK
        && device->SetPixelShader(pshader) == D3D_OK
        && device->SetVertexDeclaration(vertex_declaration) == D3D_OK
        && SetD3DTransform(device)) {

        // Fully specify the pipeline: GW's ambient UI state (alpha test/cull/fog/colour-write) would otherwise discard our draw. The state block restores it on exit.
        device->SetRenderState(D3DRS_SCISSORTESTENABLE, FALSE);
        device->SetRenderState(D3DRS_STENCILENABLE, FALSE);
        device->SetRenderState(D3DRS_FILLMODE, D3DFILL_SOLID);
        device->SetRenderState(D3DRS_SHADEMODE, D3DSHADE_GOURAUD);
        device->SetRenderState(D3DRS_CULLMODE, D3DCULL_NONE);
        device->SetRenderState(D3DRS_LIGHTING, FALSE);
        device->SetRenderState(D3DRS_FOGENABLE, FALSE);
        device->SetRenderState(D3DRS_ALPHATESTENABLE, FALSE);
        device->SetRenderState(D3DRS_COLORWRITEENABLE,
                               D3DCOLORWRITEENABLE_RED | D3DCOLORWRITEENABLE_GREEN | D3DCOLORWRITEENABLE_BLUE | D3DCOLORWRITEENABLE_ALPHA);
        device->SetRenderState(D3DRS_ALPHABLENDENABLE, TRUE);
        device->SetRenderState(D3DRS_BLENDOP, D3DBLENDOP_ADD);
        device->SetRenderState(D3DRS_SRCBLEND, D3DBLEND_SRCALPHA);
        device->SetRenderState(D3DRS_DESTBLEND, D3DBLEND_INVSRCALPHA);

        if (occlude_behind_terrain) {
            // Depth-test against the scene so geometry occludes the overlay; never write depth (must not disturb GW's values).
            device->SetRenderState(D3DRS_ZENABLE, D3DZB_TRUE);
            device->SetRenderState(D3DRS_ZWRITEENABLE, FALSE);
            device->SetRenderState(D3DRS_ZFUNC, D3DCMP_LESSEQUAL);
        }
        else {
            device->SetRenderState(D3DRS_ZENABLE, D3DZB_FALSE);
        }

        const GW::Camera* cam = GW::CameraMgr::GetCamera();
        // Pixel shader constants (all Float4): c0 player pos, c1 max distance, c2 fog start.
        const float cur_pos_constant[4] = {cam->look_at_target.x, cam->look_at_target.y, cam->look_at_target.z, 0.0f};
        device->SetPixelShaderConstantF(0, cur_pos_constant, 1);

        const float max_dist_constant[4] = {render_max_distance, 0.0f, 0.0f, 0.0f};
        device->SetPixelShaderConstantF(1, max_dist_constant, 1);

        const float fog_starts_at_constant[4] = {render_max_distance - render_max_distance * fog_factor, 0.0f, 0.0f, 0.0f};
        device->SetPixelShaderConstantF(2, fog_starts_at_constant, 1);

        const auto map_id = GW::Map::GetMapID();
        renderables_mutex.lock();

        auto draw_renderables = [&] {
            for (auto& renderable : renderables) {
                if (renderable.map_id == map_id) {
                    renderable.Draw(device);
                }
            }
        };

        // GW draws the compass disc (world pass) and its frame (later HUD pass) separately, so the overlay lands between and bleeds across the minimap; stencil the disc out.
        float compass_cx, compass_cy, compass_radius;
        if (exclude_compass && GetCompassTerrainCircle(compass_cx, compass_cy, compass_radius)) {
            constexpr DWORD compass_stencil_bit = 0x80;
            MarkCompassStencil(device, compass_cx, compass_cy, compass_radius, compass_stencil_bit, true);

            // restore the programmable pipeline + render state the mark pass changed
            device->SetVertexShader(vshader);
            device->SetPixelShader(pshader);
            device->SetVertexDeclaration(vertex_declaration);
            device->SetRenderState(D3DRS_COLORWRITEENABLE,
                                   D3DCOLORWRITEENABLE_RED | D3DCOLORWRITEENABLE_GREEN | D3DCOLORWRITEENABLE_BLUE | D3DCOLORWRITEENABLE_ALPHA);
            device->SetRenderState(D3DRS_ZENABLE, occlude_behind_terrain ? D3DZB_TRUE : D3DZB_FALSE);

            // draw the overlay only where our bit is clear, i.e. outside the compass disc
            device->SetRenderState(D3DRS_STENCILENABLE, TRUE);
            device->SetRenderState(D3DRS_STENCILMASK, compass_stencil_bit);
            device->SetRenderState(D3DRS_STENCILREF, 0);
            device->SetRenderState(D3DRS_STENCILFUNC, D3DCMP_EQUAL);
            device->SetRenderState(D3DRS_STENCILFAIL, D3DSTENCILOP_KEEP);
            device->SetRenderState(D3DRS_STENCILZFAIL, D3DSTENCILOP_KEEP);
            device->SetRenderState(D3DRS_STENCILPASS, D3DSTENCILOP_KEEP);

            draw_renderables();

            // clear our bit back so GW's shared stencil is left exactly as we found it
            MarkCompassStencil(device, compass_cx, compass_cy, compass_radius, compass_stencil_bit, false);
            device->SetRenderState(D3DRS_STENCILENABLE, FALSE);
        }
        else {
            draw_renderables();
        }
        renderables_mutex.unlock();
    }

    state_block->Apply();
    state_block->Release();
}

bool GameWorldRenderer::ConfigureProgrammablePipeline(IDirect3DDevice9* device)
{
    constexpr D3DVERTEXELEMENT9 decl[] = {
        {0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0},
        {0, 12, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0},
        D3DDECL_END()};
    if (device->CreateVertexDeclaration(decl, &vertex_declaration) != D3D_OK) {
        //Log::Error("GameWorldRenderer: unable to CreateVertexDeclaration");
        return false;
    }

    if (device->CreateVertexShader(reinterpret_cast<const DWORD*>(&game_world_renderer_vs), &vshader) != D3D_OK) {
        //Log::Error("GameWorldRenderer: unable to CreateVertexShader");
        return false;
    }
    if (device->CreatePixelShader(reinterpret_cast<const DWORD*>(&game_world_renderer_dotted_ps), &pshader) != D3D_OK) {
        //Log::Error("GameWorldRenderer: unable to CreatePixelShader");
        return false;
    }
    need_configure_pipeline = false;
    return true;
}

void GameWorldRenderer::RegisterSettings(ToolboxModule* module)
{
    SettingsRegistry::RegisterField(module, "render_max_distance", &render_max_distance);
    SettingsRegistry::RegisterField(module, "lerp_steps_per_line", &lerp_steps_per_line);
    SettingsRegistry::RegisterField(module, "fog_factor", &fog_factor);
    SettingsRegistry::RegisterField(module, "occlude_behind_terrain", &occlude_behind_terrain);
    SettingsRegistry::RegisterField(module, "depth_z_near", &z_near);
    SettingsRegistry::RegisterField(module, "depth_z_far", &z_far);
    SettingsRegistry::RegisterField(module, "render_under_ui", &render_under_ui);
    SettingsRegistry::RegisterField(module, "exclude_compass", &exclude_compass);
}

void GameWorldRenderer::OnSettingsLoaded()
{
    render_max_distance = std::max(render_max_distance, 10.0f);
    fog_factor = std::clamp(fog_factor, 0.0f, 1.0f);
    z_near = std::max(z_near, 0.01f);
    z_far = std::max(z_far, z_near + 1.0f);
    need_sync_markers = true;
}

void GameWorldRenderer::DrawSettings()
{
    const auto red = ImGui::ColorConvertU32ToFloat4(Colors::Red());
    ImGui::TextColored(red, "Warning: This is a beta feature.");
    ImGui::Text("Note: custom markers are only rendered in-game if the option is enabled for a particular marker (check settings).");
    ImGui::DragFloat("Maximum render distance", &render_max_distance, 5.f, 0.f, 10000.f, "%.0f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("Maximum distance to render custom markers on the in-game terrain.");
    need_sync_markers |= ImGui::DragInt("Interpolation granularity", reinterpret_cast<int*>(&lerp_steps_per_line), 1.0f, 0, 100, "%d", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("Number of points to interpolate. Affects smoothness of rendering.");
    ImGui::DragFloat("Fog factor", &fog_factor, 0.1f, 0.0f, 1.0f, "%.2f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::ShowHelp("Scales from 0.0 (disabled) to 1.0");

    ImGui::Checkbox("Render under game UI", &render_under_ui);
    ImGui::ShowHelp("Draw overlays beneath the in-game UI (menus, party window, etc.) instead of on top.\n"
                    "Experimental: hooks GW's UI render pass. Turn off to restore the original on-top drawing.");
    if (render_under_ui) {
        if (compositor_failed)
            ImGui::TextColored(red, "  under-UI hook FAILED to install - drawing on top.");
        else if (compositor_hooked)
            ImGui::TextColored(ImGui::ColorConvertU32ToFloat4(Colors::Green()), "  under-UI hook active.");
        else
            ImGui::TextDisabled("  under-UI hook: not installed yet.");
    }

    ImGui::Checkbox("Keep clear of the compass", &exclude_compass);
    ImGui::ShowHelp("Don't draw in-world overlays over the in-game compass/minimap.\n"
                    "GW renders the compass terrain and its frame in separate passes, so overlays "
                    "would otherwise bleed across the inside of the minimap.");

    ImGui::Checkbox("Occlude behind terrain", &occlude_behind_terrain);
    ImGui::ShowHelp("Hide overlays behind walls, buildings and terrain using the game's depth buffer.\n"
                    "If overlays vanish or z-fight badly, disable this or tune the depth values below.");
    if (occlude_behind_terrain) {
        ImGui::DragFloat("Projection near plane", &z_near, 0.1f, 1.f, 100.f, "%.1f");
        ImGui::ShowHelp("Must match the game's near clip for occlusion to be accurate.\n"
                        "~47 is correct; too low hides visible overlays, too high lets them show through walls.");
        ImGui::DragFloat("Projection far plane", &z_far, 50.f, 1000.f, 200000.f, "%.0f");
        ImGui::ShowHelp("Insensitive anywhere from ~50000 to 200000.");
    }
}

void GameWorldRenderer::TriggerSyncAllMarkers()
{
    need_sync_markers = true;
}

void GameWorldRenderer::Terminate()
{
    if (compositor_hooked && FrCacheRenderAll_Func) {
        GW::Hook::RemoveHook(FrCacheRenderAll_Func);
        compositor_hooked = false;
    }
    renderables.clear();
    if (vshader)
        vshader->Release();
    vshader = nullptr;
    if (pshader)
        pshader->Release();
    pshader = nullptr;
    if (vertex_declaration)
        vertex_declaration->Release();
    vertex_declaration = nullptr;
    ToolboxModule::Terminate();
}

void GameWorldRenderer::SyncAllMarkers()
{
    renderables_mutex.lock();
    auto lines = SyncLines();
    auto polys = SyncPolys();
    auto markers = SyncMarkers();

    renderables.clear();
    renderables.reserve(lines.size() + polys.size() + markers.size());

    for (auto& line : lines) {
        renderables.push_back(std::move(line));
    }
    for (auto& poly : polys) {
        renderables.push_back(std::move(poly));
    }
    for (auto& marker : markers) {
        renderables.push_back(std::move(marker));
    }
    renderables_mutex.unlock();
    need_sync_markers = false;
}

GameWorldRenderer::RenderableVectors GameWorldRenderer::SyncLines()
{
    const auto& lines = Minimap::Instance().custom_renderer.GetLines();

    const auto map_id = GW::Map::GetMapID();

    RenderableVectors out;
    out.reserve(lines.size());
    for (const auto line : lines) {
        if (!(line->draw_on_terrain && line->visible)) {
            continue;
        }
        if (!(line->map == map_id || line->map == GW::Constants::MapID::None))
            continue;
        if (GW::Map::GetInstanceType() == GW::Constants::InstanceType::Outpost && map_id == GW::Constants::MapID::Domain_of_Anguish && !line->draw_everywhere) {
            // don't draw normal lines in doa outpost
            continue;
        }
        std::vector points = {line->p1, line->p2};

        auto poly_to_add = GenericPolyRenderable(line->map, points, line->color, false);

        poly_to_add.from_player_pos = line->from_player_pos;
        poly_to_add.use_dotted_effect = line->created_by_toolbox && line->dotted;

        if (const auto found = find_matching_poly(poly_to_add)) {
            found->from_player_pos = poly_to_add.from_player_pos;
            found->use_dotted_effect = poly_to_add.use_dotted_effect;
            out.emplace_back(std::move(*found));
        }
        else {
            out.emplace_back(std::move(poly_to_add));
        }
    }
    return out;
}

GameWorldRenderer::RenderableVectors GameWorldRenderer::SyncPolys()
{
    const auto& polys = Minimap::Instance().custom_renderer.GetPolys();
    RenderableVectors out;

    const auto map_id = GW::Map::GetMapID();

    out.reserve(polys.size());
    for (const auto& poly : polys) {
        if (!(poly.draw_on_terrain && poly.visible && poly.points.size())) {
            continue;
        }
        if (!(poly.map == map_id || poly.map == GW::Constants::MapID::None))
            continue;
        if (GW::Map::GetInstanceType() == GW::Constants::InstanceType::Outpost && map_id == GW::Constants::MapID::Domain_of_Anguish) {
            // don't draw normal polys in doa outpost
            continue;
        }
        std::vector<GW::GamePos> pts{};
        std::ranges::transform(poly.points, std::back_inserter(pts), [](const GW::Vec2f& pt) { return GW::GamePos(pt); });

        auto poly_to_add = GenericPolyRenderable(poly.map, pts, poly.color, poly.filled);

        if (const auto found = find_matching_poly(poly_to_add)) {
            out.emplace_back(std::move(*found));
        }
        else {
            out.emplace_back(std::move(poly_to_add));
        }
    }
    return out;
}

GameWorldRenderer::RenderableVectors GameWorldRenderer::SyncMarkers()
{
    const auto& markers = Minimap::Instance().custom_renderer.GetMarkers();

    const auto map_id = GW::Map::GetMapID();

    RenderableVectors out;
    out.reserve(markers.size());
    for (const auto& marker : markers) {
        if (!(marker.draw_on_terrain && marker.visible)) {
            continue;
        }
        if (!(marker.map == map_id || marker.map == GW::Constants::MapID::None)) {
            continue;
        }
        if (GW::Map::GetInstanceType() == GW::Constants::InstanceType::Outpost && map_id == GW::Constants::MapID::Domain_of_Anguish) {
            // don't draw normal markers in doa outpost
            continue;
        }

        auto points = circular_points_from_marker(marker.pos, marker.size);

        const auto color = (marker.color & IM_COL32_A_MASK) == 0 ? CustomRenderer::color : marker.color;

        auto poly_to_add = GenericPolyRenderable(marker.map, points, color, marker.IsFilled());

        auto found = find_matching_poly(poly_to_add);

        if (found) {
            out.emplace_back(std::move(*found));
        }
        else {
            out.emplace_back(std::move(poly_to_add));
        }
    }
    return out;
}

// ===========================================================================
// ToolboxModule lifecycle (own settings section / JSON file, separate from Minimap)
// ===========================================================================

void GameWorldRenderer::Initialize()
{
    ToolboxModule::Initialize(); // registers DrawSettingsInternal() under "In-game rendering"
    // Register fields against this module so they persist in their own section, not under the Minimap.
    RegisterSettings(this);
}

void GameWorldRenderer::LoadSettings(SettingsDoc& doc, ToolboxIni* legacy)
{
    ToolboxModule::LoadSettings(doc, legacy);
    OnSettingsLoaded();
}

void GameWorldRenderer::DrawSettingsInternal()
{
    DrawSettings();
}

void GameWorldRenderer::SignalTerminate()
{
    // Stop the compositor the instant the module is disabled (it leaves the draw loop too, so Render() also stops).
    if (compositor_hooked && FrCacheRenderAll_Func) {
        GW::Hook::RemoveHook(FrCacheRenderAll_Func);
        compositor_hooked = false;
    }
}
