#include <unordered_map>
#include <vector>

#include <GWCA/Constants/Maps.h>

struct MapConstantInfo
{
    GW::Constants::MapID map_id;
    int file_hash;
};

struct SpawnPoint
{
    int ID;
    int MapID;
    float X;
    float Y;
    int Plane;
    int Radius;
};

std::unordered_map<int, std::vector<MapConstantInfo>> constant_maps_info = {
  {0,
   {{GW::Constants::MapID::Gladiators_Arena, 0},
    {GW::Constants::MapID::Warriors_Isle_outpost, 0},
    {GW::Constants::MapID::Hunters_Isle_outpost, 0},
    {GW::Constants::MapID::Griffons_Mouth, 0},
    {GW::Constants::MapID::The_Fissure_of_Woe, 0},
    {GW::Constants::MapID::Test_Map_species_art, 0},
    {GW::Constants::MapID::DAlessio_Arena_mission, 0},
    {GW::Constants::MapID::All_Call_Click_Point_1, 0},
    {GW::Constants::MapID::Druids_Isle, 0},
    {GW::Constants::MapID::Tournament_6, 0},
    {GW::Constants::MapID::Broken_Tower_mission, 0},
    {GW::Constants::MapID::Unholy_Temples_mission, 0},
    {GW::Constants::MapID::The_Vault_mission, 0},
    {GW::Constants::MapID::Sacred_Temples_mission, 0},
    {GW::Constants::MapID::Spearhead_Peak, 0},
    {GW::Constants::MapID::Titans_Tears, 0},
    {GW::Constants::MapID::Scarred_Earth2, 0},
    {GW::Constants::MapID::Ascalon_Academy_outpost, 0},
    {GW::Constants::MapID::Ascalon_Academy_PvP_battle_mission_1, 0},
    {GW::Constants::MapID::Ascalon_Academy_PvP_battle_mission_2, 0},
    {GW::Constants::MapID::Ascalon_Academy_explorable, 0},
    {GW::Constants::MapID::Burning_Isle_mission, 0},
    {GW::Constants::MapID::Druids_Isle_mission, 0},
    {static_cast<GW::Constants::MapID>(169), 0},
    {GW::Constants::MapID::Frozen_Isle_mission, 0},
    {GW::Constants::MapID::Warriors_Isle_mission, 0},
    {GW::Constants::MapID::Hunters_Isle_mission, 0},
    {GW::Constants::MapID::Wizards_Isle_mission, 0},
    {GW::Constants::MapID::Nomads_Isle_mission, 0},
    {GW::Constants::MapID::Isle_of_the_Dead_guild_hall_mission, 0},
    {GW::Constants::MapID::Frozen_Isle_outpost, 0},
    {GW::Constants::MapID::Nomads_Isle_outpost, 0},
    {GW::Constants::MapID::Druids_Isle_outpost, 0},
    {GW::Constants::MapID::Isle_of_the_Dead_guild_hall_outpost, 0},
    {GW::Constants::MapID::Fort_Koga_mission, 0},
    {GW::Constants::MapID::Amnoon_Arena_mission, 0},
    {GW::Constants::MapID::Deldrimor_Arena_mission, 0},
    {GW::Constants::MapID::The_Crag_mission, 0},
    {GW::Constants::MapID::Sorrows_Furnace, 0},
    {GW::Constants::MapID::All_Call_Click_Point_2, 0},
    {GW::Constants::MapID::Dragons_Thieves, 0},
    {GW::Constants::MapID::Heroes_Crypt_mission, 0},
    {GW::Constants::MapID::Fort_Aspenwood_mission, 0},
    {GW::Constants::MapID::The_Jade_Quarry_mission, 0},
    {GW::Constants::MapID::Grenz_Frontier_mission, 0},
    {GW::Constants::MapID::The_Ancestral_Lands_mission, 0},
    {GW::Constants::MapID::Kaanai_Canyon_mission, 0},
    {GW::Constants::MapID::Dwayna_Vs_Grenth, 0},
    {GW::Constants::MapID::Dwaynas_Camp, 0},
    {GW::Constants::MapID::Grenths_Camp, 0},
    {GW::Constants::MapID::Minister_Chos_Estate_cinematic, 0},
    {GW::Constants::MapID::Zen_Daijun_cinematic, 0},
    {GW::Constants::MapID::The_Jade_Quarry_Kurzick_cinematic, 0},
    {GW::Constants::MapID::Nahpui_Quarter_cinematic, 0},
    {GW::Constants::MapID::Tahnnaka_Temple_cinematic, 0},
    {GW::Constants::MapID::Arborstone_cinematic, 0},
    {GW::Constants::MapID::Boreas_Seabed_cinematic, 0},
    {GW::Constants::MapID::Sunjiang_District_cinematic, 0},
    {GW::Constants::MapID::The_Eternal_Grove_cinematic, 0},
    {GW::Constants::MapID::Gyala_Hatchery_cinematic, 0},
    {GW::Constants::MapID::Raisu_Palace_cinematic, 0},
    {GW::Constants::MapID::Imperial_Sanctum_cinematic, 0},
    {GW::Constants::MapID::Isle_of_Weeping_Stone_outpost, 0},
    {GW::Constants::MapID::Isle_of_Jade_outpost, 0},
    {GW::Constants::MapID::Monastery_Overlook2, 0},
    {GW::Constants::MapID::Saltspray_Beach_mission, 0},
    {GW::Constants::MapID::Etnaran_Keys_mission, 0},
    {GW::Constants::MapID::Vizunah_Square_Local_Quarter_cinematic, 0},
    {GW::Constants::MapID::Vizunah_Square_Foreign_Quarter_cinematic, 0},
    {GW::Constants::MapID::The_Jade_Quarry_Luxon_cinematic, 0},
    {GW::Constants::MapID::Ascalon_Arena_mission, 0},
    {GW::Constants::MapID::Shiverpeak_Arena_mission, 0},
    {GW::Constants::MapID::Travel_Battle_Isles, 0},
    {GW::Constants::MapID::Travel_Tyria, 0},
    {GW::Constants::MapID::Travel_Cantha, 0},
    {GW::Constants::MapID::Fort_Aspenwood_Kurzick_cinematic, 0},
    {GW::Constants::MapID::Fort_Aspenwood_Luxon_cinematic, 0},
    {GW::Constants::MapID::The_Harvest_Ceremony_Kurzick_cinematic, 0},
    {GW::Constants::MapID::The_Harvest_Ceremony_Luxon_cinematic, 0},
    {GW::Constants::MapID::Imperial_Sanctum_explorable, 0},
    {GW::Constants::MapID::Saltspray_Beach_Luxon_outpost, 0},
    {GW::Constants::MapID::Saltspray_Beach_Kurzick_outpost, 0},
    {GW::Constants::MapID::Grenz_Frontier_Luxon_outpost, 0},
    {GW::Constants::MapID::Grenz_Frontier_Kurzick_outpost, 0},
    {GW::Constants::MapID::The_Ancestral_Lands_Luxon_outpost, 0},
    {GW::Constants::MapID::The_Ancestral_Lands_Kurzick_outpost, 0},
    {GW::Constants::MapID::Etnaran_Keys_Luxon_outpost, 0},
    {GW::Constants::MapID::Etnaran_Keys_Kurzick_outpost, 0},
    {GW::Constants::MapID::DAlessio_Arena_mission2, 0},
    {GW::Constants::MapID::Amnoon_Arena_mission2, 0},
    {GW::Constants::MapID::Fort_Koga_mission2, 0},
    {GW::Constants::MapID::Heroes_Crypt_mission2, 0},
    {GW::Constants::MapID::Shiverpeak_Arena_mission2, 0},
    {GW::Constants::MapID::Scarred_Earth, 0},
    {GW::Constants::MapID::Divine_Path, 0},
    {GW::Constants::MapID::Brawlers_Pit_mission, 0},
    {GW::Constants::MapID::Petrified_Arena_mission, 0},
    {GW::Constants::MapID::Seabed_Arena_mission, 0},
    {GW::Constants::MapID::Isle_of_Weeping_Stone_mission, 0},
    {GW::Constants::MapID::Isle_of_Jade_mission, 0},
    {GW::Constants::MapID::Imperial_Isle_mission, 0},
    {GW::Constants::MapID::Isle_of_Meditation_mission, 0},
    {GW::Constants::MapID::Imperial_Isle_outpost, 0},
    {GW::Constants::MapID::Random_Arenas_Test, 0},
    {GW::Constants::MapID::All_Skills, 0},
    {GW::Constants::MapID::Kamadan_mission, 0},
    {GW::Constants::MapID::Fahranur_mission, 0},
    {GW::Constants::MapID::Vortex_Elona, 0},
    {GW::Constants::MapID::Wehhan_Terraces_outpost, 0},
    {GW::Constants::MapID::Yohlon_Haven_outpost, 0},
    {GW::Constants::MapID::Vortex_Realm_of_Torment, 0},
    {GW::Constants::MapID::Lions_Arch_Sunspears_in_Kryta, 0},
    {GW::Constants::MapID::Kaineng_Center_Sunspears_in_Cantha, 0},
    {GW::Constants::MapID::Sebelkeh_Basilica, 0},
    {GW::Constants::MapID::Sun_Docks_cinematic, 0},
    {static_cast<GW::Constants::MapID>(408), 0},
    {static_cast<GW::Constants::MapID>(409), 0},
    {static_cast<GW::Constants::MapID>(410), 0},
    {static_cast<GW::Constants::MapID>(411), 0},
    {static_cast<GW::Constants::MapID>(412), 0},
    {GW::Constants::MapID::Bejunkan_Pier_cinematic, 0},
    {GW::Constants::MapID::Lions_Gate_cinematic, 0},
    {GW::Constants::MapID::Secure_the_Refuge, 0},
    {GW::Constants::MapID::Venta_Cemetery, 0},
    {GW::Constants::MapID::Kamadan_Jewel_of_Istan_explorable, 0},
    {GW::Constants::MapID::The_Tribunal, 0},
    {GW::Constants::MapID::Cliffs_of_Dohjok, 0},
    {GW::Constants::MapID::A_Land_of_Heroes, 0},
    {GW::Constants::MapID::Crystal_Overlook, 0},
    {GW::Constants::MapID::Gate_of_Anguish_elite_mission, 0},
    {GW::Constants::MapID::Secure_the_Refuge_cinematic, 0},
    {GW::Constants::MapID::Evacuation_cinematic, 0},
    {GW::Constants::MapID::Test_Map_solo_areas, 0},
    {GW::Constants::MapID::Nightfallen_Garden, 0},
    {GW::Constants::MapID::Beknur_Harbor, 0},
    {GW::Constants::MapID::Kodonur_Crossroads_cinematic, 0},
    {GW::Constants::MapID::Rilohn_Refuge_cinematic, 0},
    {GW::Constants::MapID::Pogahn_Passage_cinematic, 0},
    {GW::Constants::MapID::Heart_of_Abaddon, 0},
    {GW::Constants::MapID::Nightfallen_Coast, 0},
    {GW::Constants::MapID::Bloodstone_Fen_quest, 0},
    {GW::Constants::MapID::Ooze_Pit_mission, 0},
    {GW::Constants::MapID::Island_of_Shehkah, 0},
    {GW::Constants::MapID::Travel_Elona, 0},
    {GW::Constants::MapID::Bokka_Amphitheatre, 0},
    {GW::Constants::MapID::Throne_of_Secrets, 0},
    {GW::Constants::MapID::Churranu_Island_Arena_mission, 0},
    {GW::Constants::MapID::Shing_Jea_Monastery_mission, 0},
    {GW::Constants::MapID::Haiju_Lagoon_mission, 0},
    {GW::Constants::MapID::Jaya_Bluffs_mission, 0},
    {GW::Constants::MapID::Seitung_Harbor_mission, 0},
    {GW::Constants::MapID::Tsumei_Village_mission, 0},
    {GW::Constants::MapID::Seitung_Harbor_mission_2, 0},
    {GW::Constants::MapID::Tsumei_Village_mission_2, 0},
    {GW::Constants::MapID::Minister_Chos_Estate_mission_2, 0},
    {GW::Constants::MapID::Island_of_Shehkah_cinematic, 0},
    {GW::Constants::MapID::Jokanur_Diggings_cinematic, 0},
    {GW::Constants::MapID::Blacktide_Den_cinematic, 0},
    {GW::Constants::MapID::Consulate_Docks_cinematic, 0},
    {GW::Constants::MapID::Tihark_Orchard_cinematic, 0},
    {GW::Constants::MapID::Dzagonur_Bastion_cinematic, 0},
    {GW::Constants::MapID::Hidden_City_of_Ahdashim_cinematic, 0},
    {GW::Constants::MapID::Grand_Court_of_Sebelkeh_cinematic, 0},
    {GW::Constants::MapID::Jennurs_Horde_cinematic, 0},
    {GW::Constants::MapID::Nundu_Bay_cinematic, 0},
    {GW::Constants::MapID::Gates_of_Desolation_cinematic, 0},
    {GW::Constants::MapID::Ruins_of_Morah_cinematic, 0},
    {GW::Constants::MapID::Domain_of_Pain_cinematic, 0},
    {GW::Constants::MapID::Gate_of_Madness_cinematic, 0},
    {GW::Constants::MapID::Abaddons_Gate_cinematic, 0},
    {GW::Constants::MapID::Uncharted_Isle_outpost, 0},
    {GW::Constants::MapID::Uncharted_Isle_mission, 0},
    {GW::Constants::MapID::Isle_of_Wurms_mission, 0},
    {GW::Constants::MapID::Ahmtur_Arena_mission, 0},
    {GW::Constants::MapID::Sunspear_Arena_mission, 0},
    {GW::Constants::MapID::Isle_of_Solitude_outpost, 0},
    {GW::Constants::MapID::Corrupted_Isle_mission, 0},
    {GW::Constants::MapID::Isle_of_Solitude_mission, 0},
    {GW::Constants::MapID::Bombardment_mission, 0},
    {GW::Constants::MapID::The_Beachhead_mission, 0},
    {GW::Constants::MapID::The_Crossing_mission, 0},
    {GW::Constants::MapID::Desert_Sands_mission, 0},
    //{GW::Constants::MapID::Dajkah_Inlet, 0x3E15C}, //challenge mission, same map id but different map hash, wtf...
    {GW::Constants::MapID::Chahbek_Village_cutscene, 0},
    {GW::Constants::MapID::Throne_Of_Secrets_outpost, 0},
    {GW::Constants::MapID::Cathedral_of_Flames_Level_1, 0},
    {GW::Constants::MapID::The_Troubled_Keeper, 0},
    {GW::Constants::MapID::Fortress_of_Jahai, 0},
    {GW::Constants::MapID::Halls_of_Chokhin, 0},
    {GW::Constants::MapID::Citadel_of_Dzagon, 0},
    {GW::Constants::MapID::Cathedral_of_Flames_Level_2, 0},
    {GW::Constants::MapID::Cathedral_of_Flames_Level_3, 0},
    {GW::Constants::MapID::Catacombs_of_Kathandrax_Level_1, 0},
    {GW::Constants::MapID::Catacombs_of_Kathandrax_Level_2, 0},
    {GW::Constants::MapID::Rragars_Menagerie_Level_1, 0},
    {GW::Constants::MapID::Rragars_Menagerie_Level_2, 0},
    {GW::Constants::MapID::Rragars_Menagerie_Level_3, 0},
    {GW::Constants::MapID::Ooze_Pit, 0},
    {GW::Constants::MapID::Slavers_Exile_Level_1, 0},
    {GW::Constants::MapID::Oolas_Lab_Level_1, 0},
    {GW::Constants::MapID::Oolas_Lab_Level_2, 0},
    {GW::Constants::MapID::Oolas_Lab_Level_3, 0},
    {GW::Constants::MapID::Shards_of_Orr_Level_1, 0},
    {GW::Constants::MapID::Shards_of_Orr_Level_2, 0},
    {GW::Constants::MapID::Shards_of_Orr_Level_3, 0},
    {GW::Constants::MapID::Arachnis_Haunt_Level_1, 0},
    {GW::Constants::MapID::Arachnis_Haunt_Level_2, 0},
    {static_cast<GW::Constants::MapID>(586), 0},
    {static_cast<GW::Constants::MapID>(587), 0},
    {static_cast<GW::Constants::MapID>(588), 0},
    {static_cast<GW::Constants::MapID>(589), 0},
    {static_cast<GW::Constants::MapID>(590), 0},
    {static_cast<GW::Constants::MapID>(591), 0},
    {GW::Constants::MapID::Five_Team_Test, 0},
    {GW::Constants::MapID::Overlook_mission, 0},
    {GW::Constants::MapID::Cemetery_mission, 0},
    {GW::Constants::MapID::Forgotten_Shrines_mission, 0},
    {GW::Constants::MapID::Track_mission, 0},
    {GW::Constants::MapID::Collision_mission, 0},
    {static_cast<GW::Constants::MapID>(601), 0},
    {static_cast<GW::Constants::MapID>(602), 0},
    {static_cast<GW::Constants::MapID>(603), 0},
    {GW::Constants::MapID::Vloxen_Excavations_Level_2, 0},
    {GW::Constants::MapID::Vloxen_Excavations_Level_3, 0},
    {GW::Constants::MapID::Heart_of_the_Shiverpeaks_Level_2, 0},
    {GW::Constants::MapID::Heart_of_the_Shiverpeaks_Level_3, 0},
    {static_cast<GW::Constants::MapID>(610), 0},
    {static_cast<GW::Constants::MapID>(611), 0},
    {GW::Constants::MapID::Bloodstone_Caves_Level_1, 0},
    {GW::Constants::MapID::Bloodstone_Caves_Level_2, 0},
    {GW::Constants::MapID::Bloodstone_Caves_Level_3, 0},
    {GW::Constants::MapID::Bogroot_Growths_Level_1, 0},
    {GW::Constants::MapID::Bogroot_Growths_Level_2, 0},
    {GW::Constants::MapID::Ravens_Point_Level_1, 0},
    {GW::Constants::MapID::Ravens_Point_Level_2, 0},
    {GW::Constants::MapID::Ravens_Point_Level_3, 0},
    {GW::Constants::MapID::Slavers_Exile_Level_2, 0},
    {GW::Constants::MapID::Slavers_Exile_Level_3, 0},
    {GW::Constants::MapID::Slavers_Exile_Level_4, 0},
    {GW::Constants::MapID::Slavers_Exile_Level_5, 0},
    {GW::Constants::MapID::Battledepths_Level_2, 0},
    {GW::Constants::MapID::Battledepths_Level_3, 0},
    {GW::Constants::MapID::Sepulchre_of_Dragrimmar_Level_1, 0},
    {GW::Constants::MapID::Sepulchre_of_Dragrimmar_Level_2, 0},
    {GW::Constants::MapID::Frostmaws_Burrows_Level_1, 0},
    {GW::Constants::MapID::Frostmaws_Burrows_Level_2, 0},
    {GW::Constants::MapID::Frostmaws_Burrows_Level_3, 0},
    {GW::Constants::MapID::Frostmaws_Burrows_Level_4, 0},
    {GW::Constants::MapID::Frostmaws_Burrows_Level_5, 0},
    {GW::Constants::MapID::Darkrime_Delves_Level_1, 0},
    {GW::Constants::MapID::Darkrime_Delves_Level_2, 0},
    {GW::Constants::MapID::Darkrime_Delves_Level_3, 0},
    {GW::Constants::MapID::Curse_of_the_Nornbear, 0},
    {GW::Constants::MapID::Blood_Washes_Blood, 0},
    {GW::Constants::MapID::A_Gate_Too_Far_Level_1, 0},
    {GW::Constants::MapID::A_Gate_Too_Far_Level_2, 0},
    {GW::Constants::MapID::A_Gate_Too_Far_Level_3, 0},
    {GW::Constants::MapID::Finding_the_Bloodstone_Level_1, 0},
    {GW::Constants::MapID::Finding_the_Bloodstone_Level_2, 0},
    {GW::Constants::MapID::Finding_the_Bloodstone_Level_3, 0},
    {GW::Constants::MapID::Genius_Operated_Living_Enchanted_Manifestation, 0},
    {GW::Constants::MapID::Against_the_Charr, 0},
    {GW::Constants::MapID::Warband_of_Brothers_Level_1, 0},
    {GW::Constants::MapID::Warband_of_Brothers_Level_2, 0},
    {GW::Constants::MapID::Warband_of_Brothers_Level_3, 0},
    {GW::Constants::MapID::Assault_on_the_Stronghold, 0},
    {GW::Constants::MapID::Destructions_Depths_Level_1, 0},
    {GW::Constants::MapID::Destructions_Depths_Level_2, 0},
    {GW::Constants::MapID::Destructions_Depths_Level_3, 0},
    {GW::Constants::MapID::Warband_Training, 0},
    {GW::Constants::MapID::Catacombs_of_Kathandrax_Level_3, 0},
    {GW::Constants::MapID::Hall_of_Primordus, 0},
    {GW::Constants::MapID::Attack_of_the_Nornbear, 0},
    {GW::Constants::MapID::Cinematic_Cave_Norn_Cursed, 0},
    {GW::Constants::MapID::Cinematic_Steppe_Interrogation, 0},
    {GW::Constants::MapID::Cinematic_Interior_Research, 0},
    {GW::Constants::MapID::Cinematic_Mountain_Resolution, 0},
    {GW::Constants::MapID::Cold_as_Ice, 0},
    {GW::Constants::MapID::Cinematic_Mountain_Dwarfs, 0},
    {GW::Constants::MapID::Service_In_Defense_of_the_Eye, 0},
    {GW::Constants::MapID::Mano_a_Norn_o, 0},
    {GW::Constants::MapID::Service_Practice_Dummy, 0},
    {GW::Constants::MapID::Hero_Tutorial, 0},
    {GW::Constants::MapID::Prototype_Map, 0},
    {GW::Constants::MapID::Secret_Lair_of_the_Snowmen, 0},
    {GW::Constants::MapID::Norn_Brawling_Championship, 0},
    {GW::Constants::MapID::Kilroys_Punchout_Training, 0},
    {GW::Constants::MapID::The_Justiciars_End, 0},
    {GW::Constants::MapID::Designer_Test_Map, 0},
    {GW::Constants::MapID::The_Great_Norn_Alemoot, 0},
    {GW::Constants::MapID::Varajar_Fells_Bear_Club_quest, 0},
    {GW::Constants::MapID::The_Crossing_mission2, 0},
    {GW::Constants::MapID::Epilogue, 0},
    {GW::Constants::MapID::Insidious_Remnants, 0},
    {GW::Constants::MapID::The_Beachhead_mission2, 0},
    {GW::Constants::MapID::Bombardment_mission2, 0},
    {GW::Constants::MapID::Desert_Sands_mission2, 0},
    {GW::Constants::MapID::MISSION_CINEMATIC_MISSION_PACK_TYRIA_INTRODUCTION, 0},
    {GW::Constants::MapID::The_Battlefield_cinematic, 0},
    {GW::Constants::MapID::Attack_on_Jaliss_Camp, 0},
    {GW::Constants::MapID::The_Hierophants_Stronghold_cinematic, 0},
    {GW::Constants::MapID::The_Asura_Plan_cinematic, 0},
    {GW::Constants::MapID::Creature_Test_Map, 0},
    {GW::Constants::MapID::Costume_Brawl_outpost, 0},
    {GW::Constants::MapID::Whitefury_Rapids_mission, 0},
    {GW::Constants::MapID::Kysten_Shore_mission, 0},
    {GW::Constants::MapID::Deepway_Ruins_mission, 0},
    {GW::Constants::MapID::Plikkup_Works_mission, 0},
    {GW::Constants::MapID::Special_Ops_Flame_Temple_Corridor, 0},
    {GW::Constants::MapID::Special_Ops_Dragons_Gullet, 0}}},
  {0x36b4,
   {{GW::Constants::MapID::The_Hall_of_Heroes_arena_mission, 0x36b4},
    {GW::Constants::MapID::The_Hall_of_Heroes, 0x36b4},
    {GW::Constants::MapID::The_Hall_of_Heroes2, 0x36b4}}},
  {0x36a5,
   {{GW::Constants::MapID::The_Courtyard_arena_mission, 0x36a5},
    {GW::Constants::MapID::The_Courtyard, 0x36a5}}},
  {0x3bb2,
   {{GW::Constants::MapID::Burial_Mounds_mission, 0x3bb2}}},
  {0x402c,
   {{GW::Constants::MapID::The_Underworld_gvg_mission, 0x402c},
    {GW::Constants::MapID::The_Underworld_guild_hall, 0x402c},
    {GW::Constants::MapID::The_Underworld_guild_hall_preview, 0x402c},
    {GW::Constants::MapID::The_Underworld_PvP, 0x402c},
    {GW::Constants::MapID::The_Underworld2, 0x402c},
    {GW::Constants::MapID::The_Underworld3, 0x402c},
    {GW::Constants::MapID::The_Underworld_arena_mission, 0x402c}}},
  {0x46d8a,
   {{GW::Constants::MapID::Fetid_River_mission, 0x46d8a}}},
  {0x2fed,
   {{GW::Constants::MapID::DEV_Test_Arena_1v1, 0x2fed}}},
  {0x340c6,
   {{GW::Constants::MapID::Test_map, 0x340c6},
    {GW::Constants::MapID::Yohlon_Haven_outpost, 0x340c6}}},
  {0x1f22c,
   {{GW::Constants::MapID::Wizards_Isle_outpost, 0x1f22c},
    {GW::Constants::MapID::Wizards_Isle, 0x1f22c}}},
  {0x1f1fc,
   {{GW::Constants::MapID::Warriors_Isle, 0x1f1fc}}},
  {0x1f208,
   {{GW::Constants::MapID::Hunters_Isle, 0x1f208}}},
  {0x34db,
   {{GW::Constants::MapID::Bloodstone_Fen, 0x34db}}},
  {0x9f5c,
   {{GW::Constants::MapID::The_Wilds, 0x9f5c}}},
  {0x3331,
   {{GW::Constants::MapID::Aurora_Glade, 0x3331}}},
  {0x3a58,
   {{GW::Constants::MapID::Diessa_Lowlands, 0x3a58},
    {GW::Constants::MapID::Grendich_Courthouse_outpost, 0x3a58}}},
  {0x8a33,
   {{GW::Constants::MapID::Gates_of_Kryta, 0x8a33},
    {GW::Constants::MapID::Sunjiang_District_explorable, 0x8a33}}},
  {0x837f,
   {{GW::Constants::MapID::DAlessio_Seaboard, 0x837f}}},
  {0x8381,
   {{GW::Constants::MapID::Divinity_Coast, 0x8381}}},
  {0x84f7,
   {{GW::Constants::MapID::Talmark_Wilderness, 0x84f7}}},
  {0x56FA8,
   {{GW::Constants::MapID::War_in_Kryta_Talmark_Wilderness, 0x56FA8}}},
  {0x84fd,
   {{GW::Constants::MapID::The_Black_Curtain, 0x84fd},
    {GW::Constants::MapID::Temple_of_the_Ages, 0x84fd}}},
  {0x9160,
   {{GW::Constants::MapID::Sanctum_Cay, 0x9160}}},
  {0x836a,
   {{GW::Constants::MapID::Droknars_Forge_outpost, 0x836a}}},
  {0x33d1,
   {{GW::Constants::MapID::The_Frost_Gate, 0x33d1}}},
  {0x2f08,
   {{GW::Constants::MapID::Ice_Caves_of_Sorrow, 0x2f08}}},
  {0x2d2d,
   {{GW::Constants::MapID::Thunderhead_Keep, 0x2d2d}}},
  {0xba2c,
   {{GW::Constants::MapID::Iron_Mines_of_Moladune, 0xba2c}}},
  {0x32db,
   {{GW::Constants::MapID::Borlis_Pass, 0x32db}}},
  {0xb5fd,
   {{GW::Constants::MapID::Talus_Chute, 0xb5fd}}},
  {0xB5FE,
   {{GW::Constants::MapID::Griffons_Mouth, 0xB5FE}}},
  {0x3600,
   {{GW::Constants::MapID::The_Great_Northern_Wall, 0x3600}}},
  {0x3652,
   {{GW::Constants::MapID::Fort_Ranik, 0x3652}}},
  {0x3653,
   {{GW::Constants::MapID::Ruins_of_Surmia, 0x3653}}},
  {0x265f0,
   {{GW::Constants::MapID::Xaquang_Skyway, 0x265f0},
    {GW::Constants::MapID::Senjis_Corner_outpost, 0x265f0}}},
  {0x3659,
   {{GW::Constants::MapID::Nolani_Academy, 0x3659}}},
  {0x3a59,
   {{GW::Constants::MapID::Old_Ascalon, 0x3a59},
    {GW::Constants::MapID::Sardelac_Sanitarium_outpost, 0x3a59}}},
  {0xd90b,
   {{GW::Constants::MapID::Ember_Light_Camp_outpost, 0xd90b},
    {GW::Constants::MapID::Perdition_Rock, 0xd90b}}},
  {0x252c9,
   {{GW::Constants::MapID::Glints_Challenge_mission, 0x252c9}}},
  {0xce65,
   {{GW::Constants::MapID::Augury_Rock_outpost, 0xce65},
    {GW::Constants::MapID::Skyward_Reach, 0xce65},
    {GW::Constants::MapID::Augury_Rock_mission, 0xce65}}},
  {0xc775,
   {{GW::Constants::MapID::Piken_Square_outpost, 0xc775},
    {GW::Constants::MapID::The_Breach, 0xc775}}},
  {0x9f63,
   {{GW::Constants::MapID::Sage_Lands, 0x9f63},
    {GW::Constants::MapID::Druids_Overlook_outpost, 0x9f63}}},
  {0x9f69,
   {{GW::Constants::MapID::Mamnoon_Lagoon, 0x9f69}}},
  {0x9f6c,
   {{GW::Constants::MapID::Silverwood, 0x9f6c},
    {GW::Constants::MapID::Quarrel_Falls_outpost, 0x9f6c}}},
  {0x9f5e,
   {{GW::Constants::MapID::Ettins_Back, 0x9f5e},
    {GW::Constants::MapID::Ventaris_Refuge_outpost, 0x9f5e}}},
  {0x9f62,
   {{GW::Constants::MapID::Reed_Bog, 0x9f62}}},
  {0x9f68,
   {{GW::Constants::MapID::The_Falls, 0x9f68}}},
  {0x9f61,
   {{GW::Constants::MapID::Dry_Top, 0x9f61}}},
  {0x9f6b,
   {{GW::Constants::MapID::Tangle_Root, 0x9f6b},
    {GW::Constants::MapID::Maguuma_Stade_outpost, 0x9f6b}}},
  {0x9f37,
   {{GW::Constants::MapID::Henge_of_Denravi_outpost, 0x9f37}}},
  {0x1f24d,
   {{GW::Constants::MapID::Burning_Isle_outpost, 0x1f24d},
    {GW::Constants::MapID::Burning_Isle, 0x1f24d}}},
  {0xa0e8,
   {{GW::Constants::MapID::Tears_of_the_Fallen, 0xa0e8}}},
  {0xa0e9,
   {{GW::Constants::MapID::Scoundrels_Rise, 0xa0e9}}},
  {0x34fd,
   {{GW::Constants::MapID::Lions_Arch_outpost, 0x34fd}}},
  {0x85a8,
   {{GW::Constants::MapID::Cursed_Lands, 0x85a8},
    {GW::Constants::MapID::Bergen_Hot_Springs_outpost, 0x85a8},
    {GW::Constants::MapID::Nebo_Terrace, 0x85a8}}},
  {0x4e706,
   {{GW::Constants::MapID::North_Kryta_Province, 0x4e706}}},
  {0x8610,
   {{GW::Constants::MapID::Majestys_Rest, 0x8610}}},
  {0x8611,
   {{GW::Constants::MapID::Twin_Serpent_Lakes, 0x8611}}},
  {0x85ae,
   {{GW::Constants::MapID::Watchtower_Coast, 0x85ae},
    {GW::Constants::MapID::Beetletun_outpost, 0x85ae}}},
  {0x85e9,
   {{GW::Constants::MapID::Stingray_Strand, 0x85e9},
    {GW::Constants::MapID::Fishermens_Haven_outpost, 0x85e9}}},
  {0x85b1,
   {{GW::Constants::MapID::Kessex_Peak, 0x85b1}}},
  {0x1f265,
   {{GW::Constants::MapID::Frozen_Isle, 0x1f265}}},
  {0x1f268,
   {{GW::Constants::MapID::Nomads_Isle, 0x1f268}}},
  {0x1f27a,
   {{GW::Constants::MapID::Druids_Isle, 0x1f27a}}},
  {0x1f29b,
   {{GW::Constants::MapID::Isle_of_the_Dead_guild_hall, 0x1f29b}}},
  {0x29ba,
   {{GW::Constants::MapID::Riverside_Province, 0x29ba}}},
  {0x25e13,
   {{GW::Constants::MapID::House_zu_Heltzer_outpost, 0x25e13},
    {GW::Constants::MapID::Altrumm_Ruins, 0x25e13}}},
  {0x5624,
   {{GW::Constants::MapID::Ascalon_City_outpost, 0x5624},
    {GW::Constants::MapID::Ascalon_Arena, 0x5624}}},
  {0x288a0,
   {{GW::Constants::MapID::Tomb_of_the_Primeval_Kings, 0x288a0}}},
  {0xb5ff,
   {{GW::Constants::MapID::Icedome, 0xb5ff}}},
  {0xb600,
   {{GW::Constants::MapID::Iron_Horse_Mine, 0xb600}}},
  {0xb601,
   {{GW::Constants::MapID::Anvil_Rock, 0xb601},
    {GW::Constants::MapID::Ice_Tooth_Cave_outpost, 0xb601}}},
  {0xb602,
   {{GW::Constants::MapID::Lornars_Pass, 0xb602},
    {GW::Constants::MapID::Beacons_Perch_outpost, 0xb602}}},
  {0x2fd4,
   {{GW::Constants::MapID::Snake_Dance, 0x2fd4},
    {GW::Constants::MapID::Camp_Rankor_outpost, 0x2fd4}}},
  {0xb605,
   {{GW::Constants::MapID::Tascas_Demise, 0xb605},
    {GW::Constants::MapID::Spearhead_Peak, 0xb605},
    {GW::Constants::MapID::The_Granite_Citadel_outpost, 0xb605}}},
  {0xb606,
   {{GW::Constants::MapID::Ice_Floe, 0xb606},
    {GW::Constants::MapID::Marhans_Grotto_outpost, 0xb606}}},
  {0xb607,
   {{GW::Constants::MapID::Witmans_Folly, 0xb607},
    {GW::Constants::MapID::Port_Sledge_outpost, 0xb607}}},
  {0xb608,
   {{GW::Constants::MapID::Mineral_Springs, 0xb608}}},
  {0xb609,
   {{GW::Constants::MapID::Dreadnoughts_Drift, 0xb609}}},
  {0xb60a,
   {{GW::Constants::MapID::Frozen_Forest, 0xb60a},
    {GW::Constants::MapID::Copperhammer_Mines_outpost, 0xb60a}}},
  {0xb60b,
   {{GW::Constants::MapID::Travelers_Vale, 0xb60b},
    {GW::Constants::MapID::Yaks_Bend_outpost, 0xb60b},
    {GW::Constants::MapID::Shiverpeak_Arena, 0xb60b},
    {GW::Constants::MapID::Shiverpeak_Arena_mission3, 0xb60b}}},
  {0xb60c,
   {{GW::Constants::MapID::Deldrimor_Bowl, 0xb60c}}},
  {0xc774,
   {{GW::Constants::MapID::Regent_Valley, 0xc774}}},
  {0xc776,
   {{GW::Constants::MapID::Ascalon_Foothills, 0xc776}}},
  {0xc777,
   {{GW::Constants::MapID::Pockmark_Flats, 0xc777},
    {GW::Constants::MapID::Serenity_Temple_outpost, 0xc777}}},
  {0xc778,
   {{GW::Constants::MapID::Dragons_Gullet, 0xc778},
    {GW::Constants::MapID::Flame_Temple_Corridor, 0xc778}}},
  {0xc77a,
   {{GW::Constants::MapID::Eastern_Frontier, 0xc77a},
    {GW::Constants::MapID::Frontier_Gate_outpost, 0xc77a}}},
  {0xcbc6,
   {{GW::Constants::MapID::The_Scar, 0xcbc6},
    {GW::Constants::MapID::Destinys_Gorge_outpost, 0xcbc6}}},
  {0xceb6,
   {{GW::Constants::MapID::The_Amnoon_Oasis_outpost, 0xceb6},
    {GW::Constants::MapID::Amnoon_Arena_mission3, 0xceb6}}},
  {0xce55,
   {{GW::Constants::MapID::Diviners_Ascent, 0xce55}}},
  {0xce56,
   {{GW::Constants::MapID::Vulture_Drifts, 0xce56}}},
  {0xce5e,
   {{GW::Constants::MapID::The_Arid_Sea, 0xce5e}}},
  {0xce63,
   {{GW::Constants::MapID::Prophets_Path, 0xce63},
    {GW::Constants::MapID::Heroes_Audience_outpost, 0xce63}}},
  {0xce64,
   {{GW::Constants::MapID::Salt_Flats, 0xce64},
    {GW::Constants::MapID::Seekers_Passage_outpost, 0xce64}}},
  {0xce66,
   {{GW::Constants::MapID::Dunes_of_Despair, 0xce66}}},
  {0xce67,
   {{GW::Constants::MapID::Thirsty_River, 0xce67}}},
  {0xce68,
   {{GW::Constants::MapID::Elona_Reach, 0xce68}}},
  {0xce6a,
   {{GW::Constants::MapID::The_Dragons_Lair, 0xce6a}}},
  {0xd900,
   {{GW::Constants::MapID::Ring_of_Fire, 0xd900}}},
  {0xd907,
   {{GW::Constants::MapID::Abaddons_Mouth, 0xd907}}},
  {0xd908,
   {{GW::Constants::MapID::Hells_Precipice, 0xd908}}},
  {0xd941,
   {{GW::Constants::MapID::Golden_Gates_mission, 0xd941}}},
  {0x25e1d,
   {{GW::Constants::MapID::The_Eternal_Grove, 0x25e1d},
    {GW::Constants::MapID::Vasburg_Armory_outpost, 0x25e1d},
    {GW::Constants::MapID::The_Eternal_Grove_outpost_mission, 0x25e1d}}},
  {0x25bde,
   {{GW::Constants::MapID::Lutgardis_Conservatory_outpost, 0x25bde},
    {GW::Constants::MapID::Melandrus_Hope, 0x25bde}}},
  {0x25e1f,
   {{GW::Constants::MapID::Gyala_Hatchery, 0x25e1f},
    {GW::Constants::MapID::Gyala_Hatchery_outpost_mission, 0x25e1f},
    {GW::Constants::MapID::Leviathan_Pits_outpost, 0x25e1f}}},
  {0x1c530,
   {{GW::Constants::MapID::The_Catacombs, 0x1c530}}},
  {0x1b97d,
   {{GW::Constants::MapID::Lakeside_County, 0x1b97d},
    {GW::Constants::MapID::Ascalon_City_pre_searing, 0x1b97d},
    {GW::Constants::MapID::Ashford_Abbey_outpost, 0x1b97d}}},
  {0x1c539,
   {{GW::Constants::MapID::The_Northlands, 0x1c539},
    {GW::Constants::MapID::Piken_Square_pre_Searing_outpost, 0x1c539}}},
  {0x5E78F,
   {{GW::Constants::MapID::Forsaken_Tunnels_Presearing_Level1, 0x5E78F}}},
  {0x5E9F9, 
   {{static_cast<GW::Constants::MapID>(880)/*"Tunnels of the Forsaken"*/, 0x5E9F9}}}, //fix this in gwca
  {0x5E9FA, 
   {{static_cast<GW::Constants::MapID>(881)/*"Tunnels of the Forsaken: Level 2"*/, 0x5E9FA}}}, //fix this in gwca
  {0x1bb1d,
   {{GW::Constants::MapID::Regent_Valley_pre_Searing, 0x1bb1d},
    {GW::Constants::MapID::Fort_Ranik_pre_Searing_outpost, 0x1bb1d}}},
  {0x1ba26,
   {{GW::Constants::MapID::Green_Hills_County, 0x1ba26},
    {GW::Constants::MapID::The_Barradin_Estate_outpost, 0x1ba26}}},
  {0x1bacb,
   {{GW::Constants::MapID::Wizards_Folly, 0x1bacb},
    {GW::Constants::MapID::Foibles_Fair_outpost, 0x1bacb}}},
  {0x284db,
   {{GW::Constants::MapID::Random_Arenas_outpost, 0x284db}}},
  {0x28538,
   {{GW::Constants::MapID::Team_Arenas_outpost, 0x28538}}},
  {0x2527c,
   {{GW::Constants::MapID::Sorrows_Furnace, 0x2527c}}},
  {0x25289,
   {{GW::Constants::MapID::Grenths_Footprint, 0x25289},
    {GW::Constants::MapID::Deldrimor_War_Camp_outpost, 0x25289}}},
  {0x25e15,
   {{GW::Constants::MapID::Cavalon_outpost, 0x25e15},
    {GW::Constants::MapID::Zos_Shivros_Channel, 0x25e15}}},
  {0x265f7,
   {{GW::Constants::MapID::Kaineng_Center_outpost, 0x265f7},
    {GW::Constants::MapID::Bejunkan_Pier, 0x265f7}}},
  {0x25b9f,
   {{GW::Constants::MapID::Drazach_Thicket, 0x25b9f},
    {GW::Constants::MapID::Brauer_Academy_outpost, 0x25b9f}}},
  {0x26526,
   {{GW::Constants::MapID::Jaya_Bluffs, 0x26526}}},
  {0x265f1,
   {{GW::Constants::MapID::Shenzun_Tunnels, 0x265f1}}},
  {0x25dc3,
   {{GW::Constants::MapID::Archipelagos, 0x25dc3}}},
  {0x25d0d,
   {{GW::Constants::MapID::Maishang_Hills, 0x25d0d},
    {GW::Constants::MapID::Bai_Paasu_Reach_outpost, 0x25d0d},
    {GW::Constants::MapID::Eredon_Terrace_outpost, 0x25d0d}}},
  {0x25dd1,
   {{GW::Constants::MapID::Mount_Qinkai, 0x25dd1},
    {GW::Constants::MapID::Breaker_Hollow_outpost, 0x25dd1}}},
  {0x25df1,
   {{GW::Constants::MapID::Rheas_Crater, 0x25df1},
    {GW::Constants::MapID::Seafarers_Rest_outpost, 0x25df1}}},
  {0x25e0e,
   {{GW::Constants::MapID::Silent_Surf, 0x25e0e}}},
  {0x25e20,
   {{GW::Constants::MapID::Unwaking_Waters_mission, 0x25e20},
    {GW::Constants::MapID::Unwaking_Waters, 0x25e20},
    {GW::Constants::MapID::Harvest_Temple_outpost, 0x25e20},
    {GW::Constants::MapID::Unwaking_Waters_Luxon_outpost, 0x25e20},
    {GW::Constants::MapID::Unwaking_Waters_Kurzick_outpost, 0x25e20}}},
  {0x25c0e,
   {{GW::Constants::MapID::Morostav_Trail, 0x25c0e}}},
  {0x2663a,
   {{GW::Constants::MapID::Mourning_Veil_Falls, 0x2663a},
    {GW::Constants::MapID::Durheim_Archives_outpost, 0x2663a}}},
  {0x25c34,
   {{GW::Constants::MapID::Ferndale, 0x25c34},
    {GW::Constants::MapID::Saint_Anjekas_Shrine_outpost, 0x25c34}}},
  {0x25e0f,
   {{GW::Constants::MapID::Pongmei_Valley, 0x25e0f},
    {GW::Constants::MapID::Maatu_Keep_outpost, 0x25e0f},
    {GW::Constants::MapID::Tanglewood_Copse_outpost, 0x25e0f}}},
  {0x26529,
   {{GW::Constants::MapID::Monastery_Overlook1, 0x26529},
    {GW::Constants::MapID::Shing_Jea_Monastery_outpost, 0x26529},
    {GW::Constants::MapID::Seitung_Harbor_outpost, 0x26529},
    {GW::Constants::MapID::Linnok_Courtyard, 0x26529},
    {GW::Constants::MapID::Saoshang_Trail, 0x26529},
    {GW::Constants::MapID::Monastery_Overlook_cinematic, 0x26529}}},
  {0x264d2,
   {{GW::Constants::MapID::Zen_Daijun_outpost_mission, 0x264d2},
    {GW::Constants::MapID::Zen_Daijun_explorable, 0x264d2}}},
  {0x2649b,
   {{GW::Constants::MapID::Minister_Chos_Estate_outpost_mission, 0x2649b},
    {GW::Constants::MapID::Minister_Chos_Estate_explorable, 0x2649b}}},
  {0x265f8,
   {{GW::Constants::MapID::Vizunah_Square_mission, 0x265f8},
    {GW::Constants::MapID::Shadows_Passage, 0x265f8},
    {GW::Constants::MapID::Vizunah_Square_Local_Quarter_outpost, 0x265f8},
    {GW::Constants::MapID::Vizunah_Square_Foreign_Quarter_outpost, 0x265f8}}},
  {0x265f9,
   {{GW::Constants::MapID::Nahpui_Quarter_outpost_mission, 0x265f9},
    {GW::Constants::MapID::Nahpui_Quarter_explorable, 0x265f9}}},
  {0x265fa,
   {{GW::Constants::MapID::Tahnnakai_Temple_outpost_mission, 0x265fa},
    {GW::Constants::MapID::Tahnnakai_Temple_explorable, 0x265fa},
    {GW::Constants::MapID::Zin_Ku_Corridor_outpost, 0x265fa}}},
  {0x25e16,
   {{GW::Constants::MapID::Arborstone_outpost_mission, 0x25e16},
    {GW::Constants::MapID::Arborstone_explorable, 0x25e16}}},
  {0x25e17,
   {{GW::Constants::MapID::Boreas_Seabed_outpost_mission, 0x25e17},
    {GW::Constants::MapID::Boreas_Seabed_explorable, 0x25e17}}},
  {0x265fb,
   {{GW::Constants::MapID::Sunjiang_District_outpost_mission, 0x265fb}}},
  {0x2661c,
   {{GW::Constants::MapID::Raisu_Palace_outpost_mission, 0x2661c},
    {GW::Constants::MapID::Raisu_Palace, 0x2661c},
    {GW::Constants::MapID::Raisu_Pavilion, 0x2661c}}},
  {0x2661d,
   {{GW::Constants::MapID::Imperial_Sanctum_outpost_mission, 0x2661d}}},
  {0x25e24,
   {{GW::Constants::MapID::Amatz_Basin, 0x25e24}}},
  {0x25e28,
   {{GW::Constants::MapID::The_Aurios_Mines, 0x25e28}}},
  {0x2655d,
   {{GW::Constants::MapID::Panjiang_Peninsula, 0x2655d}}},
  {0x26578,
   {{GW::Constants::MapID::Kinya_Province, 0x26578},
    {GW::Constants::MapID::Ran_Musu_Gardens_outpost, 0x26578}}},
  {0x26597,
   {{GW::Constants::MapID::Haiju_Lagoon, 0x26597}}},
  {0x2659f,
   {{GW::Constants::MapID::Sunqua_Vale, 0x2659f},
    {GW::Constants::MapID::Tsumei_Village_outpost, 0x2659f}}},
  {0x265ef,
   {{GW::Constants::MapID::Wajjun_Bazaar, 0x265ef},
    {GW::Constants::MapID::Kaineng_Docks, 0x265ef},
    {GW::Constants::MapID::The_Marketplace_outpost, 0x265ef}}},
  {0x4e70b,
   {{GW::Constants::MapID::Bukdek_Byway, 0x4e70b}}},
  {0x265f4,
   {{GW::Constants::MapID::The_Undercity, 0x265f4}}},
  {0x2661e,
   {{GW::Constants::MapID::Shing_Jea_Arena, 0x2661e},
    {GW::Constants::MapID::Shing_Jea_Arena_mission, 0x2661e}}},
  {0x287b3,
   {{GW::Constants::MapID::Great_Temple_of_Balthazar_outpost, 0x287b3},
    {GW::Constants::MapID::Isle_of_the_Nameless, 0x287b3}}},
  {0x28fb4,
   {{GW::Constants::MapID::Urgozs_Warren, 0x28fb4}}},
  {0x28fb8,
   {{GW::Constants::MapID::Dragons_Throat, 0x28fb8}}},
  {0x287c2,
   {{GW::Constants::MapID::Zaishen_Challenge_outpost, 0x287c2}}},
  {0x287d2,
   {{GW::Constants::MapID::Zaishen_Elite_outpost, 0x287d2}}},
  {0x28f32,
   {{GW::Constants::MapID::Annihilation_mission, 0x28f32},
    {GW::Constants::MapID::Kill_Count_Training_mission, 0x28f32},
    {GW::Constants::MapID::Priest_Annihilation_Training, 0x28f32}}},
  {0x28f33,
   {{GW::Constants::MapID::Obelisk_Annihilation_Training_mission, 0x28f33}}},
  {0x25e1c,
   {{GW::Constants::MapID::Fort_Aspenwood_Luxon_outpost, 0x25e1c},
    {GW::Constants::MapID::Fort_Aspenwood_Kurzick_outpost, 0x25e1c},
    {GW::Constants::MapID::Aspenwood_Gate_Kurzick_outpost, 0x25e1c},
    {GW::Constants::MapID::Aspenwood_Gate_Luxon_outpost, 0x25e1c}}},
  {0x25e1e,
   {{GW::Constants::MapID::The_Jade_Quarry_Luxon_outpost, 0x25e1e},
    {GW::Constants::MapID::The_Jade_Quarry_Kurzick_outpost, 0x25e1e},
    {GW::Constants::MapID::Jade_Flats_Kurzick_outpost, 0x25e1e},
    {GW::Constants::MapID::Jade_Flats_Luxon_outpost, 0x25e1e}}},
  {0x3094b,
   {{GW::Constants::MapID::Kaineng_Center_Canthan_New_Year_outpost, 0x3094b}}},
  {0x2e195,
   {{GW::Constants::MapID::The_Deep, 0x2e195}}},
  {0x1f1c4,
   {{GW::Constants::MapID::DAlessio_Arena_mission3, 0x1f1c4}}},
  {0xe9f6,
   {{GW::Constants::MapID::Fort_Koga_mission3, 0xe9f6}}},
  {0x25a0b,
   {{GW::Constants::MapID::Heroes_Crypt_mission3, 0x25a0b}}},
  {0x2879c,
   {{GW::Constants::MapID::Heroes_Ascent_outpost, 0x2879c}}},
  {0x2e6b6,
   {{GW::Constants::MapID::Kaanai_Canyon_Luxon_outpost, 0x2e6b6},
    {GW::Constants::MapID::Kaanai_Canyon_Kurzick_outpost, 0x2e6b6}}},
  {0x28784,
   {{GW::Constants::MapID::Isle_of_Meditation_outpost, 0x28784},
    {GW::Constants::MapID::Isle_of_Meditation, 0x28784}}},
  {0x2661f,
   {{GW::Constants::MapID::Isle_of_Weeping_Stone, 0x2661f}}},
  {0x26625,
   {{GW::Constants::MapID::Isle_of_Jade, 0x26625}}},
  {0x28736,
   {{GW::Constants::MapID::Imperial_Isle, 0x28736}}},
  {0x3093b,
   {{GW::Constants::MapID::Dragon_Arena, 0x3093b}}},
  {0x353e3,
   {{GW::Constants::MapID::Jahai_Bluffs, 0x353e3}}},
  {0x33f27,
   {{GW::Constants::MapID::Marga_Coast, 0x33f27},
    {GW::Constants::MapID::Nundu_Bay, 0x33f27}}},
  {0x33f6c,
   {{GW::Constants::MapID::Sunward_Marches, 0x33f6c},
    {GW::Constants::MapID::Venta_Cemetery, 0x33f6c}}},
  {0x33ff0,
   {{GW::Constants::MapID::Barbarous_Shore, 0x33ff0},
    {GW::Constants::MapID::Camp_Hojanu_outpost, 0x33ff0}}},
  {0x34913,
   {{GW::Constants::MapID::Bahdok_Caverns, 0x34913},
    {GW::Constants::MapID::Moddok_Crevice, 0x34913}}},
  {0x33ff3,
   {{GW::Constants::MapID::Wehhan_Terraces_outpost, 0x33ff3}}},
  {0x34897,
   {{GW::Constants::MapID::Dejarin_Estate, 0x34897}}},
  {0x356df,
   {{GW::Constants::MapID::Arkjok_Ward, 0x356df}}},
  {0x34873,
   {{GW::Constants::MapID::Gandara_the_Moon_Fortress, 0x34873}}},
  {0x34435,
   {{GW::Constants::MapID::The_Floodplain_of_Mahnkelon, 0x34435},
    {GW::Constants::MapID::Rilohn_Refuge, 0x34435}}},
  {0x3572d,
   {{GW::Constants::MapID::Turais_Procession, 0x3572d}}},
  {0x34c38,
   {{GW::Constants::MapID::Sunspear_Sanctuary_outpost, 0x34c38},
    {GW::Constants::MapID::Command_Post, 0x34c38}}},
  {0x3385e,
   {{GW::Constants::MapID::Yatendi_Canyons, 0x3385e},
    {GW::Constants::MapID::Chantry_of_Secrets_outpost, 0x3385e}}},
  {0x34a54,
   {{GW::Constants::MapID::Garden_of_Seborhin, 0x34a54}}},
  {0x34f33,
   {{GW::Constants::MapID::Holdings_of_Chokhin, 0x34f33}}},
  {0x33883,
   {{GW::Constants::MapID::Mihanu_Township_outpost, 0x33883}}},
  {0x3503d,
   {{GW::Constants::MapID::Vehjin_Mines, 0x3503d}}},
  {0x33bf5,
   {{GW::Constants::MapID::Basalt_Grotto_outpost, 0x33bf5}}},
  {0x3513b,
   {{GW::Constants::MapID::Forum_Highlands, 0x3513b},
    {GW::Constants::MapID::Tihark_Orchard, 0x3513b}}},
  {0x33dc4,
   {{GW::Constants::MapID::Resplendent_Makuun, 0x33dc4},
    {GW::Constants::MapID::Honur_Hill_outpost, 0x33dc4},
    {GW::Constants::MapID::Bokka_Amphitheatre, 0x33dc4}}},
  {0x34b0a,
   {{GW::Constants::MapID::Wilderness_of_Bahdza, 0x34b0a}}},
  {0x35363,
   {{GW::Constants::MapID::Vehtendi_Valley, 0x35363}}},
  {0x33dd6,
   {{GW::Constants::MapID::Yahnur_Market_outpost, 0x33dd6}}},
  {0x33e11,
   {{GW::Constants::MapID::The_Hidden_City_of_Ahdashim, 0x33e11},
    {GW::Constants::MapID::Dasha_Vestibule, 0x33e11}}},
  {0x34c07,
   {{GW::Constants::MapID::The_Kodash_Bazaar_outpost, 0x34c07}}},
  {0x2f9fa,
   {{GW::Constants::MapID::Lions_Gate, 0x2f9fa}}},
  {0x33bdf,
   {{GW::Constants::MapID::The_Mirror_of_Lyss, 0x33bdf},
    {GW::Constants::MapID::Grand_Court_of_Sebelkeh, 0x33bdf}}},
  {0x33e6a,
   {{GW::Constants::MapID::Kodonur_Crossroads, 0x33e6a}}},
  {0x340df,
   {{GW::Constants::MapID::Pogahn_Passage, 0x340df}}},
  {0x345cc,
   {{GW::Constants::MapID::Consulate, 0x345cc},
    {GW::Constants::MapID::Kamadan_Jewel_of_Istan_outpost, 0x345cc},
    {GW::Constants::MapID::Consulate_Docks, 0x345cc},
    {GW::Constants::MapID::Sun_Docks, 0x345cc}}},
  {0x4e70d,
   {{GW::Constants::MapID::Plains_of_Jarin, 0x4e70d}}},
  {0x33651,
   {{GW::Constants::MapID::Sunspear_Great_Hall_outpost, 0x33651}}},
  {0x33dcc,
   {{GW::Constants::MapID::Dzagonur_Bastion, 0x33dcc}}},
  {0x33516,
   {{GW::Constants::MapID::Jokos_Domain, 0x33516},
    {GW::Constants::MapID::Bone_Palace_outpost, 0x33516}}},
  {0x33574,
   {{GW::Constants::MapID::The_Ruptured_Heart, 0x33574},
    {GW::Constants::MapID::The_Mouth_of_Torment_outpost, 0x33574}}},
  {0x34ce4,
   {{GW::Constants::MapID::The_Shattered_Ravines, 0x34ce4}}},
  {0x33583,
   {{GW::Constants::MapID::Lair_of_the_Forgotten_outpost, 0x33583}}},
  {0x34cf1,
   {{GW::Constants::MapID::Poisoned_Outcrops, 0x34cf1}}},
  {0x34b79,
   {{GW::Constants::MapID::The_Sulfurous_Wastes, 0x34b79}}},
  {0x33594,
   {{GW::Constants::MapID::The_Alkali_Pan, 0x33594},
    {GW::Constants::MapID::Ruins_of_Morah, 0x33594}}},
  {0x34cf7,
   {{GW::Constants::MapID::Crystal_Overlook, 0x34cf7}}},
  {0x3452b,
   {{GW::Constants::MapID::Gate_of_Torment_outpost, 0x3452b},
    {GW::Constants::MapID::Gate_of_Fear_outpost, 0x3452b},
    {GW::Constants::MapID::Gate_of_Secrets_outpost, 0x3452b},
    {GW::Constants::MapID::Gate_of_Pain, 0x3452b},
    {GW::Constants::MapID::Gate_of_Madness, 0x3452b},
    {GW::Constants::MapID::Gate_of_the_Nightfallen_Lands_outpost, 0x3452b}}},
  {0x3cdc9,
   {{GW::Constants::MapID::Churrhir_Fields, 0x3cdc9},
    {GW::Constants::MapID::Island_of_Shehkah, 0x3cdc9},
    {GW::Constants::MapID::Island_of_Shehkah_cinematic, 0x3cdc9},
    {GW::Constants::MapID::Chahbek_Village, 0x3cdc9}}},
  {0x35821,
   {{GW::Constants::MapID::Nightfallen_Jahai, 0x35821}}},
  {0x34bf9,
   {{GW::Constants::MapID::Depths_of_Madness, 0x34bf9}}},
  {0x44e8a,
   {{GW::Constants::MapID::Rollerbeetle_Racing, 0x44e8a}}},
  {0x35832,
   {{GW::Constants::MapID::Domain_of_Fear, 0x35832}}},
  {0x34bcc,
   {{GW::Constants::MapID::Domain_of_Pain, 0x34bcc}}},
  {0x3583e,
   {{GW::Constants::MapID::Domain_of_Secrets, 0x3583e}}},
  {0x3584f,
   {{GW::Constants::MapID::Domain_of_Anguish, 0x3584f},
    {GW::Constants::MapID::The_Ebony_Citadel_of_Mallyx_mission, 0x3584f}}},
  {0x33c20,
   {{GW::Constants::MapID::Jennurs_Horde, 0x33c20}}},
  {0x3443c,
   {{GW::Constants::MapID::Gate_of_Desolation, 0x3443c}}},
  {0x336b4,
   {{GW::Constants::MapID::Champions_Dawn_outpost, 0x336b4},
    {GW::Constants::MapID::Cliffs_of_Dohjok, 0x336b4}}},
  {0x34d11,
   {{GW::Constants::MapID::Fahranur_The_First_City, 0x34d11}}},
  {0x4706b,
   {{GW::Constants::MapID::Bjora_Marches, 0x4706b}}},
  {0x34d1f,
   {{GW::Constants::MapID::Zehlon_Reach, 0x34d1f}}},
  {0x34d34,
   {{GW::Constants::MapID::Lahtenda_Bog, 0x34d34}}},
  {0x4621e,
   {{GW::Constants::MapID::Arbor_Bay, 0x4621e},
    {GW::Constants::MapID::Vloxs_Falls, 0x4621e}}},
  {0x33727,
   {{GW::Constants::MapID::Issnur_Isles, 0x33727},
    {GW::Constants::MapID::Beknur_Harbor_outpost, 0x33727}}},
  {0x34d44,
   {{GW::Constants::MapID::Mehtani_Keys, 0x34d44}}},
  {0x3372c,
   {{GW::Constants::MapID::Kodlonu_Hamlet_outpost, 0x3372c}}},
  {0x336bf,
   {{GW::Constants::MapID::Jokanur_Diggings, 0x336bf}}},
  {0x336c5,
   {{GW::Constants::MapID::Blacktide_Den, 0x336c5}}},
  {0x34498,
   {{GW::Constants::MapID::Abaddons_Gate, 0x34498}}},
  {0x34c4c,
   {{GW::Constants::MapID::Sunspear_Arena, 0x34c4c}}},
  {0x4662b,
   {{GW::Constants::MapID::Ice_Cliff_Chasms, 0x4662b},
    {GW::Constants::MapID::Eye_of_the_North_outpost, 0x4662b},
    {GW::Constants::MapID::Hall_of_Monuments, 0x4662b},
    {GW::Constants::MapID::Boreal_Station_outpost, 0x4662b}}},
  {0x47051,
   {{GW::Constants::MapID::Riven_Earth, 0x47051}}},
  {0x336c2,
   {{GW::Constants::MapID::The_Astralarium_outpost, 0x336c2}}},
  {0x46801,
   {{GW::Constants::MapID::Drakkar_Lake, 0x46801},
    {GW::Constants::MapID::Sifhalla_outpost, 0x46801}}},
  {0x3321c,
   {{GW::Constants::MapID::Isle_of_Wurms_outpost, 0x3321c},
    {GW::Constants::MapID::Isle_of_Wurms, 0x3321c}}},
  {0x33056,
   {{GW::Constants::MapID::Uncharted_Isle, 0x33056}}},
  {0x3314e,
   {{GW::Constants::MapID::Corrupted_Isle_outpost, 0x3314e},
    {GW::Constants::MapID::Corrupted_Isle, 0x3314e}}},
  {0x334a2,
   {{GW::Constants::MapID::Isle_of_Solitude, 0x334a2}}},
  {0x3358c,
   {{GW::Constants::MapID::Remains_of_Sahlahja, 0x3358c}}},
  {0x4707f,
   {{GW::Constants::MapID::Jaga_Moraine, 0x4707f}}},
  {0x4693f,
   {{GW::Constants::MapID::Norrhart_Domains, 0x4693f},
    {GW::Constants::MapID::Gunnars_Hold_outpost, 0x4693f},
    {GW::Constants::MapID::The_Norn_Fighting_Tournament, 0x4693f},
    {GW::Constants::MapID::Kilroys_Punchout_Tournament, 0x4693f}}},
  {0x3c3ee,
   {{GW::Constants::MapID::Hero_Battles_outpost, 0x3c3ee},
    {GW::Constants::MapID::Codex_Arena_outpost, 0x3c3ee}}},
  {0x46b50,
   {{GW::Constants::MapID::Varajar_Fells, 0x46b50},
    {GW::Constants::MapID::Olafstead_outpost, 0x46b50}}},
  {0x33f38,
   {{GW::Constants::MapID::Dajkah_Inlet, 0x33f38}}},
  {0x3d526,
   {{GW::Constants::MapID::The_Shadow_Nexus, 0x3d526}}},
  {0x46305,
   {{GW::Constants::MapID::Sparkfly_Swamp, 0x46305},
    {GW::Constants::MapID::Gadds_Encampment_outpost, 0x46305}}},
  {0x47415,
   {{GW::Constants::MapID::Cathedral_of_Flames_Level_1, 0x47415}}},
  {0x03e0c9,
   {{GW::Constants::MapID::Dynastic_Tombs, 0x03e0c9}}},
  {0x463ba,
   {{GW::Constants::MapID::Verdant_Cascades, 0x463ba},
    {GW::Constants::MapID::Umbral_Grotto_outpost, 0x463ba}}},
  {0x46427,
   {{GW::Constants::MapID::Magus_Stones, 0x46427},
    {GW::Constants::MapID::Rata_Sum_outpost, 0x46427}}},
  {0x46547,
   {{GW::Constants::MapID::Alcazia_Tangle, 0x46547},
    {GW::Constants::MapID::Tarnished_Haven_outpost, 0x46547}}},
  {0x46db8,
   {{GW::Constants::MapID::Antechamber_mission, 0x46db8}}},
  {0x474fa,
   {{GW::Constants::MapID::Ooze_Pit, 0x474fa},
    {GW::Constants::MapID::Heart_of_the_Shiverpeaks_Level_1, 0x474fa}}},
  {0x4745d,
   {{GW::Constants::MapID::Vloxen_Excavations_Level_1, 0x4745d},
    {GW::Constants::MapID::Bogroot_Growths_Level_1, 0x4745d},
    {GW::Constants::MapID::Bogroot_Growths_Level_2, 0x4745d}}},
  {0x475cc,
   {{GW::Constants::MapID::Battledepths_Level_1, 0x475cc}}},
  {0x4759b,
   {{GW::Constants::MapID::Sepulchre_of_Dragrimmar_Level_2, 0x4759b}}},
  {0x46ca8,
   {{GW::Constants::MapID::Dalada_Uplands, 0x46ca8},
    {GW::Constants::MapID::Doomlore_Shrine_outpost, 0x46ca8}}},
  {0x46d85,
   {{GW::Constants::MapID::Grothmar_Wardowns, 0x46d85},
    {GW::Constants::MapID::Longeyes_Ledge_outpost, 0x46d85}}},
  {0x47144,
   {{GW::Constants::MapID::Sacnoth_Valley, 0x47144}}},
  {0x46d86,
   {{GW::Constants::MapID::Central_Transfer_Chamber_outpost, 0x46d86}}},
  {0x4720a,
   {{GW::Constants::MapID::The_Elusive_Golemancer_Level_1, 0x4720a}}},
  {0x47359,
   {{GW::Constants::MapID::Shards_of_Orr_Level_1, 0x47359},
    {GW::Constants::MapID::The_Elusive_Golemancer_Level_2, 0x47359},
    {GW::Constants::MapID::The_Elusive_Golemancer_Level_3, 0x47359}}},
  {0x4f717,
   {{GW::Constants::MapID::A_Time_for_Heroes, 0x4f717}}},
  {0x4f71c,
   {{GW::Constants::MapID::Cinematic_Eye_Vision_A, 0x4f71c},
    {GW::Constants::MapID::Cinematic_Eye_Vision_B, 0x4f71c},
    {GW::Constants::MapID::Cinematic_Eye_Vision_C, 0x4f71c},
    {GW::Constants::MapID::Cinematic_Eye_Vision_D, 0x4f71c}}},
  {0x47566,
   {{GW::Constants::MapID::Beneath_Lions_Arch, 0x47566},
    {GW::Constants::MapID::Tunnels_Below_Cantha, 0x47566},
    {GW::Constants::MapID::Caverns_Below_Kamadan, 0x47566}}},
  {0x475df,
   {{GW::Constants::MapID::Sepulchre_of_Dragrimmar_Level_1, 0x475df},
    {GW::Constants::MapID::Fronis_Irontoes_Lair_mission, 0x475df}}},
  {0x49f34,
   {{GW::Constants::MapID::Polymock_Coliseum, 0x49f34}}},
  {0x49f36,
   {{GW::Constants::MapID::Polymock_Glacier, 0x49f36}}},
  {0x49f38,
   {{GW::Constants::MapID::Polymock_Crossing, 0x49f38}}},
  {0xf653,
   {{GW::Constants::MapID::The_Underworld, 0xf653}}},
  {0xf652,
   {{GW::Constants::MapID::The_Fissure_of_Woe, 0xf652}}},
  {0x34c6e,
   {{GW::Constants::MapID::None, 0x34c6e}}},
  {0x5597a,
   {{GW::Constants::MapID::Zaishen_Menagerie_Grounds, 0x5597a},
    {GW::Constants::MapID::Zaishen_Menagerie_outpost, 0x5597a}}},
  {0x52a18,
   {{GW::Constants::MapID::Embark_Beach, 0x52a18}}},
  {0x5cf20,
   {{GW::Constants::MapID::None, 0x5cf20}}},
  {0x5d088,
   {{GW::Constants::MapID::None, 0x5d088}}},
  {0x5d068,
   {{GW::Constants::MapID::None, 0x5d068}}},
  {0x5cf22,
   {{GW::Constants::MapID::None, 0x5cf22}}},
};
