#pragma once

#include <GWCA/GameEntities/Map.h>

using Region = GW::Region;

static constexpr size_t ZAISHEN_BOUNTY_COUNT = 66;
static constexpr size_t ZAISHEN_MISSION_COUNT = 69;
static constexpr size_t ZAISHEN_COMBAT_COUNT = 28;
static constexpr size_t ZAISHEN_VANQUISH_COUNT = 136;
static constexpr size_t WANTED_COUNT = 21;
static constexpr size_t WEEKLY_BONUS_PVE_COUNT = 9;
static constexpr size_t WEEKLY_BONUS_PVP_COUNT = 6;
static constexpr size_t VANGUARD_COUNT = 9;
static constexpr size_t NICHOLAS_PRE_COUNT = 52;

enum class GameRegion {
    BATTLE_ISLES,
    THE_MISTS,
    PRE_SEARING,
    ASCALON,
    NORTHERN_SHIVERPEAKS,
    KRYTA,
    MAGUUMA_JUNGLE,
    CRYSTAL_DESERT,
    SOUTHERN_SHIVERPEAKS,
    RING_OF_FIRE_ISLANDS,
    SHING_JEA,
    KAINENG_CITY,
    ECHOVALD_FOREST,
    JADE_SEA,
    RAISU_PALACE,
    ISTAN,
    KOURNA,
    VABBI,
    DESOLATION,
    REALM_OF_TORMENT,
    FAR_SHIVERPEAKS,
    CHARR_HOMELANDS,
    TARNISHED_COAST,
    DEPTHS_OF_TYRIA,
};

struct NicholasCycleData {
    uint32_t model_id;
    uint32_t quantity;
    const char* english_name; // TODO: replace with enc_name
    const char* english_map_name; // TODO: replace with map id
    GameRegion region;
};

// TODO: Replace english text with encoded strings as much as possible

// TODO: enc quest names?  quest ids?
inline const char* VANGUARD_CYCLES[VANGUARD_COUNT] = {
    "Bandits",
    "Utini Wupwup",
    "Ascalonian Noble",
    "Undead",                // 0x8102 0x7050 0xFC72 0xBD17 0x552E
    "Blazefiend Griefblade",
    "Farmer Hamnet",
    "Charr",
    "Countess Nadya",
    "Footman Tate"
};

// TODO: enc names
inline const char* NICHOLAS_PRE_CYCLES[NICHOLAS_PRE_COUNT] = {
    "Grawl Necklaces",
    "Baked Husks",
    "Skeletal Limbs",
    "Unnatural Seeds",
    "Enchanted Lodestones",
    "Skale Fins",
    "Icy Lodestones",
    "Gargoyle Skulls",
    "Dull Carapaces",
    "Baked Husks",
    "Red Iris Flowers",
    "Spider Legs",
    "Skeletal Limbs",
    "Charr Carvings",
    "Enchanted Lodestones",
    "Grawl Necklaces",
    "Icy Lodestones",
    "Worn Belts",
    "Gargoyle Skulls",
    "Unnatural Seeds",
    "Skale Fins",
    "Red Iris Flowers",
    "Enchanted Lodestones",
    "Skeletal Limbs",
    "Charr Carvings",
    "Spider Legs",
    "Baked Husks",
    "Gargoyle Skulls",
    "Unnatural Seeds",
    "Icy Lodestones",
    "Grawl Necklaces",
    "Enchanted Lodestones",
    "Worn Belts",
    "Dull Carapaces",
    "Spider Legs",
    "Gargoyle Skulls",
    "Icy Lodestones",
    "Unnatural Seeds",
    "Worn Belts",
    "Grawl Necklaces",
    "Baked Husks",
    "Skeletal Limbs",
    "Red Iris Flowers",
    "Charr Carvings",
    "Skale Fins",
    "Dull Carapaces",
    "Enchanted Lodestones",
    "Charr Carvings",
    "Spider Legs",
    "Red Iris Flowers",
    "Worn Belts",
    "Dull Carapaces"
};

// TODO: enc names, map ids, add item type field as model id is not unique across types
inline const NicholasCycleData nicholas_post_cycles[137] = {
    { 2994, 3, "Red Iris Flowers", "Regent Valley", GameRegion::ASCALON, },
    { 498, 3, "Feathered Avicara Scalps", "Mineral Springs", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 1581, 2, "Margonite Masks", "Poisoned Outcrops", GameRegion::DESOLATION, },
    { 27039, 2, "Quetzal Crests", "Alcazia Tangle", GameRegion::TARNISHED_COAST, },
    { 805, 3, "Plague Idols", "Wajjun Bazaar", GameRegion::KAINENG_CITY, },
    { 496, 2, "Azure Remains", "Dreadnought's Drift", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 19170, 1, "Mandragor Root Cake", "Arkjok Ward", GameRegion::KOURNA, },
    { 513, 1, "Mahgo Claw", "Perdition Rock", GameRegion::RING_OF_FIRE_ISLANDS, },
    { 829, 5, "Mantid Pincers", "Saoshang Trail", GameRegion::SHING_JEA, },
    { 1601, 3, "Sentient Seeds", "Fahranur, The First City", GameRegion::ISTAN, },
    { 27053, 2, "Stone Grawl Necklaces", "Sacnoth Valley", GameRegion::CHARR_HOMELANDS, },
    { 26502, 1, "Herring", "Twin Serpent Lakes", GameRegion::KRYTA, },
    { 848, 3, "Naga Skins", "Mount Qinkai", GameRegion::JADE_SEA, },
    { 523, 1, "Gloom Seed", "The Falls", GameRegion::MAGUUMA_JUNGLE, },
    { 225, 1, "Charr Hide", "The Breach", GameRegion::ASCALON, },
    { 19187, 1, "Ruby Djinn Essence", "The Alkali Pan", GameRegion::DESOLATION, },
    { 467, 2, "Thorny Carapaces", "Majesty's Rest", GameRegion::KRYTA, },
    { 811, 3, "Bone Charms", "Rhea's Crater", GameRegion::JADE_SEA, },
    { 27043, 3, "Modniir Manes", "Varajar Fells", GameRegion::FAR_SHIVERPEAKS, },
    { 27052, 3, "Superb Charr Carvings", "Dalada Uplands", GameRegion::CHARR_HOMELANDS, },
    { 951, 5, "Rolls of Parchment", "Zen Daijun", GameRegion::SHING_JEA, },
    { 1679, 2, "Roaring Ether Claws", "Garden of Seborhin", GameRegion::VABBI, },
    { 19194, 3, "Branches of Juni Berries", "Bukdek Byway", GameRegion::KAINENG_CITY, },
    { 488, 3, "Shiverpeak Manes", "Deldrimor Bowl", GameRegion::NORTHERN_SHIVERPEAKS, },
    { 479, 3, "Fetid Carapaces", "Eastern Frontier", GameRegion::ASCALON, },
    { 1009, 2, "Moon Shells", "Gyala Hatchery", GameRegion::JADE_SEA, },
    { 452, 1, "Massive Jawbone", "The Arid Sea", GameRegion::CRYSTAL_DESERT, },
    { 27069, 1, "Chromatic Scale", "Ice Cliff Chasms", GameRegion::FAR_SHIVERPEAKS, },
    { 462, 3, "Mursaat Tokens", "Ice Floe", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 1619, 1, "Sentient Lodestone", "Bahdok Caverns", GameRegion::KOURNA, },
    { 471, 3, "Jungle Troll Tusks", "Tangle Root", GameRegion::MAGUUMA_JUNGLE, },
    { 19188, 1, "Sapphire Djinn Essence", "Resplendent Makuun", GameRegion::VABBI, },
    { 820, 1, "Stone Carving", "Arborstone", GameRegion::ECHOVALD_FOREST, },
    { 444, 3, "Feathered Caromi Scalps", "North Kryta Province", GameRegion::KRYTA, },
    { 1663, 1, "Pillaged Goods", "Holdings of Chokhin", GameRegion::VABBI, },
    { 807, 1, "Gold Crimson Skull Coin", "Haiju Lagoon", GameRegion::SHING_JEA, },
    { 809, 3, "Jade Bracelets", "Tahnnakai Temple", GameRegion::KAINENG_CITY, },
    { 455, 2, "Minotaur Horns", "Prophet's Path", GameRegion::CRYSTAL_DESERT, },
    { 493, 2, "Frosted Griffon Wings", "Snake Dance", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 1579, 2, "Silver Bullion Coins", "Mehtani Keys", GameRegion::ISTAN, },
    { 813, 1, "Truffle", "Morostav Trail", GameRegion::ECHOVALD_FOREST, },
    { 27040, 3, "Skelk Claws", "Verdant Cascades", GameRegion::TARNISHED_COAST, },
    { 454, 2, "Dessicated Hydra Claws", "The Scar", GameRegion::CRYSTAL_DESERT, },
    { 494, 3, "Frigid Hearts", "Spearhead Peak", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 855, 3, "Celestial Essences", "Nahpui Quarter", GameRegion::KAINENG_CITY, },
    { 474, 1, "Phantom Residue", "Lornar's Pass", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 17060, 1, "Drake Kabob", "Issnur Isles", GameRegion::ISTAN, },
    { 6532, 3, "Amber Chunks", "Ferndale", GameRegion::ECHOVALD_FOREST, },
    { 439, 2, "Glowing Hearts", "Stingray Strand", GameRegion::KRYTA, },
    { 27035, 5, "Saurian Bones", "Riven Earth", GameRegion::TARNISHED_COAST, },
    { 1675, 2, "Behemoth Hides", "Wilderness of Bahdza", GameRegion::VABBI, },
    { 1660, 1, "Luminous Stone", "Crystal Overlook", GameRegion::DESOLATION, },
    { 499, 3, "Intricate Grawl Necklaces", "Witman's Folly", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 6533, 3, "Jadeite Shards", "Shadow's Passage", GameRegion::KAINENG_CITY, },
    { 1578, 1, "Gold Doubloon", "Barbarous Shore", GameRegion::KOURNA, },
    { 446, 2, "Shriveled Eyes", "Skyward Reach", GameRegion::CRYSTAL_DESERT, },
    { 424, 2, "Icy Lodestones", "Icedome", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 847, 1, "Keen Oni Talon", "Silent Surf", GameRegion::JADE_SEA, },
    { 435, 2, "Hardened Humps", "Nebo Terrace", GameRegion::KRYTA, },
    { 27050, 2, "Piles of Elemental Dust", "Drakkar Lake", GameRegion::FAR_SHIVERPEAKS, },
    { 832, 3, "Naga Hides", "Panjiang Peninsula", GameRegion::SHING_JEA, },
    { 956, 3, "Spiritwood Planks", "Griffon's Mouth", GameRegion::NORTHERN_SHIVERPEAKS, },
    { 477, 1, "Stormy Eye", "Pockmark Flats", GameRegion::ASCALON, },
    { 1610, 3, "Skree Wings", "Forum Highlands", GameRegion::VABBI, },
    { 852, 3, "Soul Stones", "Raisu Palace", GameRegion::KAINENG_CITY, },
    { 434, 1, "Spiked Crest", "Tears of the Fallen", GameRegion::KRYTA, },
    { 819, 1, "Dragon Root", "Drazach Thicket", GameRegion::ECHOVALD_FOREST, },
    { 27046, 3, "Berserker Horns", "Jaga Moraine", GameRegion::FAR_SHIVERPEAKS, },
    { 465, 1, "Behemoth Jaw", "Mamnoon Lagoon", GameRegion::MAGUUMA_JUNGLE, },
    { 17061, 1, "Bowl of Skalefin Soup", "Zehlon Reach", GameRegion::ISTAN, },
    { 440, 2, "Forest Minotaur Horns", "Kessex Peak", GameRegion::KRYTA, },
    { 827, 3, "Putrid Cysts", "Sunjiang District", GameRegion::KAINENG_CITY, },
    { 457, 2, "Jade Mandibles", "Salt Flats", GameRegion::CRYSTAL_DESERT, },
    { 466, 2, "Maguuma Manes", "Silverwood", GameRegion::MAGUUMA_JUNGLE, },
    { 814, 1, "Skull Juju", "The Eternal Grove", GameRegion::ECHOVALD_FOREST, },
    { 1671, 3, "Mandragor Swamproots", "Lahtenda Bog", GameRegion::ISTAN, },
    { 19173, 1, "Bottle of Vabbian Wine", "Vehtendi Valley", GameRegion::VABBI, },
    { 27037, 2, "Weaver Legs", "Magus Stones", GameRegion::TARNISHED_COAST, },
    { 450, 1, "Topaz Crest", "Diviner's Ascent", GameRegion::CRYSTAL_DESERT, },
    { 842, 2, "Rot Wallow Tusks", "Pongmei Valley", GameRegion::KAINENG_CITY, },
    { 489, 2, "Frostfire Fangs", "Anvil Rock", GameRegion::NORTHERN_SHIVERPEAKS, },
    { 1580, 1, "Demonic Relic", "The Ruptured Heart", GameRegion::DESOLATION, },
    { 442, 2, "Abnormal Seeds", "Talmark Wilderness", GameRegion::KRYTA, },
    { 19186, 1, "Diamond Djinn Essence", "The Hidden City of Ahdashim", GameRegion::VABBI, },
    { 459, 2, "Forgotten Seals", "Vulture Drifts", GameRegion::CRYSTAL_DESERT, },
    { 806, 5, "Copper Crimson Skull Coins", "Kinya Province", GameRegion::SHING_JEA, },
    { 469, 3, "Mossy Mandibles", "Ettin's Back", GameRegion::MAGUUMA_JUNGLE, },
    { 532, 2, "Enslavement Stones", "Grenth's Footprint", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 943, 5, "Elonian Leather Squares", "Jahai Bluffs", GameRegion::KOURNA, },
    { 1609, 2, "Cobalt Talons", "Vehjin Mines", GameRegion::VABBI, },
    { 234, 1, "Maguuma Spider Web", "Reed Bog", GameRegion::MAGUUMA_JUNGLE, },
    { 825, 5, "Forgotten Trinket Boxes", "Minister Cho's Estate", GameRegion::SHING_JEA, },
    { 490, 3, "Icy Humps", "Iron Horse Mine", GameRegion::NORTHERN_SHIVERPEAKS, },
    { 1584, 1, "Sandblasted Lodestone", "The Shattered Ravines", GameRegion::DESOLATION, },
    { 841, 3, "Black Pearls", "Archipelagos", GameRegion::JADE_SEA, },
    { 1617, 3, "Insect Carapaces", "Marga Coast", GameRegion::KOURNA, },
    { 463, 3, "Mergoyle Skulls", "Watchtower Coast", GameRegion::KRYTA, },
    { 504, 3, "Decayed Orr Emblems", "Cursed Lands", GameRegion::KRYTA, },
    { 939, 5, "Tempered Glass Vials", "Mourning Veil Falls", GameRegion::ECHOVALD_FOREST, },
    { 486, 3, "Scorched Lodestones", "Old Ascalon", GameRegion::ASCALON, },
    { 19189, 1, "Water Djinn Essence", "Turai's Procession", GameRegion::DESOLATION, },
    { 849, 1, "Guardian Moss", "Maishang Hills", GameRegion::JADE_SEA, },
    { 5585, 6, "Dwarven Ales", "The Floodplain of Mahnkelon", GameRegion::KOURNA, },
    { 27036, 2, "Amphibian Tongues", "Sparkfly Swamp", GameRegion::TARNISHED_COAST, },
    { 497, 2, "Alpine Seeds", "Frozen Forest", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 468, 2, "Tangled Seeds", "Dry Top", GameRegion::MAGUUMA_JUNGLE, },
    { 840, 3, "Stolen Supplies", "Jaya Bluffs", GameRegion::SHING_JEA, },
    { 17062, 1, "Pahnai Salad", "Plains of Jarin", GameRegion::ISTAN, },
    { 853, 3, "Vermin Hides", "Xaquang Skyway", GameRegion::KAINENG_CITY, },
    { 1662, 1, "Roaring Ether Heart", "The Mirror of Lyss", GameRegion::VABBI, },
    { 484, 3, "Leathery Claws", "Ascalon Foothills", GameRegion::ASCALON, },
    { 844, 1, "Azure Crest", "Unwaking Waters", GameRegion::JADE_SEA, },
    { 27045, 1, "Jotun Pelt", "Bjora Marches", GameRegion::FAR_SHIVERPEAKS, },
    { 19199, 2, "Heket Tongues", "Dejarin Estate", GameRegion::KOURNA, },
    { 500, 5, "Mountain Troll Tusks", "Talus Chute", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 944, 3, "Vials of Ink", "Shenzun Tunnels", GameRegion::KAINENG_CITY, },
    { 1582, 3, "Kournan Pendants", "Gandara, the Moon Fortress", GameRegion::KOURNA, },
    { 480, 3, "Singed Gargoyle Skulls", "Diessa Lowlands", GameRegion::ASCALON, },
    { 818, 3, "Dredge Incisors", "Melandru's Hope", GameRegion::ECHOVALD_FOREST, },
    { 502, 3, "Stone Summit Badges", "Tasca's Demise", GameRegion::SOUTHERN_SHIVERPEAKS, },
    { 27729, 3, "Krait Skins", "Arbor Bay", GameRegion::TARNISHED_COAST, },
    { 1587, 2, "Inscribed Shards", "Joko's Domain", GameRegion::DESOLATION, },
    { 836, 3, "Feathered Scalps", "Sunqua Vale", GameRegion::SHING_JEA, },
    { 1583, 3, "Mummy Wrappings", "The Sulfurous Wastes", GameRegion::DESOLATION, },
    { 441, 2, "Shadowy Remnants", "The Black Curtain", GameRegion::KRYTA, },
    { 856, 3, "Ancient Kappa Shells", "The Undercity", GameRegion::KAINENG_CITY, },
    { 1681, 1, "Geode", "Yatendi Canyons", GameRegion::VABBI, },
    { 27051, 2, "Fibrous Mandragor Roots", "Grothmar Wardowns", GameRegion::CHARR_HOMELANDS, },
    { 482, 3, "Gruesome Ribcages", "Dragon's Gullet", GameRegion::ASCALON, },
    { 843, 2, "Kraken Eyes", "Boreas Seabed", GameRegion::JADE_SEA, },
    { 443, 3, "Bog Skale Fins", "Scoundrel's Rise", GameRegion::KRYTA, },
    { 19198, 2, "Sentient Spores", "Sunward Marches", GameRegion::KOURNA, },
    { 464, 2, "Ancient Eyes", "Sage Lands", GameRegion::MAGUUMA_JUNGLE, },
    { 1577, 3, "Copper Shillings", "Cliffs of Dohjok", GameRegion::ISTAN, },
    { 27042, 3, "Frigid Mandragor Husks", "Norrhart Domains", GameRegion::FAR_SHIVERPEAKS, },
    { 926, 3, "Bolts of Linen", "Traveler's Vale", GameRegion::NORTHERN_SHIVERPEAKS, },
    { 423, 3, "Charr Carvings", "Flame Temple Corridor", GameRegion::ASCALON }
};

// TODO: enc names
inline const char* zaishen_bounty_cycles[ZAISHEN_BOUNTY_COUNT] = {
    "Droajam, Mage of the Sands",
    "Royen Beastkeeper",
    "Eldritch Ettin",
    "Vengeful Aatxe",
    "Fronis Irontoe",
    "Urgoz",
    "Fenrir",
    "Selvetarm",
    "Mohby Windbeak",
    "Charged Blackness",
    "Rotscale",
    "Zoldark the Unholy",
    "Korshek the Immolated",
    "Myish, Lady of the Lake",
    "Frostmaw the Kinslayer",
    "Kunvie Firewing",
    "Z'him Monns",
    "The Greater Darkness",
    "TPS Regulator Golem",
    "Plague of Destruction",
    "The Darknesses",
    "Admiral Kantoh",
    "Borrguus Blisterbark",
    "Forgewight",
    "Baubao Wavewrath",
    "Joffs the Mitigator",
    "Rragar Maneater",
    "Chung, the Attuned",
    "Lord Jadoth",
    "Nulfastu, Earthbound",
    "The Iron Forgeman",
    "Magmus",
    "Mobrin, Lord of the Marsh",
    "Jarimiya the Unmerciful",
    "Duncan the Black",
    "Quansong Spiritspeak",
    "The Stygian Underlords",
    "Fozzy Yeoryios",
    "The Black Beast of Arrgh",
    "Arachni",
    "The Four Horsemen",
    "Remnant of Antiquities",
    "Arbor Earthcall",
    "Prismatic Ooze",
    "Lord Khobay",
    "Jedeh the Mighty",
    "Ssuns, Blessed of Dwayna",
    "Justiciar Thommis",
    "Harn and Maxine Coldstone",
    "Pywatt the Swift",
    "Fendi Nin",
    "Mungri Magicbox",
    "Priest of Menzies",
    "Ilsundur, Lord of Fire",
    "Kepkhet Marrowfeast",
    "Commander Wahli",
    "Kanaxai",
    "Khabuus",
    "Molotov Rocktail",
    "The Stygian Lords",
    "Dragon Lich",
    "Havok Soulwail",
    "Ghial the Bone Dancer",
    "Murakai, Lady of the Night",
    "Rand Stormweaver",
    "Verata"
};

// TODO: enc names
const char* zaishen_combat_cycles[ZAISHEN_COMBAT_COUNT] = {
    "Jade Quarry",
    "Codex Arena",
    "Heroes' Ascent",
    "Guild Versus Guild",
    "Alliance Battles",
    "Heroes' Ascent",
    "Guild Versus Guild",
    "Codex Arena",
    "Fort Aspenwood",
    "Jade Quarry",
    "Random Arena",
    "Codex Arena",
    "Guild Versus Guild",
    "Jade Quarry",
    "Alliance Battles",
    "Heroes' Ascent",
    "Random Arena",
    "Fort Aspenwood",
    "Jade Quarry",
    "Random Arena",
    "Fort Aspenwood",
    "Heroes' Ascent",
    "Alliance Battles",
    "Guild Versus Guild",
    "Codex Arena",
    "Random Arena",
    "Fort Aspenwood",
    "Alliance Battles"
};

// TODO: enc names/mission ids/something
const char* zaishen_mission_cycles[ZAISHEN_MISSION_COUNT] = {
    "Augury Rock",
    "Grand Court of Sebelkeh",
    "Ice Caves of Sorrow",
    "Raisu Palace",
    "Gate of Desolation",
    "Thirsty River",
    "Blacktide Den",
    "Against the Charr",
    "Abaddon's Mouth",
    "Nundu Bay",
    "Divinity Coast",
    "Zen Daijun",
    "Pogahn Passage",
    "Tahnnakai Temple",
    "The Great Northern Wall",
    "Dasha Vestibule",
    "The Wilds",
    "Unwaking Waters",
    "Chahbek Village",
    "Aurora Glade",
    "A Time for Heroes",
    "Consulate Docks",
    "Ring of Fire",
    "Nahpui Quarter",
    "The Dragon's Lair",
    "Dzagonur Bastion",
    "D'Alessio Seaboard",
    "Assault on the Stronghold",
    "The Eternal Grove",
    "Sanctum Cay",
    "Rilohn Refuge",
    "Warband of Brothers",
    "Borlis Pass",
    "Imperial Sanctum",
    "Moddok Crevice",
    "Nolani Academy",
    "Destruction's Depths",
    "Venta Cemetery",
    "Fort Ranik",
    "A Gate Too Far",
    "Minister Cho's Estate",
    "Thunderhead Keep",
    "Tihark Orchard",
    "Finding the Bloodstone",
    "Dunes of Despair",
    "Vizunah Square",
    "Jokanur Diggings",
    "Iron Mines of Moladune",
    "Kodonur Crossroads",
    "G.O.L.E.M.",
    "Arborstone",
    "Gates of Kryta",
    "Gate of Madness",
    "The Elusive Golemancer",
    "Riverside Province",
    "Boreas Seabed",
    "Ruins of Morah",
    "Hell's Precipice",
    "Ruins of Surmia",
    "Curse of the Nornbear",
    "Sunjiang District",
    "Elona Reach",
    "Gate of Pain",
    "Blood Washes Blood",
    "Bloodstone Fen",
    "Jennur's Horde",
    "Gyala Hatchery",
    "Abaddon's Gate",
    "The Frost Gate"
};

// TODO: enc names/map ids/something
const char* zaishen_vanquish_cycles[ZAISHEN_VANQUISH_COUNT] = {
    "Jaya Bluffs",
    "Holdings of Chokhin",
    "Ice Cliff Chasms",
    "Griffon's Mouth",
    "Kinya Province",
    "Issnur Isles",
    "Jaga Moraine",
    "Ice Floe",
    "Maishang Hills",
    "Jahai Bluffs",
    "Riven Earth",
    "Icedome",
    "Minister Cho's Estate",
    "Mehtani Keys",
    "Sacnoth Valley",
    "Iron Horse Mine",
    "Morostav Trail",
    "Plains of Jarin",
    "Sparkfly Swamp",
    "Kessex Peak",
    "Mourning Veil Falls",
    "The Alkali Pan",
    "Varajar Fells",
    "Lornar's Pass",
    "Pongmei Valley",
    "The Floodplain of Mahnkelon",
    "Verdant Cascades",
    "Majesty's Rest",
    "Raisu Palace",
    "The Hidden City of Ahdashim",
    "Rhea's Crater",
    "Mamnoon Lagoon",
    "Shadow's Passage",
    "The Mirror of Lyss",
    "Saoshang Trail",
    "Nebo Terrace",
    "Shenzun Tunnels",
    "The Ruptured Heart",
    "Salt Flats",
    "North Kryta Province",
    "Silent Surf",
    "The Shattered Ravines",
    "Scoundrel's Rise",
    "Old Ascalon",
    "Sunjiang District",
    "The Sulfurous Wastes",
    "Magus Stones",
    "Perdition Rock",
    "Sunqua Vale",
    "Turai's Procession",
    "Norrhart Domains",
    "Pockmark Flats",
    "Tahnnakai Temple",
    "Vehjin Mines",
    "Poisoned Outcrops",
    "Prophet's Path",
    "The Eternal Grove",
    "Tasca's Demise",
    "Resplendent Makuun",
    "Reed Bog",
    "Unwaking Waters",
    "Stingray Strand",
    "Sunward Marches",
    "Regent Valley",
    "Wajjun Bazaar",
    "Yatendi Canyons",
    "Twin Serpent Lakes",
    "Sage Lands",
    "Xaquang Skyway",
    "Zehlon Reach",
    "Tangle Root",
    "Silverwood",
    "Zen Daijun",
    "The Arid Sea",
    "Nahpui Quarter",
    "Skyward Reach",
    "The Scar",
    "The Black Curtain",
    "Panjiang Peninsula",
    "Snake Dance",
    "Traveler's Vale",
    "The Breach",
    "Lahtenda Bog",
    "Spearhead Peak",
    "Mount Qinkai",
    "Marga Coast",
    "Melandru's Hope",
    "The Falls",
    "Joko's Domain",
    "Vulture Drifts",
    "Wilderness of Bahdza",
    "Talmark Wilderness",
    "Vehtendi Valley",
    "Talus Chute",
    "Mineral Springs",
    "Anvil Rock",
    "Arborstone",
    "Witman's Folly",
    "Arkjok Ward",
    "Ascalon Foothills",
    "Bahdok Caverns",
    "Cursed Lands",
    "Alcazia Tangle",
    "Archipelagos",
    "Eastern Frontier",
    "Dejarin Estate",
    "Watchtower Coast",
    "Arbor Bay",
    "Barbarous Shore",
    "Deldrimor Bowl",
    "Boreas Seabed",
    "Cliffs of Dohjok",
    "Diessa Lowlands",
    "Bukdek Byway",
    "Bjora Marches",
    "Crystal Overlook",
    "Diviner's Ascent",
    "Dalada Uplands",
    "Drazach Thicket",
    "Fahranur, the First City",
    "Dragon's Gullet",
    "Ferndale",
    "Forum Highlands",
    "Dreadnought's Drift",
    "Drakkar Lake",
    "Dry Top",
    "Tears of the Fallen",
    "Gyala Hatchery",
    "Ettin's Back",
    "Gandara, the Moon Fortress",
    "Grothmar Wardowns",
    "Flame Temple Corridor",
    "Haiju Lagoon",
    "Frozen Forest",
    "Garden of Seborhin",
    "Grenth's Footprint"
};

// TODO: enc names etc
const char* wanted_by_shining_blade_cycles[WANTED_COUNT] = {
    "Justiciar Kimii",
    "Zaln the Jaded",
    "Justiciar Sevaan",
    "Insatiable Vakar",
    "Amalek the Unmerciful",
    "Carnak the Hungry",
    "Valis the Rampant",
    "Cerris",
    "Sarnia the Red-Handed",
    "Destor the Truth Seeker",
    "Selenas the Blunt",
    "Justiciar Amilyn",
    "Maximilian the Meticulous",
    "Joh the Hostile",
    "Barthimus the Provident",
    "Calamitous",
    "Greves the Overbearing",
    "Lev the Condemned",
    "Justiciar Marron",
    "Justiciar Kasandra",
    "Vess the Disputant"
};

// TODO: enc strings?  should probably be some for login screen bonus info
const char* pve_weekly_bonus_cycles[WEEKLY_BONUS_PVE_COUNT] = {
    "Extra Luck",
    "Elonian Support",
    "Zaishen Bounty",
    "Factions Elite",
    "Northern Support",
    "Zaishen Mission",
    "Pantheon",
    "Faction Support",
    "Zaishen Vanquishing"
};

// TODO: enc strings?  should probably be some for login screen bonus info
const char* pve_weekly_bonus_descriptions[9] = {
    "Keys and lockpicks drop at four times the usual rate and double Lucky and Unlucky title points",
    "Double Sunspear and Lightbringer points",
    "Double copper Zaishen Coin rewards for Zaishen bounties",
    "The Deep and Urgoz's Warren can be entered from Kaineng Center",
    "Double Asura, Deldrimor, Ebon Vanguard, or Norn reputation points",
    "Double copper Zaishen Coin rewards for Zaishen missions",
    "Free passage to the Underworld and the Fissure of Woe",
    "Double Kurzick and Luxon title track points for exchanging faction",
    "Double copper Zaishen Coin rewards for Zaishen vanquishes"
};

// TODO: enc strings?  should probably be some for login screen bonus info
const char* pvp_weekly_bonus_cycles[WEEKLY_BONUS_PVP_COUNT] = {
    "Random Arenas",
    "Guild Versus Guild",
    "Competitive Mission",
    "Heroes' Ascent",
    "Codex Arena",
    "Alliance Battle"
};

// TODO: enc strings?  should probably be some for login screen bonus info
const char* pvp_weekly_bonus_descriptions[6] = {
    "Double Balthazar faction and Gladiator title points in Random Arenas",
    "Double Balthazar faction and Champion title points in GvG",
    "Double Balthazar and Imperial faction in the Jade Quarry and Fort Aspenwood",
    "Double Balthazar faction and Hero title points in Heroes' Ascent",
    "Double Balthazar faction and Codex title points in Codex Arena",
    "Double Balthazar and Imperial faction in Alliance Battles"
};
